### ISSUE TITLE
Integrated with angular2-seed

### ISSUE THREAD

**Issue by kietphamtps** [DanielYKPan/date-time-picker#1]
Dear Daniel, 

I tried to integrated your ng2-date-time-picker into angular2-seed:
https://github.com/mgechev/angular-seed

but it doesn't work...

Can you help on this? Thanks

**Comment by DanielYKPan** [comment]
@kietphamtps
Hi, kietphamtps,

Sorry for the late response.
I downloaded the angular-seed project you provided, and installed the package ng2-date-time-picker package. And It worked.

What you need to do is to import the DateTimePickerModule into your module: 

For example in the home.module.ts
```javascript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HomeComponent } from './home.component';
import { HomeRoutingModule } from './home-routing.module';
import { SharedModule } from '../shared/shared.module';
import { NameListService } from '../shared/name-list/index';
import { DateTimePickerModule } from 'ng2-date-time-picker/dist/date-time-picker.module';

@NgModule({
    imports: [CommonModule, HomeRoutingModule, SharedModule, DateTimePickerModule],
    declarations: [HomeComponent],
    exports: [HomeComponent],
    providers: [NameListService]
})
export class HomeModule {
}
```
