### ISSUE TITLE
Confirm\Cancel buttons customizing

### ISSUE THREAD

**Issue by filosof86** [DanielYKPan/date-time-picker#102]
Hi,

First of all, let me thank you for the amazing application. You really did a great work.

And the question. Is it possible to customize the confirm\cancel buttons (for example replace icons with buttons or change the icons) without modifying your source code? do you have any plans to implement such a possibility?

Thank you in advance.

**Comment by DanielYKPan** [comment]
The confirm and cancel button are under '.owl-foot-control .control-btn' class.
You could override the shape or the color of the button by using this class.
PS: the tick and cross icons inside the button are SVG. If you want to change to color of those icons, please use property 'fill'

**Comment by guidosreis** [comment]
Is it possible to change button text?
