### ISSUE TITLE
[minMoment] error : Can't bind to 'minMoment' since it isn't a known property of 'input'. 

### ISSUE THREAD

**Issue by karocksjoelee** [DanielYKPan/date-time-picker#104]
`<input [ngModel]="startDateValue | date: 'y-MM-dd'" id="input" type="text" class="btn btn-outline-primary hover-style " [theme]="'#3498DB'" [dateTimePicker]="startDateValue" [pickerType]="'date'" [locale]="'zh_TW'" (dateTimePickerConfirm)="setStartDate($event)" [minMoment]="'2015-01-01'" readonly>`

here is my component template .
I had import the module , setting date works as charm , but don't know why [minMoment] is not working

**Comment by DanielYKPan** [comment]
Please follow the README.md
