### ISSUE TITLE
Picker Type: Time not update UI in the first time it load

### ISSUE THREAD

**Issue by KeitaElric** [DanielYKPan/date-time-picker#105]
Hey @DanielYKPan, pls review my issues 😄 

HTML
`<input class="form-control" [(ngModel)]="time" dateTimePicker
             [value]="reminderConfig.time" [mode]="'inline'"
             [returnObject]="'string'" [viewFormat]="'HH:mm'" [pickerType]="'time'" readonly>`

TS
`let time = '05:55';`

When I run code and get dialog as image below
![image](https://user-images.githubusercontent.com/18684466/28995484-8c57bb48-7a14-11e7-9f92-fc94cafe806e.png)

I trying change time = new Date() and set hours, minutes.

It don't update control in the first time and then I pick time, submit and open picker again, it updated control and worked well.

I realize it also not update UI with Reactive Form in the first time.

I using Angular v4 and Webpack.

**Comment by DanielYKPan** [comment]
Try the package version @4.3.2

See if this fixed the issues
