### ISSUE TITLE
Event on click X button, or onClose event not working.

### ISSUE THREAD

**Issue by amankhurana812** [DanielYKPan/date-time-picker#112]
Event on click X button, or onClose event not working.

I have a use case in which I have to clear the date ( if had selected before ) on click on X button. I have tried to write (close)="anyfunction()", onClose ="anyfunction()" ,but this function didn't trigger on pressing the close function.
Can somebody please help.

**Comment by DanielYKPan** [comment]
@amankhurana812 
Could you provide a git repo to demonstrate the issue?
