### ISSUE TITLE
Dutch Locale

### ISSUE THREAD

**Issue by utataroglu** [DanielYKPan/date-time-picker#121]
Hi Daniel Pan,

I used local nl but this is not supported completely.
I want the dutch locale.
Below is information what is seen in screen after placing locale is nl.
Also is added what should different

![calendar dutch locale time](https://user-images.githubusercontent.com/11899868/29562964-dce13074-873b-11e7-84a7-785181064dc8.jpg)
![calendar dutch locale date](https://user-images.githubusercontent.com/11899868/29562965-dce2af26-873b-11e7-90d3-5e55fc1f6263.jpg)

The following should be different. The rest is ok
Today -> Vandaag
Cancel -> Annuleer
Confirm -> Bevestigen
Time Picker -> Tijd Selectie
Set Time -> Zet tijd
Hour -> Uur
Minute -> Minuut

Already thanks.

**Comment by DanielYKPan** [comment]
Please, use version v4.3.2
