### ISSUE TITLE
Lost background and highlights when using Bootstrap 4

### ISSUE THREAD

**Issue by Kenya-West** [DanielYKPan/date-time-picker#123]
Steps to reproduce:
1. `npm i -g @angular/cli`

2. ```
    ng new PROJECT-NAME
    cd PROJECT-NAME
    ng serve
    ```

3. `npm i bootstrap^4.0.0-beta`
4. Connect everything
5. Create a new component `ng g test-component` and paste the following here:

```
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Book a room</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <br>
        <h4 class="font-weight-normal">Booking date and time</h4>
        <owl-date-time [(ngModel)]="dateValue"></owl-date-time>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Book</button>
      </div>
    </div>
  </div>
</div>

```

Looks like this:

![gentlerareboutu-size_restricted 1](https://user-images.githubusercontent.com/12271104/29967216-896dfd74-8f50-11e7-8843-a1c2953232b6.gif)

P. S. Can't build[ similar reproduction](https://stackblitz.com/edit/angular-m8kukd) in Stackblitz online editor, there are template parse errors.

**Comment by DanielYKPan** [comment]
Please follow the How to Use Guild in README.md to add the style sheet
