### ISSUE TITLE
Error: ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by handyCAPS** [DanielYKPan/date-time-picker#125]
Using Angular 4 I keep getting this error from DateTimePickerComponent.html line 7. Can't find any information on it.

**Comment by DanielYKPan** [comment]
Could you build a plurk to demonstrate the issue?

**Comment by geraldhumphries** [comment]
I ran into the same issue while trying this component out for the first time. I'd create a Plunker for it but I'm having a hard time getting the deps set up.

The error happens on `<tr class="owl-days" *ngFor="let week of calendarDays">`

`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'.`

**Comment by geraldhumphries** [comment]
I get the error while using the component in a dynamically loaded component (an ng-bootstrap modal that [uses a component as content](https://ng-bootstrap.github.io/#/components/modal/examples)), but not while using it in a regular component.

**Comment by DanielYKPan** [comment]
@geraldhumphries 
Could you use angular-cli to create a simple project and publish to git repo to demonstrate the issue?
In this case, I could download the repo and debug it

**Comment by geraldhumphries** [comment]
Sure. I'll do that later today.

**Comment by geraldhumphries** [comment]
Here's the repo: https://github.com/geraldhumphries/date-time-picker-error

Pull, `npm install`, then `npm run start`. Visit `localhost:4200`. The datetime picker still works but the error is thrown in the console.

I was able to reproduce it without using a dynamically loaded component. I had to leave out `ngModel` because I was getting the error `Can't bind to 'ngModel' since it isn't a known property of 'owl-date-time'.`. This makes me think I'm doing something wrong.

**Comment by DanielYKPan** [comment]
You could not bing to ngModel because ngModel comes from FormsModule. Once you add FormsModule to your app, everything works fine.

**Comment by BlankHrt** [comment]
have you solved the problem yet ?
i also met the error
this is my code

```html
            <owl-date-time name="date" [showHeader]="true" [inline]="true" [inputId]="'input10'"></owl-date-time>

```
error:
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object],[object Object],[object Object],[object Object]...

**Comment by DanielYKPan** [comment]
@BlankHrt 
Please bind to the [(ngModel)]

**Comment by BlankHrt** [comment]
@DanielYKPan yes
```html
            <owl-date-time name="date" [(ngModel)]="date" [showHeader]="true" [inline]="true" [inputId]="'input10'"></owl-date-time>
```
still has this error
