### ISSUE TITLE
Not prefixed icons overwriting app-styles

### ISSUE THREAD

**Issue by burnaDLX** [DanielYKPan/date-time-picker#126]
Hi, I'm using the font-awesome icon set and it seems like your stylesheet (especially your wildcard rule for your icon class) is overwriting some of my icon related app styles. Could you prefix them, like you do it with your other classes or encapsulate your styles?

EDIT: I'm using your datepicker in version 5.0.0-beta3

**Comment by DanielYKPan** [comment]
That's weird. Because the icons i am using has class **icon icon-*** which i think is different from font-awesome.

**Comment by burnaDLX** [comment]
Yeah, you're right. After looking more exact, I noticed it's the way we integrated and customized the icon font (with helper classes like icon-left or icon-right for positioning, which where affected) in our app. Nevertheless I think it's better, if you could encapsulate or prefix your icon classes to be more unobstrusive, because 'icon-*' named classes are common used by people in projects.

**Comment by shavin47** [comment]
Default icomoon icon export uses icon- suggest you change it!
