### ISSUE TITLE
Set default time for time picker. when [pickerType]="'time'"

### ISSUE THREAD

**Issue by iqbalsibili** [DanielYKPan/date-time-picker#131]
Time picker is always default to current time. is there any way to set a default time for the time picker?
Versions using,
angular: 4.3.2
"ng-pick-datetime": "^4.3.2",

**Comment by DanielYKPan** [comment]
You could provide you default value on you [ngModel] binding

**Comment by iqbalsibili** [comment]
Thank you very much for responding. 
I have tried to give in [ngModel] then i am facing two problems. 
1. I have to pass the Date() object to [ngModel] to set the default and which is displaying in my model text box as well. I need only time in my text box. 

2. even if I give date() object, the time picker sliders are default to current time. only the top label of time changed to what I set. 

Please let me know if there any way.

![image](https://user-images.githubusercontent.com/7020768/30112916-930310e8-9330-11e7-9e15-1269688614b6.png)

**Comment by DanielYKPan** [comment]
@iqbalsibili 
First of all, the picker has been update to version 5. It has completely different properties from previous versions. You could read more about this from README.

Secondly, now in version 5, there is [defaultMoment] property, which I guess is what you want. You could also read more about this property from README.
