### ISSUE TITLE
Error when using from VS2017.3 Angular template

### ISSUE THREAD

**Issue by henrikdahl8240** [DanielYKPan/date-time-picker#132]
I have made a project using Visual Studio 2017.3's Angular template.

I have followed the instructions except on SystemJS because the template configures for WebPack and not SystemJS.

I have verified in vendor.js. that the DateTimePickerComponent indeed has been included.

As I run my web app, I get these exceptions in the console of Google Chrome:
Uncaught Error: Template parse errors:
'owl-date-time' is not a known element:
1. If 'owl-date-time' is an Angular component, then verify that it is part of this module.
2. If 'owl-date-time' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<td>
    [ERROR ->]<owl-date-time [(ngModel)]="xxx.ValidFrom"></owl-date-time>
    : ng:///yyy.html@1:4
'owl-date-time' is not a known element:
1. If 'owl-date-time' is an Angular component, then verify that it is part of this module.
2. If 'owl-date-time' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
<td>
    [ERROR ->]<owl-date-time [(ngModel)]="xxx.ValidTo"></owl-date-time>

Am I missing something or basically, how to make it to operate?

**Comment by DanielYKPan** [comment]
The error message means you haven't properly import the DateTimePickerModule into your app
