### ISSUE TITLE
Readme for contributions

### ISSUE THREAD

**Issue by culli** [DanielYKPan/date-time-picker#136]
Would you add a readme for contributions?  I'd like to try sending a pull request, but the latest code seems to be missing files references in the webpack config and I thought maybe I missed a step.

```
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src/polyfills.ts
Module not found: Error: Can't resolve './src/polyfills.ts' in 'projects/date-time-picker'
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/polyfills.ts

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src/vendor.ts
Module not found: Error: Can't resolve './src/vendor.ts' in 'projects/date-time-picker'
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/vendor.ts

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts
Module not found: Error: Can't resolve './src/main.ts' in 'projects/date-time-picker'
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts

```

**Comment by culli** [comment]
I figured out what I was doing wrong.  The build is actually done by gulp, and not by package.json scripts.

**Comment by igormilla** [comment]
@culli did you ended up running it from master branch? I'm getting the same errors you got when trying to run: **npm run**. Even after doing **gulp all**

**Comment by culli** [comment]
What are you trying to do with the run?  I'm not sure why it's even there in the package.json, since this is an npm library.

**Comment by igormilla** [comment]
I just wanted to figure out what was the dev process of author while he was developing this library. 

If you switch to development branch, which has an older version of this library, you will see that it has slightly different structure of files, and those npm scripts do work there. And they work as any typically angular project: you start the serve, work on your code, make a change, click save, and see your changes instantly in a browser.

**Comment by culli** [comment]
A pretty typical way to work on a library is to `npm link` from a demo project.  Alternatively, if you check out the `gh-pages` branch in this project with a little work you can get it running and use the demo page that is seen in github.  I don't remember the details of what I had to do to get that running, but it wasn't too hard.

**Comment by igormilla** [comment]
Never heard of `npm link`, that seems like a handy option, thanks for mentioning it. Before i was tweaking master branch with files from `gh-pages`, to be able to have fresh code, with live reload environment.
