### ISSUE TITLE
Setting the timezone in the datepicker

### ISSUE THREAD

**Issue by itsmekhanh** [DanielYKPan/date-time-picker#140]
Currently using 4.3.2, is there any way that we can pass in the timezone for the datepicker? Whenever I update the time or the date, it's only considering the browser's current timezone. For example, I want to show 2pm in central time on the input field but it's showing 12pm PST.

**Comment by DanielYKPan** [comment]
@itsmekhanh 
First of all, the picker has been updated to version 5 which is completely different from version 4. You could read more about it on README.

Secondly, in version 5, there is a property named 'defaultMoment'. This [defaultMoment] allows you to set the picker's default value and you could provide a Javascript Date object with your desired timezone. I guess this is what you want.
