### ISSUE TITLE
ngModelChange or equivalent?

### ISSUE THREAD

**Issue by jaya55** [DanielYKPan/date-time-picker#141]
Using version 5.0.0 beta 5 with Angular 4. I'm looking for a callback function that fires when the model is changed by the datetimepicker. NgModelChange doesn't seem to work. I tried OnBlur, but it doesn't seem to work properly. The event fires when I hit the right arrow to go to the next month. Then doesn't fire after that. 

I need something that fires when the date/time is selected. Am I missing something?

**Comment by DanielYKPan** [comment]
(ngModelChange) should be fired when you selected a date or time

**Comment by enavarro222** [comment]
I can confirm : (ngModelChange) works fine
