### ISSUE TITLE
Disable Dates Does not work.

### ISSUE THREAD

**Issue by mi1olson** [DanielYKPan/date-time-picker#142]
Hi, Daniel
The datetimepicker disable dates does not work, how can use this function?

**Comment by DanielYKPan** [comment]
@mi1olson 
use [disabledDates] = [JS Date Object]

**Comment by DanielYKPan** [comment]
I would close this issue as you haven't given any further information

**Comment by mi1olson** [comment]
Can't, i use this way disable ady.
but it still cant work.
disabledDates = [new Date(2017, 9, 8)];
