### ISSUE TITLE
Example inline style

### ISSUE THREAD

**Issue by johaven** [DanielYKPan/date-time-picker#143]
```js
[style]="'width: 100px'"
```
Give me this error: _Cannot find a differ supporting object 'width: 100px'_

**Comment by DanielYKPan** [comment]
[style] is pretty much like the way you use ngStyle from angular. It only accepts an Object. But what you provided is a pure string.

**Comment by y4nnick** [comment]
I am still getting the same error for `inputStyle="{'height':'34px'}"` .
Could you please provide a sample?

**Comment by y4nnick** [comment]
Never mind: ` [inputStyle]="{'height':'34px'}"` is working fine.

Thanks for your work!
