### ISSUE TITLE
Display Issues in IE10

### ISSUE THREAD

**Issue by jpilfold-diig** [DanielYKPan/date-time-picker#147]
The component currently does not work in IE10, because of the use of the `hidden` attribute.

It looks like this could probably be fixed by replacing it with `*ngIf`

**Comment by DanielYKPan** [comment]
@jpilfold-diig 
Yes, because IE9/10 doesn't have property [hidden].
You could find more about this in [here](https://github.com/angular/angular/issues/5774)
