### ISSUE TITLE
Can't Use FontAwesome Icon 

### ISSUE THREAD

**Issue by shubh4git** [DanielYKPan/date-time-picker#148]
I am not able to use fontawesome icon. Because You override Icon css.

**Comment by DanielYKPan** [comment]
I didn't overwrite any font-awesome icon class as my icon class name is **icon-*** which is different from font-awesome ('fa-*')

**Comment by shubh4git** [comment]
There are some icons in fontaewsome which uses icon- Please provide some solution .

**Comment by DanielYKPan** [comment]
@shubh4git 
Which ones use icon-?

**Comment by shubh4git** [comment]
There is icon-star, icon-speedometer

**Comment by shubh4git** [comment]
Thank You For this Wonderfull DatePicker I have solved my problem By Overiding Your picker.css File.
