### ISSUE TITLE
Expression has changed after it was checked

### ISSUE THREAD

**Issue by AmineBena17** [DanielYKPan/date-time-picker#150]
Hi !

i tried to add the module to my component and it works successfully, but i still have one bug and i still don't know the source of this one :
 DateTimePickerComponent.ngfactory.js:263 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'.
    at viewDebugError (vendor.bundle.js:93186)
    at expressionChangedAfterItHasBeenCheckedError (vendor.bundle.js:93164)
    at checkBindingNoChanges (vendor.bundle.js:93328)
    at checkNoChangesNodeInline (vendor.bundle.js:97200)
    at checkNoChangesNode (vendor.bundle.js:97174)
    at debugCheckNoChangesNode (vendor.bundle.js:97954)
    at debugCheckDirectivesFn (vendor.bundle.js:97856)
    at Object.View_DateTimePickerComponent_5._co [as updateDirectives] (DateTimePickerComponent.ngfactory.js:306)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.bundle.js:97838)
    at checkNoChangesView (vendor.bundle.js:96994)

 thanks !!

**Comment by DanielYKPan** [comment]
You need to set [(ngModel)]

**Comment by AmineBena17** [comment]
i already set it by i still have the same problem

**Comment by DanielYKPan** [comment]
@AmineBena17 
Then you may use a angular-cli to create a sample app to demonstrate the issue and publish to your git. In this case, I could download the git and see the problem

**Comment by DanielYKPan** [comment]
@AmineBena17 
Are u sure you used it like this way? you have to bind a variable to [(ngModel)], otherwise you would get an error like you described before.
`
<owl-date-time [(ngModel)]="moment" ></owl-date-time>
`

**Comment by AmineBena17** [comment]
@DanielYKPan  yes i used it in this way and i still have the same problem

**Comment by DanielYKPan** [comment]
Could you share you code?

**Comment by BlankHrt** [comment]
same issue
this is my code 
        ```javascript
<owl-date-time name="date" [(ngModel)]="date" [showHeader]="true" [inline]="true" [inputId]="'input10'"></owl-date-time>```

error:
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value...

**Comment by DanielYKPan** [comment]
What angular version are u using? What environment r u in?

**Comment by BlankHrt** [comment]
angular :4.4.1
  production: true

**Comment by DanielYKPan** [comment]
@BlankHrt 
Could you build a simple angular-cli project to demonstrate the issue and publish to you git. In this case, I could download the project and figure out what is going on

**Comment by BlankHrt** [comment]
ok,wait a minute

**Comment by BlankHrt** [comment]
@DanielYKPan this is my repo 
https://github.com/BlankHrt/activity.git

**Comment by DanielYKPan** [comment]
where do use the component?

**Comment by BlankHrt** [comment]
src/app/hot/hot-add.component.html

**Comment by DanielYKPan** [comment]
@BlankHrt 
No way i could debug it from you original git.

Could you just create a simple new angular-cli, and only use the picker component to demonstrate the issue

**Comment by DanielYKPan** [comment]
@BlankHrt 
I tried my best. 
Try the 5.0.0 beta 6 version to see if the issue solved.
I would close this issue at this moment.

**Comment by BlankHrt** [comment]
@DanielYKPan 
I  created a new repo , it's Ok 
https://github.com/BlankHrt/date-picker

i don't know why it's not working with

**Comment by BlankHrt** [comment]
i update to 5.0.0-beta.6.
well done!
thank you!

**Comment by AmineBena17** [comment]
it works now ! 

thank you
