### ISSUE TITLE
Fontello icon font doesnt appear under assets

### ISSUE THREAD

**Issue by fvisaggio** [DanielYKPan/date-time-picker#151]
I cannot get the icon fonts to work for me, and I believe this is because I cannot serve them under my assets folder. In your exampe https://danielykpan.github.io/date-time-picker/ I noticed the Fontello icon font is served under dist/assets/font.

Here is what I tried to do to serve them. 

1.add a fonts/date-time-picker folder under my assets folder (I am using a new angular 4 cli project) and I put the fontello.woff and the older fontello types there (.svg .eot etc).

2. Modify my .angular-cli.json to serve these icon fonts 
`"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",

      "styles": [
        "../node_modules/ng-pick-datetime/assets/font/fontello.eot",
        "../node_modules/ng-pick-datetime/assets/font/fontello.svg",
        "../node_modules/ng-pick-datetime/assets/font/fontello.ttf",
        "../node_modules/ng-pick-datetime/assets/font/fontello.woff",
        "../node_modules/ng-pick-datetime/assets/font/fontello.woff2",
        "../node_modules/ng-pick-datetime/assets/style/picker.min.css",
`
Any idea what I am missing? 
It picks up the picker.min.css file but I dont get the additional folders I added under assets. I also tried adding "assets/fonts/date-time-picker" to the assets array because thats the folder I created to add the fontello font there. 

By the way, this library is awesome thank you for sharing it Daniel.

**Comment by DanielYKPan** [comment]
picker.min.css imports the fonts file under a url like this '../font/fontello.eot.***', so you folder structure would have to be like this
