### ISSUE TITLE
dateFormat not a property. Unable to start the app

### ISSUE THREAD

**Issue by anthonysubramani** [DanielYKPan/date-time-picker#154]
Uncaught Error: Template parse errors:
Can't bind to 'dateFormat' since it isn't a known property of 'owl-date-time'.

**Comment by DanielYKPan** [comment]
@anthonysubramani 
What version of the picker are you using?

**Comment by anthonysubramani** [comment]
Working fine with latest version

**Comment by webhav** [comment]
@DanielYKPan 

Getting same error on using dateFormat property in owl-date-time 
I am using angular 5 with picker version 5.
