### ISSUE TITLE
type date string on input

### ISSUE THREAD

**Issue by viethoanganh79** [DanielYKPan/date-time-picker#155]
i see this is great plug-in
but i want type a date string on the input cause sometime i just fill it by hand

**Comment by toonkii** [comment]
I also have the same requirement. I need to be able to type in the date and time into the input field sometimes. Is this at all possible? Thanks for a very good component.

**Comment by DanielYKPan** [comment]
@viethoanganh79 
@toonkii 
Update the picker to version 5.0.0-beta.7

Now, there is [readonlyInput] property which could set the text input to NOT readonly and you could type your date time string in it.
You could read more about this from README

**Comment by cfsilence** [comment]
> Now, there is [readonlyInput] property which could set the text input to NOT readonly and you could type your date time string in it.

I'm on 5.0.0-beta.11 and setting readonlyInput="false" has no effect.  The input is still readonly.

**Comment by cfsilence** [comment]
As an update, if I bind `readonlyInput` to a boolean in the component it works, but passing the string `false` has no effect.
