### ISSUE TITLE
AOT Cannot find module ng-pick-datetime/picker.component.ngfactory

### ISSUE THREAD

**Issue by GeorgeKnap** [DanielYKPan/date-time-picker#156]
this is the AOT error. happends on all versions of this picker. It must be something with the CLI or Angular.
```
ERROR in C:/Development/Intens.Osks.Gis/Intens.Osks.Gis.Website/$$_gendir/src/app/gis/esri-menu/gps-history/gps-timeline/gps-timeline.component.ngfactory.ts (19,22): Cannot find module '../../../../../../../$$_gendir/node_modules/ng-pick-datetime/picker.component.ngfactory'.
```

```
ng-pick-datetime: 5.0.0-beta.7
@angular/cli: 1.4.4
@angular 5.0.0.-rc.0
```

**Comment by DanielYKPan** [comment]
@GeorgeKnap 
Maybe try angular 4.*

**Comment by DanielYKPan** [comment]
@GeorgeKnap 
I just tested it in a brand new angular cli project, and run `ng build --aot`. It works fine

**Comment by GeorgeKnap** [comment]
Yes, downgrading `@angular` to version `4.4.4` worked. Any change to get it working for `5.x` in the near future?

**Comment by DanielYKPan** [comment]
@GeorgeKnap 
Definitely, but not until angular 5 is stable
