### ISSUE TITLE
Overlay DatePicker mode missing

### ISSUE THREAD

**Issue by avinashthakur2015** [DanielYKPan/date-time-picker#158]
full body overlay datepicker like material design missing

**Comment by jacobbutton** [comment]
Are there any current plans to implement this?

**Comment by DanielYKPan** [comment]
@jacobbutton 
Yes, I am woking on it

**Comment by DanielYKPan** [comment]
Try the new version 5.1.0 

PS: The picker in 5.1.0 is completely changed,  please follow the doc or demo examples to implement the picker into your projects.
