### ISSUE TITLE
Option to style template

### ISSUE THREAD

**Issue by sskhokhar** [DanielYKPan/date-time-picker#161]
There must be an option to style the template. Like implementation of Material template and Material icons. I tried searching for template but couldn't find as npm install compiles the project.

**Comment by DanielYKPan** [comment]
I don't fully understand what you mean. I got property [style] to let user provide inline style to the whole component and [styleClass] to provide styleClass. You could learn more about these two from README

**Comment by sskhokhar** [comment]
I know but the problem is you're using fonts awesome in your your project I guess. What if I want to use Material Icons with Material Input Design? Like floating placeholder etc.

**Comment by DanielYKPan** [comment]
Oh,
I see what you mean. I will look at it.
Thanks.

**Comment by doginthenight** [comment]
How does commit https://github.com/DanielYKPan/date-time-picker/commit/b95bd1c41e13f0cf8f2dfb1c01e7e0264241ee52 fix this issue? 
Could you give an example of using the picker in conjunction with Material features such as placeholder?

**Comment by DanielYKPan** [comment]
@doginthenight 
Sorry, I typed the wrong issue number.

I still working on this...

**Comment by DanielYKPan** [comment]
Try the latest version, it should be added
