### ISSUE TITLE
No aincrement/Decrement buttons on time picker

### ISSUE THREAD

**Issue by Shogun666** [DanielYKPan/date-time-picker#163]
Hi,

Times increment/decrement buttons don't show, do I need to use some additional icon pack?
![image](https://user-images.githubusercontent.com/6062271/31500419-a2f1f598-af67-11e7-88ba-1f7deff547ac.png)

**Comment by DanielYKPan** [comment]
This is because you didn't load the font resource from the package. Copy the font folder from the package and parse it into the location where you app loads your assets.

**Comment by Shogun666** [comment]
Fonts are loaded, but still not visible
![image](https://user-images.githubusercontent.com/6062271/31534578-d2f70d6a-aff7-11e7-87f2-3a5bbf7416ef.png)
Maybe I'm doing sth wrong, but I did'n found font import in picker.min.css file.

**Comment by DanielYKPan** [comment]
@Shogun666 
Yes, I made a silly mistake. Forgot to add the font style.
Update to the version 5.0.0-beta.10 should be all right

Thanks.
