### ISSUE TITLE
Set output date format

### ISSUE THREAD

**Issue by craftpip** [DanielYKPan/date-time-picker#164]
In the current version after a date is selected, the UTC string is saved,
ex. Fri, 13 Oct 2017 07:10:01 GMT
How do i change it to save the ISO string, 
ex. 2017-10-13T07:10:01.508Z

This will be great help, Thanks!

**Comment by DanielYKPan** [comment]
@craftpip 
I will look at it,
Thanks.

**Comment by DanielYKPan** [comment]
@craftpip 
I don't understand what you mean by Saving the ISO string.
Do you want the ISO string show on the input or you want to get the iso string from callback function?

**Comment by saketk21** [comment]
Hi @DanielYKPan It is 2021 and I dont see the [dateFormat] attribute anymore. How do I show the ISO String in the input text field now? More precisely, my issue is described as follows :-

- User will input the date-time from the date-time-picker, it should show up as an ISO string in the input text field (Tried using OWL_DATE_TIME_FORMAT injection token, but could not find a way in the docs to make it appear as ISO string in input text field)
- User will edit the ISO string and open the date-time-picker, it should show the updated value in the picker (I think this works even now)
