### ISSUE TITLE
Hour and Minute Arrows Not Visible

### ISSUE THREAD

**Issue by jlenthe2** [DanielYKPan/date-time-picker#165]
The hour and minute up/down arrows are not visible for me (using version 5.0.0-beta.9).

This appears to be because `node_modules/ng-pick-datetime/assets/style/picker.min.css` doesn't have the `icon-up-open:before` and `icon-down-open:before` styles that I see on the demo site.

I was able to work around this by making my own copy of picker.min.css and adding the additional styles at the top and adding the font assets.

**Comment by DanielYKPan** [comment]
@jlenthe2 
Yes, I made a silly mistake. Forgot to add the font style. 
Update to the version 5.0.0-beta.10 should be all right

Thanks.
