### ISSUE TITLE
How can I connect two date pickers?

### ISSUE THREAD

**Issue by klickagent** [DanielYKPan/date-time-picker#167]
Thanks for the great date and time picker. I do really like it. Right now I want to set the min attribute on the second date picker as soon as the first date got selected. Is this possible and if so, how can I do this? Thanks for your help.

**Comment by klickagent** [comment]
Ah, I just found it out by myself. I did use the breakets {{ in the first place. But it is working by only adding [min]="dateFrom".

**Comment by DanielYKPan** [comment]
don't understand what you is
