### ISSUE TITLE
Datetime picker is broken in firefox when selecting time

### ISSUE THREAD

**Issue by BlindDespair** [DanielYKPan/date-time-picker#170]
I don't know about latest firefox, but in Firefox 52 and lower it is throwing an error `ReferenceError: event is not defined`. And then in the view input date is not updated, however if you open datetime picker again the correct value will be in the time inputs. But the model value has date with two hours less. So if you selected 27 Jun 2017 and 9:00, date object from ngModel will have 7:00. You can easily reproduce this issue even in your demo, if you open it in firefox 52.0. Thank you!

**Comment by DanielYKPan** [comment]
@BlindDespair 
Update to version 5.0.0-beta.11, it should be fixed.

**Comment by BlindDespair** [comment]
Yes. It works after update. Big thanks!
