### ISSUE TITLE
Timezone issue on Firefox

### ISSUE THREAD

**Issue by pchmn** [DanielYKPan/date-time-picker#171]
Hello,

When I'm using the date picker on Firefox I have an issue. If I select the date 2017-10-19 on the picker, the returned value is 2017-10-18 22:00 on Firefox, and is 2017-10-19 00:00 on Chrome. 

With the datetime picker there is also an issue. If I select 2017-10-18 19:00, the returned value is 2017-10-18 17:00 on firefox and 2017-10-18 19:00 on Chrome.

So there is a difference of 2h (I'm in France) on Firefox, maybe because of the timezone ?

Thanks

**Comment by DanielYKPan** [comment]
I guess it not because the time-zone. Do not use the angular 4 date pipe and console log the return pure Javascript date object to see if the return value is correct.

**Comment by pchmn** [comment]
Yeah, I wasn't using the angular 4 pipe, I "consoled" log the pure javascript object to see that there is the 2h difference.

**Comment by pchmn** [comment]
Here some photos : 
In Firefox : 
![image](https://user-images.githubusercontent.com/12658241/31770576-e645bc46-b4d8-11e7-8b5e-efa21f59708a.png)

In Chrome : 
![image](https://user-images.githubusercontent.com/12658241/31770619-157b5b88-b4d9-11e7-8a23-ad49eec71f92.png)

**Comment by johankvint** [comment]
I have this issue on Chrome as well.
Only using "calendar" and when I select a date the date-string contains time which is set to 22:00:00. I live in Sweden so same timezone as @pchmn

**Comment by DanielYKPan** [comment]
@johankvint 
If you only use 'calendar', you need to set that [dateFormat] attribute to only display the date value
for example: [dateFormate]=" 'YYYY/MM/DD ' "

**Comment by johankvint** [comment]
Hi again,
Yes I'm using "calendar and have set dateFormat to "YYYY-MM-DD".
This is what I get with json-pipe:

![screen shot 2017-11-22 at 10 18 32](https://user-images.githubusercontent.com/6551731/33119231-969e0f9e-cf6e-11e7-9d96-f23232671603.png)

"From" sets the start value and "To" sets the end value

HTML
```Html
<div class="form-group col-4">
            <label>From:</label>
            <owl-date-time type="calendar"
                class="form-control"
                placeholder="yyyy-mm-dd"
                #startDate
                formControlName="start" 
                [max]="endDate.value"
                dateFormat="YYYY-MM-DD">
            </owl-date-time>
        </div>
        <div class="form-group col-4">
            <label>To:</label>
            <owl-date-time type="calendar"
                class="form-control"
                placeholder="yyyy-mm-dd"
                #endDate
                formControlName="end" 
                [min]="startDate.value"
                dateFormat="YYYY-MM-DD">
            </owl-date-time>
        </div>
```
