### ISSUE TITLE
Entering manually date with the keyboard and dateFormat

### ISSUE THREAD

**Issue by pchmn** [DanielYKPan/date-time-picker#172]
Hello again,

I have an issue when I want to let the user enter a date manually. I specified a dateFormat as follow: "DD/MM/YYYY". 
If I want to enter the date 19/10/2017, I start typing 19 but the picker will search for the year 1900 and will block after the first "/". 
So if I want to set the date to 19/10/2017 manually I have to type 2017/10/19 in the "YYYY/MM/DD" format even if I set the dateFormat to "DD/MM/YYYY".

**Comment by DanielYKPan** [comment]
This is duplicate to issue #169
