### ISSUE TITLE
dateTimeDialog pop out of overflow hidden

### ISSUE THREAD

**Issue by jacobbutton** [DanielYKPan/date-time-picker#174]
Is there a good way to get the dateTimeDialog to pop out of a parent element that have overflow:hidden?

I'm trying to to place the the picker in a modal form and it's being clipped inside the modal.

This is the particular component I'm working with.

https://vmware.github.io/clarity/documentation/modals

I've constructed a crude work around, and it's rather ugly and clunky, but it accomplishes the basic idea. We basically need to set the position of the dialog to fixed and use javascript to position and reposition (if the browser window is resized) the dialog to underneath the input.

`<owl-date-time name="due" [(ngModel)]="activity.due" *ngIf="activity" (onFocus)="dateTimeFocus($event)" (window:resize)="onResize($event)"></owl-date-time>`

`	DTP: any = {}

	dateTimeFocus(event) {
		//get target dateTimeDialog
		this.DTP.target = event.path[2].children[2];
		//get parent input
		this.DTP.parent = event.path[2];
		//resest values from previous move so it doesn't jump around screen during the timeout
		this.DTP.target.style.top = "36px";
		this.DTP.target.style.left = "0px";
		this.DTP.target.style.position = "absolute";
		//move the dialog
		this.moveDTP();
	}

	onResize() {
		//move dialog on browser resize
		this.moveDTP();
	}

	moveDTP() {
		var dtp = this.DTP;
		//We shouldn't move it if it hasn't been openeed yet
		if (this.isNotNullOrUndefined(dtp.target)) {
			setTimeout(() => {
				//needs to be delayed because initial values are zero until component updates
				var currentOffset = dtp.parent.getBoundingClientRect();
				//set postions to just below the input
				dtp.target.style.top = currentOffset.top + currentOffset.height + "px";
				dtp.target.style.left = currentOffset.left + "px";
				// set position to fixed to pop outside of overflow:hidden
				dtp.target.style.position = "fixed";
			}, 150);
		}
	}

	isNotNullOrUndefined(obj: any) {
		return !(typeof obj === "undefined" || obj === null);
	}`

It would be nice if this functionality worked inherently.

**Comment by DanielYKPan** [comment]
Duplicate to issue #158
