### ISSUE TITLE
Remove clear button

### ISSUE THREAD

**Issue by dland512** [DanielYKPan/date-time-picker#177]
I'm seeing a small black X on the right hand side of the input box:

<img width="274" alt="screen shot 2017-10-26 at 12 10 13 am" src="https://user-images.githubusercontent.com/1686534/32035979-6ce244aa-b9e2-11e7-86f1-9ebb7271b384.png">

Clicking it clears the date out. I don't see it in any of the examples and I can't seem to git rid of it (other than to use CSS to remove it). Am I doing something wrong here? Is there a config setting I'm missing that lets you hide it?

**Comment by guidosreis** [comment]
What browser are you using? it seems to be IE or Edge.
If i'm right, this is a Microsoft browser input behavior.
To remove it, you should style this pseudo-class:
`.someinput::-ms-clear {
    display: none;
}`

See this stackoverflow question:
https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

**Comment by dland512** [comment]
I'm using the latest Chrome (61.0.3163.100) and Firefox (56.0.2) on
macOS 10.12.6.

**Comment by DanielYKPan** [comment]
I added a option [hideClearButton].

Update to latest version, it should be fixed

**Comment by johaven** [comment]
Since last version the button is not showed even if [hideClearButton]="false"
