### ISSUE TITLE
scripts.bundle.js:210  Uncaught TypeError: Cannot read property 'Pipe' of undefined   

### ISSUE THREAD

**Issue by sagarloona4180** [DanielYKPan/date-time-picker#178]
scripts.bundle.js:210 Uncaught TypeError: Cannot read property 'Pipe' of undefined
    at scripts.bundle.js:210
    at scripts.bundle.js:210
    at scripts.bundle.js:210

**Comment by DanielYKPan** [comment]
This is not a good way to contribute to this repo, as this message or title could not help to identify the issue. You may try to build a Plunker or a repo to demonstrate the issue you described.

I would close this issue for now.

**Comment by sagarloona4180** [comment]
i got pipe is undefined in console .please help on it

**Comment by DanielYKPan** [comment]
I could not help as the way you described on the issue was too broad.
You may try to follow the demo or the description in README to see what caused the error
