### ISSUE TITLE
Input date string not working

### ISSUE THREAD

**Issue by viethoanganh79** [DanielYKPan/date-time-picker#179]
i set properties [dateFormat]="DD/MM/YYYY", [readonlyInput]="false" and input working 
but when i type 29/8/2017 - format dd/mm/yyyy it's working wrong
however, when i type 8/29/2017 and it's working right
![image](https://user-images.githubusercontent.com/15764130/32151339-bf267096-bd4e-11e7-9191-76949238d7db.png)

**Comment by DanielYKPan** [comment]
DD/MM/YYYY might mean 29/08/2017

**Comment by viethoanganh79** [comment]
yep, it's true, it's Day/Month/Year
and now i want input day/month/year in the plug-in

**Comment by DanielYKPan** [comment]
DD/M/YYYY

**Comment by viethoanganh79** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15764130/32159605-c042b66a-bd80-11e7-8fe5-f9edf64b5884.gif)
when it's right
i leave input field that show 29/08/1994 => it's right

**Comment by DanielYKPan** [comment]
This is duplicate to this [issue](https://github.com/DanielYKPan/date-time-picker/issues/169#issuecomment-337866506)

It will be fixed once the date-fns version 2 is stable
