### ISSUE TITLE
Min/max date problem

### ISSUE THREAD

**Issue by adrianadr** [DanielYKPan/date-time-picker#180]
Hey, i;ve tried using mix/max for date select but i cant figure out the syntax that is used in input is [max]="" or [min]=""?

**Comment by DanielYKPan** [comment]
[min]="YOUR_MIN_DATE_OBJECT"

[max]="YOUR_MAX_DATE_OBJECT"

**Comment by padmapriya18** [comment]
Hi, I'm currently facing this issue.
![image](https://user-images.githubusercontent.com/51708783/59276216-8282ff80-8c7b-11e9-9ff6-015d6defa4d4.png)
Version -> "ng-pick-datetime": "^7.0.0",
