### ISSUE TITLE
Minute and second not in the right position in IE 11

### ISSUE THREAD

**Issue by zizinic** [DanielYKPan/date-time-picker#182]
When use IE 11 and use date time picker as a drop down, the initial position of min and sec is not in the center.  It can back to normal if edit them.  Please see attached picture .

![image](https://user-images.githubusercontent.com/29929112/32341992-825d92f0-bfd5-11e7-9135-57b1db4338c3.png)

**Comment by DanielYKPan** [comment]
Update to latest version, it should be fixed
