### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by MarioLongJACK** [DanielYKPan/date-time-picker#185]
Hi, I added the link to the css file to my index.html and it doesn't work at all. Not sure what is going on.

**Comment by DanielYKPan** [comment]
@MarioLongJACK 
I could not answer this question, as it is quite board and it may be caused by many things such as you development environment or your project configuration.

**Comment by HimanshuSojitra** [comment]
@JikaiLong I fixed it by updating the **.angular-cli.json** file

```
...
"styles": [        
    "../node_modules/ng-pick-datetime/assets/style/picker.min.css",
    "styles.css"
 ],
...
```
