### ISSUE TITLE
Default moment time has been reset when interacts with any date.

### ISSUE THREAD

**Issue by allanclempe** [DanielYKPan/date-time-picker#186]
[x] Bug

The default moment time should be preserved when clicks on any date.

Steps to reproduce:

- copy the html bellow.
``` html
<owl-date-time type="both" dateFormat="DD/MM/YYYY" placeHolder="DD/MM/YYYY" autoClose="false" defaultMoment="2017-05-05 10:00:00+10:00" ></owl-date-time>
```
- Click on any date, you would see the time going back to 00:00

Thanks

**Comment by DanielYKPan** [comment]
@allanclempe 
Some people requested to set the time back to 00:00, but some requested not (#135).

I may consider to set an option to on/off the feature

**Comment by allanclempe** [comment]
@DanielYKPan  The problem is the timezone. 
example: 
the UTC date for  2017-01-01 10:00:00+10:00, will be 2017-01-01 00:00:00+00:00. 
now, resetting the time and preserving the timezone, the 00 hours of the same date will be 2016-12-31 14:00:00+00:00 UTC.

**Comment by DanielYKPan** [comment]
The property **[defaultMoment]** is designed for a situation when there is no date/time chose, that defaultMoment would appear on the picker. When you choose a date/time, it would return that date/time    object in your local timezone. If you want to have a different timezone value, you could use (ngModelChange) to get the date/time value, adjust to your prefer timezone value and update your ngModel by your own
