### ISSUE TITLE
No Event method invoking when click on Confirm button

### ISSUE THREAD

**Issue by Jijoac** [DanielYKPan/date-time-picker#187]
Which event method will invoke when click on Confirm button

**Comment by DanielYKPan** [comment]
When you click the confirm button, it means you choose a date or time and your ngModel value would be changed. If you really want to get an event from confirm, you could use (ngModelChange). But beware, it would not fire if you ngModel value is not changed

**Comment by DanielYKPan** [comment]
Update to latest version, it should be fixed
