### ISSUE TITLE
Time is not updating

### ISSUE THREAD

**Issue by Jijoac** [DanielYKPan/date-time-picker#188]
When we update time, it throws exception

ReferenceError: event is not defined
Stack trace:
../../../../ng-pick-datetime/picker.component.js/DateTimePickerComponent.prototype.setSelectedTime@http://localhost:4200/vendor.bundle.js:10653:34
../../../../ng-pick-datetime/picker.component.js/DateTimePickerComponent.prototype.setHours@http://localhost:4200/vendor.bundle.js:10141:20
../../../../ng-pick-datetime/picker.component.js/DateTimePickerComponent.prototype.onTimerInputBlur@http://localhost:4200/vendor.bundle.js:10332:32
View_DateTimePickerComponent_13/<@ng:///DateTimePickerModule/DateTimePickerComponent.ngfactory.js:472:27
handleEvent@http://localhost:4200/vendor.bundle.js:76174:98
callWithDebugContext@http://localhost:4200/vendor.bundle.js:77638:39
debugHandleEvent@http://localhost:4200/vendor.bundle.js:77226:12
dispatchEvent@http://localhost:4200/vendor.bundle.js:72767:12
renderEventHandlerClosure/<@http://localhost:4200/vendor.bundle.js:73378:20
decoratePreventDefault/<@http://localhost:4200/vendor.bundle.js:88046:53
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:10959:17
onInvokeTask@http://localhost:4200/vendor.bundle.js:68033:24
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:10958:17
../../../../zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:10726:28
../../../../zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:4200/polyfills.bundle.js:11033:24
invokeTask@http://localhost:4200/polyfills.bundle.js:12074:9
globalZoneAwareCallback@http://localhost:4200/polyfills.bundle.js:12100:17

**Comment by DanielYKPan** [comment]
@Jijoac 
Impossible to debug this from what you provided. You may try to reproduce your issue from a Plunker or a angula-cli project and share it to me.

I would close this issue for now.
