### ISSUE TITLE
[mode] ="inline" make other input type file dialog dosn`t work !

### ISSUE THREAD

**Issue by OdaiTu** [DanielYKPan/date-time-picker#19]
hi there 
im using date-time-picker and its very good but im face a problem with mode inline
i have in my form other input type file and when i set the mode to inline in date-time-picker
the dialog dosnt show up

i need a solution plz

**Comment by DanielYKPan** [comment]
@OdaiTu 
Thanks, OdaiTu.

What angular version are you running? Are you running at Webpack or SystemJS?

**Comment by OdaiTu** [comment]
@DanielYKPan 

im using angular-cli with angular version 2.3.1

**Comment by DanielYKPan** [comment]
@OdaiTu 
Did the console show any error message?

**Comment by OdaiTu** [comment]
@DanielYKPan 

no bro 

![image](https://cloud.githubusercontent.com/assets/12837840/24643148/b06352ba-1914-11e7-9332-5e75f694ad9b.png)


when click on browse to choose a file
the popup dialoag dosnt show
but when set the mode to popup in datepicker every thing goes good
in think the inline mode do some thing to all other inputs with type file !

**Comment by DanielYKPan** [comment]
What version of date-time-picker you are using?

Try use the version 4.0.2

npm install ng-pick-datetime --save

**Comment by OdaiTu** [comment]
i installed it yesterday  and the version is 4.0.1

**Comment by DanielYKPan** [comment]
Try use the version 4.0.2

**Comment by OdaiTu** [comment]
i installed it and this error comes up in console !

![image](https://cloud.githubusercontent.com/assets/12837840/24643699/4bc056f6-1918-11e7-858f-08559fd7ab5d.png)

**Comment by DanielYKPan** [comment]
@OdaiTu 
I used it in a fresh new angular-cli package, and it works well.

**Comment by OdaiTu** [comment]
how to delete it and reinstall it again ?

**Comment by OdaiTu** [comment]
thannnnnnks it works fine now !
what you did

**Comment by OdaiTu** [comment]
@DanielYKPan 
i have another issue 
i must click on confitm button  to save the date in my model ?
cant be by default confirmed ?
