### ISSUE TITLE
Dialog is misplaced

### ISSUE THREAD

**Issue by azzimuth** [DanielYKPan/date-time-picker#190]
I tried the example in README but when I click on the input I cant see the dialog. When I inspect the DOM in the DevTools I can see that the dialog exists but it is positioned strangely:
```visibility: visible;
top: -268px;
left: 0px;
opacity: 1;
display: block;
```
My HTML code is following
```
<owl-date-time name="EventDateTime" [(ngModel)]="manualEvent.eventDateTime" [min]="assessment.startDate" 
[max]="maxDate" [dateFormat]="dateTimeFormat" [showHeader]="true" [inputId]="'Input_EventDateTime'" [dataType]="'string'"></owl-date-time>
```

**Comment by JohnValadakis** [comment]
Verify your import to stylesheet
`../node_modules/ng-pick-datetime/assets/style/picker.min.css`
at your index.html  || add a style ref to your cli.json according to your implementaion.

I had also the  dialog miss-placed and dialog date and day buttons on the right side of the calendar modal was out of the view size of the component.
I added and overwrite css on my app.component 
`styles: ['
        .owl-dateTime-dialog {
            width: auto  !important;    
        }
    ']
`
it was on `300px;` if you inspect it and increase  it you will find out that it  had to be around `330px`  when i set the overwrite everything worked fine. 
Also there is a reference on the documentation that you have to include 
`@angular/platform-browser/animations` so include BrowserAnimationsModule to your module also.

Hope i helped.

**Comment by tmmidia** [comment]
I use hack 
```
.cdk-overlay-container {
  position: fixed;
  z-index: 1090;
}
```
Works !!
