### ISSUE TITLE
How to reset pickerMoment in date picker

### ISSUE THREAD

**Issue by TomasAndersen** [DanielYKPan/date-time-picker#195]
I am able to use the defaultMoment setting to set which year/month to be default when opening the date picker. I am not using this so the current year/month is set when I open the picker for the first time. I see in the code that the pickerMoment is set to this.now.

If the user navigates to ie august 2016 and chooses a date, I have noticed that the next time the picker is opened it starts with august 2016 again. I would like the current year/month to be the default after I am clearing out all my input fields.

Is there a way to set the internal pickerMoment value programatically?

**Comment by asfo** [comment]
I'm using an old version of this plugin and I can't update it, so I hope there is a way to do this programatically, I tried with the old way:

public setMoment(moment: any): any {
    this.momentValue = moment;
}

So I tough the calendar should be reset, but didn't work, so if there is a workaround or a way to fix this hope someone can help with it.
