### ISSUE TITLE
Setting active datetime without ngModel not possible?

### ISSUE THREAD

**Issue by trsh** [DanielYKPan/date-time-picker#198]
When I set `[defaultMoment]="someDate"`, it does show the appropriate month and time, but the date is not marked as active one.

If this is expected behavior of `defaultMoment `, can we have another option to set the active date manually? ngModel is not an option in my case, as I use very custom implementation. Maybe some `[activeDate]` or inputEvent `[setActiveDate]`?

**Comment by DanielYKPan** [comment]
`[defaultMoment]` is not used to marked as active.

**Comment by trsh** [comment]
@DanielYKPan what is? Any suggestions? You Kind of read only first sentence :)

**Comment by DanielYKPan** [comment]
I don't see why you could not use [ngModel] if you want to use [activeDate] to set the selected date

**Comment by trsh** [comment]
OK, explain my user case:

`    <ng-container *ngSwitchCase="controlTypes.DatetimeInput">
        <owl-date-time [dateFormat]="control.format" (onConfirm)="control.uodateCalendar($event, form.controls[control.key])" [defaultMoment]="control.dateValue" [showButtons]="true" [dataType]="'string'">
            <mat-form-field>
                <input [errorStateMatcher]="dirtyAndInvalidErrorStateMatcher" [required]="control.required" matInput [placeholder]="control.label" [formControlName]="control.key" [id]="control.key">
            </mat-form-field>
        </owl-date-time>
    </ng-container>`

You see, I can't use ngModel in reactive form, it's forbidden by angular. And formControlName I want to sen on the input, that triggers calendar. So there is no way.

**Comment by DanielYKPan** [comment]
This picker supports reactive form.

**Comment by trsh** [comment]
@DanielYKPan I give up. You didn't even check the code. Good luck!

**Comment by DanielYKPan** [comment]
@trsh 
Come on man, you can't just throw a question, and expect someone to give a perfect answer. You just put down couples of meaningless code lines and not even try to reproduce the problem with readable and runnable  codes (Plunker or Git project). For what i can tell from you lines, you used angular materials. Angular Material has their own calendar, you could use it if you want.

PS: Github is a open source library and not a Google-Search-And-Give-Me-Perfect-Answer engine.

**Comment by trsh** [comment]
@DanielYKPan angular material has no timepicker. If it would I'll be sure using it. I got around my problems with few hacks.
