### ISSUE TITLE
Unable to submit

### ISSUE THREAD

**Issue by marty912** [DanielYKPan/date-time-picker#20]
Hello, 

Since the new version, I can't submit my form anymore. 

Here's a minimalist try :

In my component :
```
private variable: string;
submit() {
    submit'+this.variable);
}
```

In my component's template :
```
<form submit)="submit()">
   <input name="variable" [ngModel]="variable | date: 'short'" [(dateTimePicker)]="variable" readonly/>
   <button>Save</button>
</form>
```

Do you have an idea to resolve this problem ?

N.B. : 
* Version : ^4.0.1
* Import : by the SharedModule
* it's possible to submit the form before using the date-time-picker (just open it)

Marty

**Comment by DanielYKPan** [comment]
@marty912 
Yes, it was a bug.
I already fixed it.
Try Version : 4.0.2
