### ISSUE TITLE
External Trigger

### ISSUE THREAD

**Issue by kherP** [DanielYKPan/date-time-picker#206]
I wanted to trigger the date-time-picker externally with a button;

![image](https://user-images.githubusercontent.com/12553063/33640310-be55755c-da6a-11e7-97de-554c38a24e93.png)

with following code:

`<owl-date-time #dtPicker [(ngModel)]="data.scheduleon" name="scheduleon"></owl-date-time>
				<button (click)="dtPicker .click()" type="button">
					<mat-icon>date_range</mat-icon>
				</button>`

and I also tried calling the element in component:

\\html
`<div class="calendar-wrapper" #dtPicker>
				<owl-date-time [(ngModel)]="data.scheduleon" name="scheduleon"></owl-date-time>
				<button (click)="triggerCalendar()" type="button">
					<mat-icon>date_range</mat-icon>
				</button>
			</div>`

//component
`  @ViewChild("dtPicker") dtPicker: ElementRef;
  triggerCalendar(){
    let input = this.dtPicker.nativeElement.querySelector('owl-date-time');
    console.log(input);
    input.click();
  }`

But the element seems to not trigger. Is there a proper way to do that?

**Comment by DanielYKPan** [comment]
Yeah, I am working on this right now

**Comment by DanielYKPan** [comment]
Try the new picker version 5.1.0

PS: The picker in 5.1.0 is completely changed,  please follow the doc or demo examples to implement the picker into your projects.
