### ISSUE TITLE
date and time in model and picker field not the same

### ISSUE THREAD

**Issue by dilotec-2015** [DanielYKPan/date-time-picker#207]
I set with the picker followind date 2017-10-27 01:00  but my model get: 2017-10-26T23:00:00.000Z.
there is a difference of 2 hours (and 1 day).
i think this is about the time zone...
but how can i get in the model exactly the same date and time as set with the picker?

Version: 5.0.0-beta.15

**Comment by dilotec-2015** [comment]
Hi, is there no solusion for this issue? It's very important for my application...

**Comment by berc** [comment]
I solved it by using [dateType]="'string'", with date format YYYY-DD-MM and started working.
