### ISSUE TITLE
Displaying in angular material dialog

### ISSUE THREAD

**Issue by minchopm** [DanielYKPan/date-time-picker#208]
When I put inline date picker inside a template of the angular material dialog, part of the content of the time picker is not loaded, but if I resize the browser it is refreshing the template and I can then interact with the picker.

**Comment by DanielYKPan** [comment]
Try the new picker version 5.1.0. It has a property [pickerMode] and set it to 'dialog', it might what you asked for

PS: The picker in 5.1.0 is completely changed,  please follow the doc or demo examples to implement the picker into your projects.
