### ISSUE TITLE
cant make two way binding with selectedValue

### ISSUE THREAD

**Issue by OdaiTu** [DanielYKPan/date-time-picker#21]
hi there
i have a form in edit mode so i subscribe to data and fill it to my input but the datetime picker just store the current time of my laptop !

**Comment by DanielYKPan** [comment]
@OdaiTu 
Which mode are you using?

**Comment by OdaiTu** [comment]
@DanielYKPan  inline mode

**Comment by DanielYKPan** [comment]
@OdaiTu 
Update to the latest package, it should be all right.

**Comment by OdaiTu** [comment]
@DanielYKPan 
thank you
but now the conform button has gone !!
so i cant submit the form without press on today button

![image](https://cloud.githubusercontent.com/assets/12837840/24826410/32ee6982-1c3e-11e7-8cdf-a2209676fa4d.png)

cant take the date without press on today button ?

**Comment by OdaiTu** [comment]
@DanielYKPan

**Comment by DanielYKPan** [comment]
Why you need to submit you form using the confirm btn inside the picker?
You should have you own submit btn to submit your form.

You just pick the date, the picker would return the date you need.

**Comment by OdaiTu** [comment]
@DanielYKPan  yes yes i know this
i mean the value of the picker dosnt binding to my model else if i click on today button
it should bind to model automatilclly right !

**Comment by DanielYKPan** [comment]
@OdaiTu 
I don't know how you bind your model. But if you follow my examples in my demo page, it should be all right.

**Comment by OdaiTu** [comment]
@DanielYKPan 
<input class="form-control input-rounded" 
                          name="date_to_publish" 
                          [hourTime]=" '12' " 
                          [mode]="'inline'" 
                          [(ngModel)]="news.date_to_publish"
                          [(dateTimePicker)]="news.date_to_publish" 
                          readonly 
                          [returnObject]="'string'" 
                          [viewFormat]= "'YYYY-MM-DD HH:mm'"
                          />

here is my example
if i submit my form without click on today button the value of date_to_publish is null
if click on today button the date_to_publish bind to the model
all my form is good

**Comment by DanielYKPan** [comment]
try not to used the input tag, use div instead

**Comment by OdaiTu** [comment]
@DanielYKPan 

its the same problem :(

**Comment by DanielYKPan** [comment]
<div class="form-control input-rounded"
name="date_to_publish"
[hourTime]=" '12' "
[mode]="'inline'"
[(dateTimePicker)]="news.date_to_publish"
readonly
[returnObject]="'string'"
[viewFormat]= "'YYYY-MM-DD HH:mm'"></div>

**Comment by DanielYKPan** [comment]
`
<div class="form-control input-rounded"
name="date_to_publish"
[hourTime]=" '12' "
[mode]="'inline'"
[dateTimePicker]="something"
(dateTimePickerChange)="setMoment($event)"
readonly
[returnObject]="'string'"
[viewFormat]= "'YYYY-MM-DD HH:mm'"></div>
`

then build setMoment in your component to set you form data

**Comment by DanielYKPan** [comment]
`<div class="form-control input-rounded"
name="date_to_publish"
[hourTime]=" '12' "
[mode]="'inline'"
[dateTimePicker]="news.date_to_publish"
(dateTimePickerChange)="setMoment($event)"
readonly
[returnObject]="'string'"
[viewFormat]= "'YYYY-MM-DD HH:mm'"></div>`

set function setMoment in your component to set your form data.

**Comment by DanielYKPan** [comment]
Try to console log to see if there is any thing return.

**Comment by OdaiTu** [comment]
@DanielYKPan 
well its print to console the date if i click on the picker on any day or on today button but if i didnt click any thing the date_to_publish still null
this mean that the issue in the bind itself !

**Comment by DanielYKPan** [comment]
@OdaiTu 
If the picker return the date you choose, that means the picker works well.

**Comment by OdaiTu** [comment]
@DanielYKPan 
yes but it should return the value without clicking on it right ?

**Comment by OdaiTu** [comment]
@DanielYKPan 
i know im asking much but i really want this to be solved its very important

**Comment by DanielYKPan** [comment]
@OdaiTu 
It is not about you asking too much, it is about you trying to debug your project by yourself. I couldn't help as I am not doing your project. If it is a bug from the picker, you are so welcome to ask any question.

As you said before, the picker prints to console the date if you click on the picker on any day or on today button. That means the picker returns the date object whether you click any day or the day button.

**Comment by OdaiTu** [comment]
@DanielYKPan 
Thank you
 i know that but i think that it should the value without click on it 
i mean without the click event right ?
