### ISSUE TITLE
Steps for timer

### ISSUE THREAD

**Issue by dreamrdeceiver** [DanielYKPan/date-time-picker#214]
This is more like a feature request or rather is there an option where I can specify the steps for the timer?

Like for the minutes I want it to increase by 15 instead of 1?

**Comment by DanielYKPan** [comment]
Please try the new picker version 5.1.0. It has properties [stepHour], [stepMinute], [stepSecond] to set the step value for the timer.

PS: The picker in 5.1.0 is completely changed,  please follow the doc or demo examples to implement the picker into your projects.
