### ISSUE TITLE
Bug: Manual edit and parse doesn't work in non US date format

### ISSUE THREAD

**Issue by baso10** [DanielYKPan/date-time-picker#215]
When I set properties:
```
[readonlyInput]="false" 
[dateFormat]="'DD.MM.YYYY'" 
```
I can't manualy edit in text field as date-fns.parse expect ISO 8601 format

"version": "5.0.0-beta.15"

**Comment by DanielYKPan** [comment]
Try the latest version, it should be fixed

**Comment by MerlinDuChaos** [comment]
Hi, I have the same problem using version 

"ng-pick-datetime": "^5.1.4",

I use 'fr' locale, which displays the date as "25/02/2018 à 11:23", when I change the value to "25/03/2018 à 11:23", the parse does not work and I get a null value.

I tried removing the 

        this._dateTimeAdapter.setLocale('fr');

line, and manual modification of the input text works.
