### ISSUE TITLE
does ng-pick-datetime version 5.0.0-beta.15 work with Angular Reactive forms?

### ISSUE THREAD

**Issue by tomschreck** [DanielYKPan/date-time-picker#217]
Hello.  I've used ng-pick-datetime version 4.3.2 on previous applications.  I'm starting a new application and noticed you've made a lot of changes with version 5.0.0-beta.15.  I've downloaded your latest version and cannot get it to work with Angular reactive forms.  Your documentation only shows 1 implementation with ngmodel:

<owl-date-time [(ngModel)]="moment" ></owl-date-time>

Does your latest version (ng-pick-datetime version 5.0.0-beta.15) work with Angular Reactive forms?

**Comment by DanielYKPan** [comment]
Yes i works with reactive forms
