### ISSUE TITLE
Set value programmatically - 2 way binding

### ISSUE THREAD

**Issue by TirexCanada** [DanielYKPan/date-time-picker#220]
Hi Daniel, Your component is perfect. I only have one question - I need to select the date programmatically, but can not find the way to do this. In previous version there was a property [(dateTimePicker)] but it is not working in the owl-date-time component anymore. Can you, please, let me know if there is a solution for that. What I need is to be able to set selected dates from UI (select and unselect dates). I'll really appreciate your help.

**Comment by ashwinirajput** [comment]
@TirexCanada you can use like this
 `     <owl-date-time [(formControlName)]="datePicker"  name="date" [(ngModel)]="date" [dataType]="'string'" [type]="'calendar'"   [placeHolder]="'DD/MM/YYYY'" [dateFormat]="'DD/MM/YYYY'"  showHeader="true" ></owl-date-time>`

**Comment by TirexCanada** [comment]
Thank you for your response, but this is not what I am looking for. What I need is to be able to set selected dates from typescript. Let's say I have a record with the date value. When open a form for that record I want to see that date selected on datepicker control. Now even I change the model - date - it is not shown as selected date on a control. I am not sure whether this control does allow that at all.

**Comment by DanielYKPan** [comment]
No idea what you tried to do. Maybe provide a plunker

**Comment by TirexCanada** [comment]
Hi Daniel. Thank you so much for response. You datetimepicker component is really great. I just need one feature and may be it is there but I am doing something wrong way. What I want is to set a model to something like date='12/24/2017' in onInit (or in some other function) and see that date being selected in a datepicker <owl-date-time [(ngModl)]="date" [dateFormat]="'MM/DD/YYYY'"></owl-date-time>. In other words, if I change model from typescript I want to see this reflected on the datepicker - the dates from model should be selected. Please, let me know if this possible and how to get this working. Many thanks for your help.

**Comment by TirexCanada** [comment]
Hi Daniel. Thank you so much for response. Your datetimepicker component is really great. 
I just need one feature and may be it is there but I am doing something wrong way. What I want is to set a model to something like date='12/24/2017' in onInit() (or in some other function) and see that date being selected in a datepicker <owl-date-time [(ngModel)]="date" [dateFormat]="'MM/DD/YYYY'">. In other words, if I change model from typescript I want to see this reflected on the datepicker - the dates from model should be selected. Many thanks for your help.
ngOnInit() {

 this.dateValue = "20/01/2018";}
<owl-date-time [(ngModel)]="dateValue" [dataType]="'string'" [type]="'calendar'" [inline]="true" [dateFormat]="'DD/MM/YYYY'" ></owl-date-time>

On the component I want to see the 20/01/2018 as selected date. (like when I click on the date).
I am not sure if this is possible and I am doing something wrong, or may be your component just do not support this feature.
Sorry for bothering you.Again your component is really great.

Regards,Katerina

**Comment by TirexCanada** [comment]
Hi Daniel,Sorry to bother you again.
After further investigation I have found that when I am using component in 'single' selectionMode - I have no issue.
The code below work perfect and when I open a webpage I can see the date selected on a datepicker component:<owl-date-time [(ngModel)]="dateValue" [selectionMode]="single" [dataType]="'string'" [type]="'calendar'" [inline]="true" [dateFormat]="'MM/DD/YYYY'"></owl-date-time>
ngOnInit() {

    this.dateValue  = "01/20/2018";}


When I am using 'multiple' selectionMode - I am not able to setup ngModel properly.<owl-date-time [(ngModel)]="dateValue" [selectionMode]="multiple" [dataType]="'string'" [type]="'calendar'" [inline]="true" [dateFormat]="'MM/DD/YYYY'"></owl-date-time>
ngOnInit() {

    this.dateValue  = "01/20/2018,01/21/2018";}When I open  webpage no dates are selected on a datepicker component, so looks like the dateValue="01/20/2018,01/21/2018" is not valid.




Can you, please, help with how to properly setup the ngModel for the multiple selectionMode.
Many thanks.
Katerina

**Comment by Hiregui92** [comment]
hi [placeHolder]="'DD/MM/YYYY'" [dateFormat]="'DD/MM/YYYY'" not working

**Comment by Hiregui92** [comment]
> hi [placeHolder]="'DD/MM/YYYY'" [dateFormat]="'DD/MM/YYYY'" not working

Solution create childview. Add group item into form. Add custom formar in providers element
