### ISSUE TITLE
Wrong dateFormat written in model

### ISSUE THREAD

**Issue by cupceavictor** [DanielYKPan/date-time-picker#223]
```
<owl-date-time formControlName="date"
                   [type]="'calendar'"
                   [autoClose]="true"
                   [dateFormat]="'DD.MM.YYYY'"
                   [dataType]="'string'"
                   [placeHolder]="''"
                   [hideClearButton]="true">
</owl-date-time>
```

`this.dateForm.addControl('date', new FormControl('09.01.2018'));`

For date '09.01.2018' (9 January) in model is written '01.09.2018' (1 September)

**Comment by DanielYKPan** [comment]
Please use the new picker version 5.1.0

PS: The picker in 5.1.0 is completely changed,  please follow the doc or demo examples to implement the picker into your projects.
