### ISSUE TITLE
The style is different.

### ISSUE THREAD

**Issue by SONASIDANTE** [DanielYKPan/date-time-picker#226]
The component from npm  is different from the demo.

**Comment by DanielYKPan** [comment]
@SONASIDANTE 
Yes, because I am building a new picker. The current demo is for the new picker, but it has not been fully tested. Hopefully it will be finished in the next couple days.

**Comment by filosof86** [comment]
Hi,

It would be great if the new version could support material design style input.

TIA

**Comment by Presiana** [comment]
Is the new datepicker ready to use from npm ?
