### ISSUE TITLE
Setting defaultTime not persisted after clicking timer arrow buttons

### ISSUE THREAD

**Issue by ld-gary** [DanielYKPan/date-time-picker#227]
Hi,

Setting the defaultTime for a 'timer' instance works great, until you use the arrows to set the time... at which point the intervals begin from whatever the current actual time is. Is this intended? Would be great to be able to establish a starting time on opening the picker (fine there) then increase/decrease the hours/minutes from that time rather than jumping to now, which is pretty jarring for the user.

Thanks!

**Comment by DanielYKPan** [comment]
@ld-gary 
Please try the new picker I just published. Use property [startAt] and it maybe is what you asked for.

PS: the new picker is completely changed, please follow the doc or the demo examples to implement the picker into your projects

Thanks,
