### ISSUE TITLE
cant run seem to run it on angular 5

### ISSUE THREAD

**Issue by adam-ali** [DanielYKPan/date-time-picker#228]
this is the message

Can't bind to 'owlDateTimeTrigger' since it isn't a known property of 'input'. ("
            <div class="start-date">

                <input [min]="min" [max]="max" [ERROR ->][owlDateTimeTrigger]="dt8" [owlDateTime]="dt8" />
                <owl-date-time #dt8></owl-date-time"):

**Comment by crico** [comment]
I have the same problem. I'm using the version "ng-pick-datetime": "^5.2.2" with Angular 5. Any idea?
