### ISSUE TITLE
Locale not working

### ISSUE THREAD

**Issue by Amadox** [DanielYKPan/date-time-picker#23]
In most countries the week starts with a monday, not a sunday. 

Sadly there doesn't seem to be a way to account for that. The datepicker always has Sunday as left-most column, no matter which locale.

Edit: Wrong issue. Real issue is: Despite setting locale, the component does not adapt to the chosen locale but still looks like 'en'.

**Comment by DanielYKPan** [comment]
You have to provide the locale to the picker [locale]= " 'YOUR_LOCALE_LETTERS' "

In this package, the first day of the week is decided by the [MomentJS](http://momentjs.com/docs/#/get-set/weekday/) as it has a wider Locale Library.

Thanks for your advice.

**Comment by Amadox** [comment]
Right, I just noticed that I noticed the wrong issue. Despite me setting the locale it remains the default english one at all times, and I have no idea why.

`<input
                                    name="qStart"
                                    type="text"
                                    placeholder="Datum / Zeit von"
                                    [ngModel]="query.q.start | date: 'medium'"
                                    [(dateTimePicker)]="query.q.start"
                                    [mode]=" 'dropdown' "
                                    [locale]=" 'de' "
                                    [hourTime]=" '24' "
                                    [theme]=" 'gray' "
                                    readonly />`

It's the same when I change it to 'fr'.

**Comment by DanielYKPan** [comment]
@Amadox 
What Angular version are you running?
What version the package are you running?
Are you running your app at Webpack or SystemJS?

**Comment by Amadox** [comment]
Angular 4.0.0, 
ng-pick-datetime 4.0.3, 
via SystemJS

**Comment by wiNgeRf0rN1ceE** [comment]
Same story 
Angular 2.4.8
ng-pick-datetime 4.0.3,
via SystemJS
locale  not working

**Comment by DanielYKPan** [comment]
@Amadox 
@wiNgeRf0rN1ceE 
Because SystemJS doesn't load MomentJS Locale,

If you add **Import 'moment/locale/YOUR_LOCALE_LETTER'** in you module, it will work.

**Comment by wiNgeRf0rN1ceE** [comment]
Thanks man(sorry i'm stupid)

**Comment by Amadox** [comment]
well, that.. makes a ton of sense... and actually worked. thank you!

However: The words "Today" and "Close" are still not translated. Any way for you to take care of that, or at least give us a way to translate those ourselves?

**Comment by DanielYKPan** [comment]
Yes, 
Because I only let MomentJS to do the locale magic. Those words are not part of the MomentJS.

In the past couple days, I tried to used ng2-translate to do the translation for those words. But that package crashed the picker once we have two pickers in one page with two different locale. I am still trying to find a way to do that.

**Comment by DanielYKPan** [comment]
@Amadox 
Finally, I got the translate work. But before I update the package, I need to build the locale library.

What locale are you using?
If you can, please help me translate those strings into your language. (the Strings include "Time Picker", "Hours", "Minutes" and "Set Time").

**Comment by Amadox** [comment]
I'm using "de" (German).

Today: "Heute"
Close: "Schließen"
Time Picker: that's a tough one, no literal translation I guess. But something like "Zeit wählen" (pick a time) would work I suppose
Hour: "Stunde"
Minute: "Minute"
Set Time: tough one again. I suppose "Zeit setzen" would work best, though it's a little awkward.

**Comment by DanielYKPan** [comment]
@Amadox 
The package has been updated.
Update the package and try to use the 'de' locale.
