### ISSUE TITLE
^5.1.0-beta-4 -  getting  error Can't resolve 'moment/moment.

### ISSUE THREAD

**Issue by rpeddu** [DanielYKPan/date-time-picker#230]
I am only using the OwlNativeDateTimeModule but getting error Can't resolve 'moment/moment. please advise.

package.json - dependency   "ng-pick-datetime": "^5.1.0-beta-4",

app module - Imported two classes OwlDateTimeModule and OwlNativeDateTimeModule 

component.html - 
<input [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1" placeholder="Date Time">
 <owl-date-time #dt1></owl-date-time>

ERROR:
ERROR in ./node_modules/ng-pick-datetime/date-time/adapter/moment-date-time-adapter.class.js
Module not found: Error: Can't resolve 'moment/moment' in '_poc/angular-starter-master-5/node_modules/ng-pick-datetime/date-time/adapter'
 @ ./node_modules/ng-pick-datetime/date-time/adapter/moment-date-time-adapter.class.js 15:14-38

**Comment by DanielYKPan** [comment]
Yes, I guess I may need to publish the OwlMomentDateTimeModule as a separate module.

**Comment by DanielYKPan** [comment]
Updated to latest, it should be fixed.
