### ISSUE TITLE
Undefined Provider Error when using OwlMomentDateTimeModule

### ISSUE THREAD

**Issue by ld-gary** [DanielYKPan/date-time-picker#232]
Hey there,

I'm getting an undefined provider error when trying to use the Moment Module as per your examples. Everything works fine for a normal set up but I need to format all the dates so Moment is needed, here is my basic import/provide set up, same as yours...
```JavaScript
import { OwlDateTimeModule, OWL_DATE_TIME_FORMATS } from 'ng-pick-datetime';
import { OwlMomentDateTimeModule } from 'ng-pick-datetime-moment';
export const MY_MOMENT_FORMATS = {
    fullPickerInput: 'LLL',
    datePickerInput: 'LL',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
};
@NgModule({
  imports: [
    ...
    OwlDateTimeModule,
    OwlMomentDateTimeModule
  ],
  declarations: [
    ...
  ],
  providers: [
    {provide: OWL_DATE_TIME_FORMATS, useValue: MY_MOMENT_FORMATS}
  ]
})
export class HomeModule {}`
```

The error...

> Encountered undefined provider! Usually this means you have a circular dependencies [sic] (might be caused by using 'barrel' index.ts files.

**Comment by DanielYKPan** [comment]
I tested it with a  new angular cli project, it works fine.

Can you provide your working environment?

**Comment by ld-gary** [comment]
I'm using the Angular Universal Seed project as a base.
[https://github.com/ng-seed/universal](https://github.com/ng-seed/universal)

**Comment by DanielYKPan** [comment]
I tested it in a new ng-seed project, and it works fine.

Close this now.
