### ISSUE TITLE
stepMinute does not increment correctly

### ISSUE THREAD

**Issue by jcachat** [DanielYKPan/date-time-picker#233]
I have version 5.1.0-beta-7.  "stepMinute" appears to be appending a string value to the time instead of adding numeric values when clicking the up arrow.  

If I set it to 2 and have a starting time of 07:00, clicking up changes it to 07:02 as it should.  But clicking up again changes it to 07:22.  Then clicking up again does nothing - presumably because it's trying to change it to 07:222 which is not valid.

Clicking the down arrow works correctly though.

**Comment by DanielYKPan** [comment]
I can't reproduce the issue. 
It works fine to me as I set [stepMinute]='2'

**Comment by jcachat** [comment]
Sorry, I set the property as "stepMinute='2'" not "[stepMinute]='2'".  It works correctly with the []'s.  Odd that the down arrow worked differently though.

**Comment by DanielYKPan** [comment]
because in the down arrow function, 
the code is something like this
```
stepMinute = -stepMinute
```
the ' - ' would make string to a number
