### ISSUE TITLE
Build fail with Angular 5.2 & fullTemplateTypeCheck enabled

### ISSUE THREAD

**Issue by Enngage** [DanielYKPan/date-time-picker#235]
Hey there,

Thanks for the plugin!

I upgraded Today and noticed that when you enable `fullTemplateTypeCheck` (https://next.angular.io/guide/aot-compiler) & then build the site with AOT `ng build --aot` you will get following errors. You might need to make those properties public to get rid of the issue.

![a](https://user-images.githubusercontent.com/7137351/34980834-ff3f0032-faa5-11e7-924e-b871ceff29f3.png)

**Comment by DanielYKPan** [comment]
Updated to latest version,
it should be fixed.

Close this at this moment.
