### ISSUE TITLE
Support for Angular 4

### ISSUE THREAD

**Issue by Isirak98** [DanielYKPan/date-time-picker#238]
Hi,
The date-time-picker is said to support only Angular 5, I was wondering if there is an Angular 4 version of this, which uses 'date-fns' instead of 'moment'. 

I tried adding the current version to my existing Angular 4 application which gave me a version mismatch error. 
'ERROR in Metadata version mismatch for module ../../node_modules/ng-pick-datetime/picker.d.ts, found version 4, expected 3'
Since this was a version mismatch error, I installed a previous version (4.3.4, which I assumed was the Angular 4 version) but there I couldn't find the installation steps for it.

If you do have the installation steps for the version or the correct Angular 4 version's repo, would you be able to share them? If not it is totally fine, and understandable.

Thanks a lot,
Isira K

**Comment by DanielYKPan** [comment]
You could simply just upgrade to angular 5

**Comment by chinkan** [comment]
Hi,
I also have this issue. I need to use Angular 4 because it is LTS version. Would you have any old version document which support Angular 4 for installation? Thanks for your help!

**Comment by andresmeidla** [comment]
@chinkan v4.3.4 is for angular 4.

**Comment by chinkan** [comment]
@andresmeidla ok let me try, thanks for your help!
