### ISSUE TITLE
dynamic component-input connection

### ISSUE THREAD

**Issue by grreeenn** [DanielYKPan/date-time-picker#239]
I want to build a dynamic form-builder for my app; fields need to be generated come from DB and being assigned by type.

The problem is connecting the input to the component.It's impossible (as I know) to set the template variable names programmatically, and as I understand from the docs template variable is the only way to connect between input and component.

Did you face similar issues before? Is there some way around?

**Comment by DanielYKPan** [comment]
How do write your html input and the picker component? I guess the way how you write your input and the picker component is the way how you assign the picker component to your input

**Comment by grreeenn** [comment]
I have a template which runs in ngFor loop on array of fields it gets from specialized service, while each field object in such array contains everything's necessary for creating an input field - type, name etc.  In most cases it just creates <input> with a type set in associated object; but since I need a datetime field which doesn't have a native multi-browser implementation - I've chose an excellent alternative of yours :)

The field creation code is based on a copypaste from the demo page:
```
<ng-container *ngIf="field.type == 'datetime-local'">
      <input class="form-control"
             [type]="'text'"
             [formControlName]="field.key"
             [id]="field.key"
             [owlDateTime]="dt"
             [owlDateTimeTrigger]="dt">
      <owl-date-time #dt></owl-date-time>
    </ng-container>
```
So, the connection goes by template variable #dt, which name I can't generate dynamically; so, my question is - how can I manage this case?

Thank you for your time and sorry if it's kinda noobish question - I'm not so experienced in Angular...

**Comment by DanielYKPan** [comment]
In this case, you might consider to create a component which accept a type, id ect to create input.
eg:
```
<your-new-component *ngFor="let field of fields"  
         [type]="field.type" [id]="field.id" [key]="field.key" ></your-new-component>
```

in your new component template:

```
<input [type]="type" [id]="id" [key]="key" 
           [owlDateTime]="dt"
           [owlDateTimeTrigger]="dt">
<owl-date-time #dt></owl-date-time>
```
