### ISSUE TITLE
Latest version - Datetime picker is displayed with incorrect style

### ISSUE THREAD

**Issue by francisminu** [DanielYKPan/date-time-picker#240]
Hi,

I added the datetime picker today. The latest version that was uploaded yesterday. 
I have followed all the steps in the readme file.
Please find attached the screenshot of the page that comes up. Please let me know if you think I am missing on anything
![datepicker](https://user-images.githubusercontent.com/14043523/35074062-aed170b4-fbb1-11e7-958e-5c7e770e3381.JPG)

**Comment by DanielYKPan** [comment]
You have't load the css style.
Please read the doc carefully

**Comment by francisminu** [comment]
I did load the css style. I can see the styles loaded when I do inspect.

**Comment by francisminu** [comment]
My bad! Was loading it in the wrong location. Thanks!
