### ISSUE TITLE
Updated version of ng-pick-datetime giving errors in Angular 4 projects.

### ISSUE THREAD

**Issue by chiragkataria22** [DanielYKPan/date-time-picker#242]
I was using ng-pick-datetime version 5.0.0-beta.5 in my Angular 4 project and customised its CSS according to my design.But due to some problem i needed to install packages again so it updated the version to 5.1.0 and now all the CSS is changed even arrow functionality to change months is not working.
I read the documentation of the updated version and tried to do according do that but it gives following erros:
./~/ng-pick-datetime/picker.module.js
Module build failed: Error: ENOENT: no such file or directory, open '/node_modules/ng-pick-datetime/picker.module.js'
or 
Some errors of rxjs/operators not found.
i then installed previous version for ng-pick-datetime but still my applied CSS is not working nor the arrow functionality.
Please help ASAP

**Comment by DanielYKPan** [comment]
If ther version 5.0.0-beta.5 is working for you, just npm install back that version

**Comment by chiragkataria22** [comment]
Hi
I installed that version
But even now i am not able to use arrow key functionalities
Moreover i can't even see the side arrows and arrows for changing time

**Comment by DanielYKPan** [comment]
Then you have to debug yourself. 
The npm package could not be changed once it is published,
therefore if your apps worked in version 5 beta-5 before, it should works in version 5 beta 5

**Comment by chiragkataria22** [comment]
It means i have to see some other module for this
As it is not working
I have spent 2 days on it still not able to find out the solution
Well if the owner can't debug it then i think changing the module will be a
better option.

Thanks for your time
