### ISSUE TITLE
Changes directly on the input doesn't affect the model

### ISSUE THREAD

**Issue by knobandre** [DanielYKPan/date-time-picker#243]
If I make a change to a date (or hour) directly on the input, it is not reflected on the picker when it is opened up.

Even a code as basic as below does not work.
`<input [owlDateTime]="dt" [owlDateTimeTrigger]="dt">
<owl-date-time #dt></owl-date-time>`

I'm using version 5.1.0.

Thanks

**Comment by DanielYKPan** [comment]
@knobandre 
As you can see in demo, it works. I could reproduce the issue you described

**Comment by DanielYKPan** [comment]
I would close this as getting no reply from
