### ISSUE TITLE
CSS import fails with Angular CLI: 1.6.4

### ISSUE THREAD

**Issue by abroccoli** [DanielYKPan/date-time-picker#244]
`@import "~@ng-pick-datetime/assets/style/picker.min.css";`

Error:
```
./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css
Module build failed: Error: Can't resolve '~@ng-pick-datetime/assets/style/picker.min.css'
```

also fails without the `~` `@import "@ng-pick-datetime/assets/style/picker.min.css";`

**Comment by DanielYKPan** [comment]
It is @import "~ng-pick-datetime/assets/style/picker.min.css"

**Comment by abroccoli** [comment]
@DanielYKPan that also fails

**Comment by DanielYKPan** [comment]
I just tested it in a fresh angular cli project, and it works fine

**Comment by DanielYKPan** [comment]
@abroccoli 
I checked the angular cli github issue.
Someone post this https://github.com/angular/angular-cli/issues/9296

I would suggest you upgrade your angular cli to 1.6.5

**Comment by abroccoli** [comment]
@DanielYKPan Thank you very much for taking a look. I was able to get it working in 1.6.4 as  `@import "ng-pick-datetime/assets/style/picker.min.css"`

I should probably update though!
