### ISSUE TITLE
Default date show with time

### ISSUE THREAD

**Issue by rameshyala** [DanielYKPan/date-time-picker#247]
Hi,

i need to set this date picker by default with today date, in view it's show with time, when i change the date it showing properly ,so my doubt is by default how i fix these .Sorry for my English .Thank you

define in formgroup like:
'dob': [ new Date() , [Validators.required, validateDOB]], 

 i try like set time is 0 also but it looks same,i need to by default setup date not showing the time.

![image](https://user-images.githubusercontent.com/18004992/35276129-4df60b5e-0068-11e8-942d-570369cfe767.png)

**Comment by DanielYKPan** [comment]
Are you trying to use only the 'Calendar' and no 'Timer'?

If you are, just set [pickerType]=" 'calendar' "

**Comment by rameshyala** [comment]
Hi DanielYKPan , 
i am use 'calendar', the complete code is

<input
          [formControl]="control"
          [min]="MinDate"
          [max]="MaxDate"
          (dateTimeChange)="pickDate($event)"
          [owlDateTimeTrigger]="dt6"
          [owlDateTime]="dt6">
        <owl-date-time [pickerType]="'calendar'" #dt6></owl-date-time>

**Comment by DanielYKPan** [comment]
@rameshyala 
I see the issue, and it already been fixed.
The new version would be published in the next couple day.

Thanks

**Comment by DanielYKPan** [comment]
This issue has been fixed in ng-pick-datetime version 5.1.1
