### ISSUE TITLE
Bug with hour12Timer option

### ISSUE THREAD

**Issue by sdornan** [DanielYKPan/date-time-picker#248]
Using the `hour12Timer` option, I am unable to set the hour to 12 by clicking the up arrow because it becomes disabled at 11. If I click the down arrow past 0, then the hour values wraps back around to 12 and I can set it that way, but obviously, this isn't very intuitive and doesn't seem like intentional behavior.

![image](https://user-images.githubusercontent.com/563517/35314472-07764710-008c-11e8-8540-32cb256cd7d4.png)

**Comment by DanielYKPan** [comment]
Yes, it is intensional...
you can not increase the hour because 11PM is the last hour of a day
