### ISSUE TITLE
Suggestion about the theme

### ISSUE THREAD

**Issue by yunClouds** [DanielYKPan/date-time-picker#25]
@DanielYKPan 
Hi, Daniel , I have a suggestion that the  [theme]  can set GRB  too, like this:   [theme]="'#ff576b'" . 
 And than its will be more compatible。
BTW, just a suggestion, for reference only

**Comment by DanielYKPan** [comment]
@yunClouds 
Good idea.

**Comment by DanielYKPan** [comment]
@yunClouds 
The [theme] has been changed to the way like you suggested. Please update to the package to the latest version.
