### ISSUE TITLE
29 October 1916 cannot be set in date picker, only by typing

### ISSUE THREAD

**Issue by coffeetea-synchestra** [DanielYKPan/date-time-picker#251]
When setting 29 October 1916 date picker automatically changes it to 28 October 1916 and all dates before it change to one day before.

**Comment by DanielYKPan** [comment]
I tested it in the demo, it works fine.

**Comment by coffeetea-synchestra** [comment]
Let me share video record 
https://www.useloom.com/share/31afdb340fb2464ab945b6238669c919

**Comment by DanielYKPan** [comment]
@coffeetea-synchestra 
Try the version 5.1.2, it should be fixed.

I would close this for now.
If you still have this issue in version5.1.2, please inform me.
Thanks.

**Comment by coffeetea-synchestra** [comment]
@DanielYKPan 
Thank you! So fast! I can check it on my project later (in a couple of days), but see on the demo it's ok.

Good job!
