### ISSUE TITLE
ngcli build error

### ISSUE THREAD

**Issue by hipresario** [DanielYKPan/date-time-picker#252]
angular cli: 1.3.2
angular: 4.3

we had this error when build the project:

> ERROR in Metadata version mismatch for module /node_modules/ng-pick-datetime/picker.d.ts, found version 4, expected 3

Any suggestion? thanks.
..

**Comment by gwillebaldhub** [comment]
Im having the same issue

**Comment by DanielYKPan** [comment]
Update your angular cli and angluar

**Comment by mkamranhamid** [comment]
I know its too late to reply here but this is for someone who's fall on this page from google. The thing that worked for me was to remove the cap(`^`) from dependency.

**Before**:
`"ng-pick-datetime": "^5.0.0-beta.15",`
**After**
`"ng-pick-datetime": "5.0.0-beta.15",`
