### ISSUE TITLE
Time picker off screen

### ISSUE THREAD

**Issue by ashhitch** [DanielYKPan/date-time-picker#253]
In version: 5.1.0 when input field it close to the edge of the screen the component gets cut off.

![screen shot 2018-01-25 at 11 42 13](https://user-images.githubusercontent.com/2438290/35386897-940e53b8-01c5-11e8-9484-ae1416e0f485.png)

**Comment by DanielYKPan** [comment]
@ashhitch 
Try the version 5.1.2, it should be fixed.

I would close this for now.
If you still have this issue in version 5.1.2, please inform me.
Thanks.
