### ISSUE TITLE
Error when setting pickerType on owl-date-time-inline 

### ISSUE THREAD

**Issue by diegoalex** [DanielYKPan/date-time-picker#254]
Hi Guys,

I'm getting this error when trying to set the " [pickerType]="'calendar'" " on owl-date-time-inline  .

![image](https://user-images.githubusercontent.com/3237570/35411639-9c4d1f4c-0200-11e8-8e19-416e75680e7b.png)

It works fine, but I keep getting this message error which disapear when I remove the pickerType (but shows the time selector). follow my code:
`
<owl-date-time-inline [pickerType]="'calendar'" [min]="minimumDate" [(ngModel)]="filter.date" [ngModelOptions]="{standalone: true}" ></owl-date-time-inline>
`

The error is happening on date-time.class.js:42 , because the this.dtInput is null...
```javascript
 set: function (val) {
            if (val !== this._pickerType) {
                this._pickerType = val;
                if (this.selectMode === 'single') {
                    this.dtInput.value = this.dtInput.value; //Error line
                }
                else {
                    this.dtInput.values = this.dtInput.values;
                }
            }
        }
```

Am I doing something wrong?

Tks!

**Comment by DanielYKPan** [comment]
@diegoalex 
Thanks man, this bug has been fixed. The new version would be published in next couple days

**Comment by DanielYKPan** [comment]
Try latest version, it should be fixed.
