### ISSUE TITLE
Set user view format.

### ISSUE THREAD

**Issue by manisankar92** [DanielYKPan/date-time-picker#255]
Hi,
I am using ng-pick-datetime (version 5.1.2.). I want to set user view(in input box) format for the date picker. the default format is 'MM/DD/YYYY'. I want to change to format 'DD/MM/YYYY'. How can I set the user view format(in input box)?

**Comment by DanielYKPan** [comment]
Learn more from [here](https://danielykpan.github.io/date-time-picker/#locale-formats)
