### ISSUE TITLE
date range not working after getting data from services

### ISSUE THREAD

**Issue by lingeswrn** [DanielYKPan/date-time-picker#258]
Hi admin,
I am trying to show date range in inline datepicker after api response.
but its not happening.

**Comment by DanielYKPan** [comment]
Any demo or codes? No way I could provide any inform about this.
I would close this issue for now.

**Comment by lingeswrn** [comment]
TS file:
`this.http.securePost(this.constants.JOB_DETAIL, reqParams).subscribe((res) => {
        this.selectedMoments = [new Date(2018, 3, 21, 20, 30), new Date(2018, 3, 29, 20, 30)];
});`

HTML File:
`<owl-date-time-inline [(ngModel)]="selectedMoments" [pickerType]="'calendar'" [selectMode]="'range'"></owl-date-time-inline>`

Please help me i am stuck here

**Comment by DanielYKPan** [comment]
Did you try to use the picker in dropdown mode and see if the issue exits as well?

**Comment by mrjihai** [comment]
I have the same issue. Set the date after api response, but nothing show in the date line.
