### ISSUE TITLE
date-time-picker & reactive Forms

### ISSUE THREAD

**Issue by lazysatyr25** [DanielYKPan/date-time-picker#26]
Hi. Can i use date-time-picker with reactiveForms ?

**Comment by DanielYKPan** [comment]
@lazysatyr25 
I have not tested it yet. But I will test it tomorrow. I would let you know once I go through all those tests.
Thanks.

**Comment by DanielYKPan** [comment]
@lazysatyr25 
I just used dateTimePicker in the [Angular Reactive Example](https://angular.io/docs/ts/latest/guide/reactive-forms.html). And it works well.

**Comment by RaphyLi** [comment]
@DanielYKPan sorry to reopen the issue, but I try to use dateTimePicker with reactiveForms but when I select the date, the dialog doesn't close and the value doesn't set.

So how did you do your test? 

And did you try to use a pipe date?

**Comment by suggy75** [comment]
@RaphyLi I got this working by hooking into the dateTimePickerChange event.
`<input
    class="form-control ml-2"
    [ngModel]="viewModel.myDate | date: 'medium'"
    [dateTimePicker]="viewModel.myDate"
    [viewFormat]="'DD/MM/YYYY HH:mm'"
    [mode]="'dropdown'"
    (dateTimePickerChange)="onSetMyDate($event)"
    formControlName="myDate"
    readonly>`

Then I manually set the value on the formControl
`onSetMyDate(date: any): any {
    this.myForm.controls['myDate'].setValue(date);
    return date;
  }`

Not sure if this is the right way to go about this, but it works....

**Comment by DanielYKPan** [comment]
@suggy75 
Sweet...That is how I tested it...

**Comment by RaphyLi** [comment]
@suggy75 thx for you help.
I try this and a can't use `[ngModel]` so a I use `[value]="viewModel.myDate | date: 'medium'" ` but when the date change the filter doesn't apply :(

**Comment by RaphyLi** [comment]
@suggy75 thx for you response.

I try this solution but I have a problem. I can't use `[ngModel]` because in my component I subscribe the value changes of my form like this : `this.form.valueChanges.debounceTime(2000).map((data) => this.save()).subscribe();` and the input date trigger change value so `save` is called. 

To bypass this I change `[ngMode]` by `[value]` and my code is: `<input class="date-picker-input" name="startDate" [ngModel]="campaign.startDate | date:'yyyy-MM-dd'" [(dateTimePicker)]="campaign.startDate"
              (dateTimePickerChange)="setStartDate($event)" [mode]="'dropdown'" [viewFormat]="'yyyy-MM-dd'" [locale]="'fr'" [theme]="'#009FE3'" 
              [pickerType]="'date'" readonly placeholder="Date de début" />`.

All works but when I change the date in my ts code the format of my input date mess up.

**Comment by ermarkar** [comment]
I am facing issue while using `formcontrolname`

```
<input [owlDateTime]="feedStartDate" formControlName="startDate" [owlDateTimeTrigger]="feedStartDate"
             placeholder="Start Date" class="validate" id="feedStartDate">
            <owl-date-time #feedStartDate></owl-date-time>
```

and here is

```
this.addFeedForm = new FormGroup({
      title: new FormControl("", Validators.compose([Validators.required])),
      startDate: new FormControl("2019-04-15", Validators.compose([Validators.required])),
});
```

but this is not getting selected by default? Am I missing something?
