### ISSUE TITLE
No trigger on tab focus

### ISSUE THREAD

**Issue by OlivierMary** [DanielYKPan/date-time-picker#260]
Hi,

With this version : "ng-pick-datetime": "^5.1.3",

When using tab on focus on a owlDateTime no picker appear.

All fine with the mouse.

With material
```
    <mat-form-field>
      <input matInput [(ngModel)]="event.dateTime" placeholder="DateTime" [owlDateTimeTrigger]="dt" [owlDateTime]="dt">
      <owl-date-time #dt></owl-date-time>
    </mat-form-field>
```
or without
```
      <input [(ngModel)]="event.dateTime" placeholder="DateTime" [owlDateTimeTrigger]="dt" [owlDateTime]="dt">
      <owl-date-time #dt></owl-date-time>
```
it's not working.

**Comment by DanielYKPan** [comment]
Yes, it is intension.
When you focus your trigger (in your case, it is input), use ALT+ARROW_DOWN to open the picker.

**Comment by OlivierMary** [comment]
@DanielYKPan why? I can't tell users to "ALT+ARROW_DOWN" if they want to use keyboard...
Any work around ?

**Comment by DanielYKPan** [comment]
Because users might want to tab into the input and type their date time straight to the input.

In your case, you might consider separate the trigger and your input. For example, use icon button next to your input and user could tab into the button and ENTER to trigger the picker open.

**Comment by OlivierMary** [comment]
@DanielYKPan Ok thank for your help
