### ISSUE TITLE
Can not  show date time picker in modal 

### ISSUE THREAD

**Issue by minhthuan274** [DanielYKPan/date-time-picker#261]
![image](https://user-images.githubusercontent.com/20428875/35793655-268eb8a0-0a85-11e8-9688-099b7624a601.png)
I wanna show date time picker below the label, but seem it deeper than modal. Anyone can help me, thanks!

**Comment by riyagloify** [comment]
I am also facing the same issue. I have a modal box open in that modal I want to show date time picker but it is not displaying the date time picker. Can anyone explain what is the issue?

**Comment by DanielYKPan** [comment]
adjusting your z-index setting.

set 
.cdk-overlay-container {
  z-index: YOUR_VALUE
}

**Comment by riyagloify** [comment]
Got the temporary solution.  Overriding the CSS- 

.cdk-overlay-container {
    z-index: 100000; 
    position: absolute;
}

**Comment by minhthuan274** [comment]
Thanks so much ✌️
