### ISSUE TITLE
Takes a long time for the date pickers to appear with moment js

### ISSUE THREAD

**Issue by stan-radu-andrei** [DanielYKPan/date-time-picker#262]
When using OwlMomentDateTimeModule for formatting, after the click on input, it takes 3-5s for the date picker to show. I only use 2 date pickers on the page. Does anybody else had this problem?

Using:
    "ng-pick-datetime": "^5.1.3",
    "ng-pick-datetime-moment": "^1.0.4",

import { OwlDateTimeModule, OWL_DATE_TIME_FORMATS, } from 'ng-pick-datetime';
import { OwlMomentDateTimeModule } from 'ng-pick-datetime-moment';

export const MY_MOMENT_FORMATS = {
  parseInput: 'YYYY-MM-DD HH:mm',
  fullPickerInput: 'YYYY-MM-DD HH:mm',
  datePickerInput: 'YYYY-MM-DD',
  monthYearLabel: 'MM YYYY',
  dateA11yLabel: 'L',
  monthYearA11yLabel: 'MM YYYY',
  timePickerInput: 'HH:mm'
};

**Comment by DanielYKPan** [comment]
You could see my demo page, it has about 10 pickers and it does not have the problem you described.

**Comment by stan-radu-andrei** [comment]
I agree. But in your demos you don't format the date with OwlMomentDateTimeModule. When I don't use OwlMomentDateTimeModule works just fine.

**Comment by DanielYKPan** [comment]
I could easily change it to use MomentJS, but still it does not have the issue you described.

**Comment by DanielYKPan** [comment]
I would suggest you to create a new angular-cli project, use the picker with MomentJS and see if the issue exists.

I would close the issue for now.
