### ISSUE TITLE
Parse input for date and time seperately

### ISSUE THREAD

**Issue by MarkVink** [DanielYKPan/date-time-picker#265]
I have a use case where two date-time-picker components are used on the same page; 
- one for selecting a date, accepting the format dd-mm-yyyy, 
- and the other for selecting a time, accepting the format HH:mm. 

Bot input fields should parse the correct date/time when a user types or pastes his input. Besides this use case the datepicker is displayed in Dutch.

I tried playing around with providing customs formats, but I couldn't get my use case to work. Ive configured datePickerInput: 'L', timePickerInput: 'HH:mm' but still the time picker seems to be looking for a format similar to the datepicker.

Select 10:10 => Tue Feb 06 2018 10:10:39 GMT+0100 CORRECT
Type 10:10 => Tue Oct 10 0000 00:00:00 GMT+0200 INCORRECT

I'm not sure wether my use case would be achievable by supplying your own formats -or that it's just not possible yet. Therefore this ticket, does anyone know?

See this repo for a simple demo
https://github.com/MarkVink/date-time-picker-incorrect-demo/tree/master/src/app

**Comment by DanielYKPan** [comment]
Thanks @MarkVink .
I guess I know what causes this bug and I would fix it.

**Comment by DanielYKPan** [comment]
@MarkVink 
The reason causes this issue is because you provided a invalid parseInput format
In your demo, your custom parseInput value your provided is "dd, L, LT". This is incorrect MomentJs Format.

If you just use format with MomentJS, you would see a invalid date time error in MomentJS Object.

```
import {Component, OnInit} from "@angular/core";
import * as _moment from "moment/moment";
import {Moment} from "moment/moment";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {
  selectedDate: Date = new Date();
  selectedTime: Date;

  ngOnInit(): void {
    const incorrectFormat = _moment('wo, 07-02-2018, 10:10',  'dd, L, LT',  'nl');
    console.log(incorrectFormat);
  }
}
```

**Comment by MarkVink** [comment]
Thank you for your replay and looking into my issue, however I keep having trouble supporting my usecase;

As you mentioned Ive tried to use the picker's defaults parseInput which should be set to [null](https://github.com/DanielYKPan/date-time-picker/tree/eea556be386362c1096d04cfd43e320c21a4149d/src/date-time/adapter) for both the native and monentjs. 

When I do so, typed input 06-02-2018 will be parsed as Sat Jun 02 2018 00:00:00 GMT+0200 (And not dd/mm/yyyy). Also changing the time by typing input yourself doesn't seem to work in my case - keep in mind that i've set the OWL_DATE_TIME_LOCALE to 'nl'.

**Comment by DanielYKPan** [comment]
I am not gonna continue to look at this issue unless there is a demo to show the issue.
Without any demo, this is painful.

**Comment by MarkVink** [comment]
See this demo for my original demo
https://github.com/MarkVink/date-time-picker-incorrect-demo

And this branch where I've set the parseInput to null as its the picker's default
https://github.com/MarkVink/date-time-picker-incorrect-demo/tree/default-parseinput

**Comment by DanielYKPan** [comment]
Why you set your parseInput to null if you want to parse the input to date?

The reason why my parseInput is null is because I am using the Native Javascript Date Object, and it does not have any parse function.

If you are using the MomentJs, you need to set your parseInput so that MomentJS understand how to parse your input to a MomentJS Object.

set your custom MomentJS format like this
```
export const MY_MOMENT_FORMATS = {
  parseInput: 'L LT',
  fullPickerInput: 'L, LT',
  datePickerInput: 'L',
  timePickerInput: 'HH:mm',
  monthYearLabel: 'MMMM YYYY',
  dateA11yLabel: 'LL',
  monthYearA11yLabel: 'MMMM YYYY',
};
```

And here is the result from your demo after the changes:
![demo](https://user-images.githubusercontent.com/5952855/36148047-b16a2b14-110e-11e8-9ed7-a0efb8d1f535.gif)

**Comment by MarkVink** [comment]
Thanks for your feedback!

**Comment by DanielYKPan** [comment]
You are welcome.
date-time with locale sometimes is a little tricky.
And Native Javascript Date Object is not good at that.
I would recommend to using MomentJS and let it do the heavy job.
