### ISSUE TITLE
DateTimeAdapter.setLocale: Change 12/24h Time Format

### ISSUE THREAD

**Issue by roeb** [DanielYKPan/date-time-picker#267]
Hello,

thanks for your work and this really cool DateTimePicker. 

Is it possible that when, calling DateTimeAdapter.setLocale(), the property [hour12Timer] is set on the owl-date-time. In concrete terms, if I set the language on de-DE, I would like to have 24h and with en-US like 12h. Or is there such a function and I just overlooked it?

Thanks for your support.
Robert

**Comment by DanielYKPan** [comment]
No, it could not. Because there is no way to find out which locale has the 24hour format and which has the 12hour format.
