### ISSUE TITLE
Inline element not reflecting changes to model

### ISSUE THREAD

**Issue by daverickdunn** [DanielYKPan/date-time-picker#268]
Hi,

I'd like to use the inline version of the calendar, I actually have two, and updating one sets a minimum date on the other. All my code works as expected, except the second calendar doesn't change on model change.  It does however reflect the change when selected, so it is getting the value, but not implementing OnChanges (or similar).

I've simplified the issue to the following, if you want to test it for yourself.

`<owl-date-time-inline [(ngModel)]="selectedMoment"></owl-date-time-inline>`

```
    selectedMoment: Date = null;

    constructor() {}
    
    ngOnInit() {
        this.selectedMoment = new Date();
        setInterval(()=>{
            console.log(this.selectedMoment)
            this.selectedMoment.setMonth(this.selectedMoment.getMonth() + 1)
        }, 1000)
    }
```

With this code you can see the current month is changed and printed to the console every 1000ms. However the calendar shows no change. **_But_**, if you click somewhere on the calendar every >~1000ms you'll see the change as the click event has triggered a re-render.

I'd expect it to redraw without the need to click on the calendar. Am I missing a trick here to get it to update?

Thanks in advance.

Edit: A picture speaks 1000 words.

![cal](https://user-images.githubusercontent.com/7645242/35970296-c0ff9f56-0cc1-11e8-9824-cb9116f66549.gif)

**Comment by DanielYKPan** [comment]
This is because setMonth method could only change the selectedMoment's month value, but your selectedMoment is still the same object, and angular treats it as the same value (mutant object).
This means your selectedMoment does not changed at all even your selectedMoment month value changed.

Update your date time picker version to ^5.1.5, 
and use below to change your selectedMoment and it should be fine
```
this.selectedMoment = new Date(
this.selectedMoment.getYear(),
this.selectedMoment.getMonth()+1,
this.selectedMoment.getDate()
)
```

**Comment by daverickdunn** [comment]
Ahh, I understand now, thanks for the concise and fast reply! I'll pass a new object going forward...

**Comment by daverickdunn** [comment]
Can I add, perhaps it's something you'll consider in future updates: my real issue/goal here was changing the min and max parameters. I can get them to update when I change the model to a new Date object, in other words I'm having to change them and then change the model object to reflect their changes. I'm sure you're trying to keep things simple, but it'd be _nice_ if they were to update when passed new objects.
