### ISSUE TITLE
Today Button Functionality Not Working on Different Months and Year

### ISSUE THREAD

**Issue by dineshdedhia** [DanielYKPan/date-time-picker#27]
For Eg: I go to different year or month and click on "Today Button" it doesn't goes to and highlight Today's Date.

**Comment by DanielYKPan** [comment]
@dineshdedhia 
Yes, thanks.
The bug has been fixed. Update the picker package and It should be all right.

**Comment by dineshdedhia** [comment]
Hello @DanielYKPan 

Thanks Its done :)

Thanks once again
