### ISSUE TITLE
Set user view format. For different instances of picker in same form

### ISSUE THREAD

**Issue by manishjanky** [DanielYKPan/date-time-picker#270]
Hi,
I am using 
```
"ng-pick-datetime": "^5.1.5",
 "ng-pick-datetime-moment": "^1.0.4",
```
I want to change to format 'DD/MM/YYYY' and i have achieved the same using moment and the [customFormats](https://danielykpan.github.io/date-time-picker/#locale-formats). 
But now i have more than 1 date/time pickers in the same form. And i have to choose `date` only with some fields and `dateTime` in other fields. but the custom formats are applicable to all the instances of the picker. I would be good if we can have `format` as a property to the instance and based on that display the date in UI.

**Comment by DanielYKPan** [comment]
From what i understand from your require, you are not using different format. You just use the date only in some fields and dateTime in other fields.

Just change [pickerType] to 'calendar' for your date only fields.

Besides, I don't understand why people need two different date time format in the same form.

**Comment by manishjanky** [comment]
Yes You got it right. 
But i want the format to be `DD/MM/YYYY` for date only fields to be displayed in UI and `DD/MM/YYYY HH:mm:ss` for the datetime fields. But after setting the custom formats in UI it shows as either `DD/MM/YYY` or `DD/MM/YYYY HH:mm:ss` whichever is set in the custom formats. Even though the `pickerType = 'calendar'` for date only and `pickerType='both'` for datetime.
Below are the custom formats i'm trying to set
```
export const MY_MOMENT_FORMATS = {
    parseInput: 'DD/MM/YYYY HH:mm:ss',
    fullPickerInput: 'DD/MM/YYYY HH:mm:ss',
    datePickerInput: 'DD/MM/YYYY HH:mm:ss',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
};
```

**Comment by DanielYKPan** [comment]
export const MY_MOMENT_FORMATS = {
    parseInput: 'DD/MM/YYYY HH:mm:ss',
    fullPickerInput: 'DD/MM/YYYY HH:mm:ss',
    datePickerInput: 'DD/MM/YYYY',
    timePickerInput: ' HH:mm:ss',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
};

**Comment by vvip-68** [comment]
Hi! I `m have almost same issue: I have two timepicker on form, both of them use fullPickerInput,
but I need for first set datetime format as fullPickerInput: 'DD-MM-YYYY HH:mm', but for second as fullPickerInput: 'MMM-DD HH:mm'.  How I can implement this?

**Comment by Bhavana-Patil** [comment]
export const MY_MOMENT_FORMATS = {
parseInput: 'DD/MM/YYYY HH:mm:ss',
fullPickerInput: 'DD/MM/YYYY HH:mm:ss',
datePickerInput: 'DD/MM/YYYY',
timePickerInput: ' HH:mm:ss',
monthYearLabel: 'MMM YYYY',
dateA11yLabel: 'LL',
monthYearA11yLabel: 'MMMM YYYY',
};

Using above code for date format it gives following error

![image](https://user-images.githubusercontent.com/44719445/55860167-3ccd8c00-5b91-11e9-9573-ab4ad6332677.png)
