### ISSUE TITLE
error cannot read property 'confirmSelectedChange' of undefined

### ISSUE THREAD

**Issue by daniel12564** [DanielYKPan/date-time-picker#271]
Hi,
I'm getting this error while trying to replicate the example of the README. I was searching about this problem but i couldn't find anything useful related to this problem.

![captura de pantalla de 2018-02-12 15-27-21](https://user-images.githubusercontent.com/4305949/36117945-66465b22-1009-11e8-84a4-d5dcc22c42a6.jpg)

This is the data-mesh.component.pug
```pug
input(
    [owlDateTimeTrigger]="dt3",
    [owlDateTime]="dt3")
owl-date-time#dt3

```

This is the app.module.ts
```typescript
...
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';

...

import { AppComponent } from './app.component';
import { DataMeshComponent } from './Data-mesh';

....

@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
    DataMeshComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    OwlDateTimeModule,
    OwlNativeDateTimeModule,
  ],
  providers: [
    ....
  ]
})
export class AppModule {}

```
This is the package.json

```json
"dependencies": {
    "@angular/animations": "~5.1.0",
    "@angular/core": "~5.1.0",
    "ng-pick-datetime": "^5.1.5"
  },
```

**Comment by DanielYKPan** [comment]
The error you got means your picker input doesn't have any associated owl-date-time component. You might have to debug your apps to see what caused this issue.

**Comment by magebharath** [comment]
I have the same error what can i do now @DanielYKPan , @daniel12564

**Comment by magebharath** [comment]
Getting the Error: "OwlDateTimePicker: the picker input doesn't have any associated owl-date-time component" (owlDateTime Not working)
 
All all worked fine but after i install this command on CLI  "ng add @angular/material" date picker stoped working and i am getting this error...
 
Please help me i tryed While , i wasted a day with this...
