### ISSUE TITLE
Error when running angular 4 app in aot

### ISSUE THREAD

**Issue by rjsalem** [DanielYKPan/date-time-picker#273]
Hi,

When I am using the ng-time-picker in development environment everything is working fine. But when I decide to put it in production and build my app with aot, the ng-time-picker gave me an error. 

The code in my app : 

`<input [owlDateTimeTrigger]="dt10" [owlDateTime]="dt10" (dateTimeChange)="pickerClosed($event)" [selectMode]="'range'" />
              <owl-date-time #dt10 [pickerMode]="'dialog'"></owl-date-time>`

Error :

![image](https://user-images.githubusercontent.com/36514017/36270942-156f82c0-124b-11e8-8a41-5d39b1c9e4a7.png)

**Comment by DanielYKPan** [comment]
Updated you angular version to 5

**Comment by rjsalem** [comment]
I updated to angular 5 didn't changed a thing. 

![image](https://user-images.githubusercontent.com/36514017/36280295-d41120c8-1267-11e8-907c-c7bf5f28b968.png)

**Comment by DanielYKPan** [comment]
If you are using the angular cli, create a new project and use the picker in your new project and run
```
ng build --prod
```

I just tested it in the brand new angular cli project, it caused NO error in --aot build.

My cli version:
@angular/cdk: 5.2.1
@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
