### ISSUE TITLE
Allow add custom date format

### ISSUE THREAD

**Issue by XardoniK** [DanielYKPan/date-time-picker#277]
Is it possible to add custom date format like 'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM:SS' like before in your plugin?

**Comment by DanielYKPan** [comment]
https://danielykpan.github.io/date-time-picker/#locale-formats

**Comment by magictune** [comment]
@DanielYKPan  i followed up the url  but i dont know to to use this exactly inside my component bro :) 

here is the app module 

![image](https://user-images.githubusercontent.com/36736057/36543736-51ea5afc-17ed-11e8-9be9-040b9fc9d7e3.png)


and here is my component 

![image](https://user-images.githubusercontent.com/36736057/36543759-658770c2-17ed-11e8-9d7e-7bd6f100e8a0.png)


how to use my format in app module through  all my components

**Comment by magictune** [comment]
@XardoniK  did you did it ?

**Comment by XardoniK** [comment]
@magictune yes but I looked to change output format of date. It is so hard than before but i tried and did something.  

@DanielYKPan can you provide a simple example what we are make a custom provider. I copied your native adapter and try change what I need. Its work but... not perfect.. :) I changed return value in format function copied from https://github.com/DanielYKPan/date-time-picker/blob/master/src/date-time/adapter/native-date-time-adapter.class.ts

![image](https://user-images.githubusercontent.com/9059223/36695649-384a0b6c-1b42-11e8-8de2-1c5612c70842.png)

My code(only return value changed)
![image](https://user-images.githubusercontent.com/9059223/36695852-c432bfca-1b42-11e8-81a1-6962979d2855.png)
