### ISSUE TITLE
Styling as part of the components

### ISSUE THREAD

**Issue by zlepper** [DanielYKPan/date-time-picker#278]
According to the Angular Style Guide, components should include their own css. Global styles shouldn't be used: https://angular.io/guide/styleguide#extract-templates-and-styles-to-their-own-files 

If the styles are part of the global style.css, then they have to be loaded always when the site loads. They cannot be loaded as part of a lazy module. 

I can see the component files already have a .css file attached, so changing things around shouldn't be that much of a problem, although it will break existing projects that includes the current style.css file.

**Comment by DanielYKPan** [comment]
I consider this approach is not suitable to the picker development
