### ISSUE TITLE
Please look in to the below issue's

### ISSUE THREAD

**Issue by SidduLakkarse** [DanielYKPan/date-time-picker#280]
Hi DanielYKPan,
Could you please look in to the below issue's
1) The location, size, font, and general formatting of the calendar should be the same as it was previously?.
 2)Remove the Cancel and Set options, save the date/time when the calendar is closed?
 3)User can't only adjust the time with the up and down arrows, we want the user to be able to click into the field and manually change the time with the keyboard?

**Comment by DanielYKPan** [comment]
1) No Idea what you talked about
2) Yes
3) the up and down arrows are buttons, users could tab into the buttons and use keyboard to adjust the time. Beside, users could change the time directly from the input the picker is bound to.
