### ISSUE TITLE
[Feature] - Add the possibility to increment hour thru minute selector

### ISSUE THREAD

**Issue by astalegale** [DanielYKPan/date-time-picker#281]
Hi, thanks for this datetime picker module!

I wonder if is possible to increment the hour when reach the max or the minimum (59,0).
Currently the component block this possibility.

Thanks
Alex

**Comment by DanielYKPan** [comment]
Update the picker to latest version.
This feature should be added

**Comment by jonathan-chin** [comment]
is this only available with 6.0.8?

any chance this feature can be added to 5.2.6 (which supports Angular 5)?

**Comment by DanielYKPan** [comment]
this  feature is available in version 6. version 5 no longer maintained.
