### ISSUE TITLE
[Feature] Being able to initially focus `to` in a range selection

### ISSUE THREAD

**Issue by scaljeri** [DanielYKPan/date-time-picker#283]
When you open the range selection dialog, it always selects `from`. It would be nice to be able to focus `to` programatically. In my case I sometimes already have a `from` date, but not a `to`, in which case it would make more sense to initially give focus to the `to`. Hope this makes any sense :)

Cheers

**Comment by DanielYKPan** [comment]
It made sense.

**Comment by DanielYKPan** [comment]
The latest version now has two new selectMode: 'rangeFrom' and 'rangeTo'.

'rangeFrom' would only shows 'from' value in the input and the picker could only selects 'from' value.
'rangeTo' would only shows 'to' value in the input and the picker could only selects 'to' value.

you could learn more about this from the demo page.
