### ISSUE TITLE
The picker changes the day I choose because of GMT

### ISSUE THREAD

**Issue by dobrinsky** [DanielYKPan/date-time-picker#284]
This is a really nice DateTime picker that actually works (i.e. binds it to the the object behind).

The problem I am facing is that it changes the date I choose to -1 on the server.

If I pick 2/28/2018,

![image](https://user-images.githubusercontent.com/21820290/36797172-ffee3f26-1caf-11e8-9031-21c757cf4d13.png)

 on the server it goes to

![image](https://user-images.githubusercontent.com/21820290/36797199-0d656f58-1cb0-11e8-9cda-d545de3702d7.png)

I have tried changing the localization, but it does not work.

The solution is to add 3 Hours on the server side and it works, but that is ugly...I was thinking maybe there is another solution.

P.S. It is pretty slow on older computers.

Thank you!
Andrei Dobrin

**Comment by DanielYKPan** [comment]
The reason why the server has the a -1 date is because the server has a different GMT value.
You may have to adjust your GMT value in your server side code.
This is not a issue from the picker.

**Comment by dobrinsky** [comment]
What I was trying to say is this:

If you could please add an option for the picker not to change the GMT, to get the standard one (as do most of the pickers). Because changing the GMT on the server is not an option always. e.g. when the server is owned by a client and I cannot ask for this since it would impact other applications.

Moreover, by adding the option to not set the GMT in Angular, would speed up the showing of the picker.

If what I wrote above is not possible maybe an option to set the time for the calendar pickerType to 12 in the afternoon which would not decrease a day on the server is possible?

It was a development request. Sorry for not pointing it out.

**Comment by DanielYKPan** [comment]
On your Javascript Code, you could adjust the date time GMT before sending data your server.
Adjusting the GMT in the picker would make the picker very complicated.

The picker does not set the GMT. Because the javascript `new Date()` would create a Date object with GMT relative to your client location.
