### ISSUE TITLE
There is no event listener for owl-date-time-inline

### ISSUE THREAD

**Issue by siyavash4812** [DanielYKPan/date-time-picker#286]
The title is self explanatory. I think there should be an event that gets called whenever user clicks on a date.

**Comment by DanielYKPan** [comment]
What event are you looking for?

**Comment by SupriyaSudhindra** [comment]
As @siyavash4812 ...there are no events like change/selectdate etc...Please can you update on events just like 'dateTimeChange'/'dateTimeInput' that are there for  input[owlDateTime]..

**Comment by szilardd** [comment]
use `ngModelChange`

`<owl-date-time-inline (ngModelChange)="onChange($event)"></owl-date-time-inline>`
