### ISSUE TITLE
Ho to set date format to dd/mm/yyy

### ISSUE THREAD

**Issue by ketanmokariya** [DanielYKPan/date-time-picker#287]
Hi ,

I want to set date format to dd/mm/yyyy but i couldn't. All the time i am getting mm/dd/yyyy format. How i can change date format please help me out. 

Thanks,
Ketan Mokariya

**Comment by DanielYKPan** [comment]
https://danielykpan.github.io/date-time-picker/#locale-formats

**Comment by mluis** [comment]
Actually I'm in the same situation and a bit confused on how to set it.
I'm using moment integration and I have:

```
export const MY_MOMENT_FORMATS = {
    parseInput: 'l LT',
    fullPickerInput: 'l LT',
    datePickerInput: 'l',
    timePickerInput: 'LT',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
};
```

Already seen the moment formats on moment's documentation but it is not explicit on OwlDateTimePicker's documentation which key one must change to get dd/mm/yyy .
