### ISSUE TITLE
Date time is not removed when clear is called for range picker

### ISSUE THREAD

**Issue by mato-stanic** [DanielYKPan/date-time-picker#289]
In current project I have this setup for displaying date time picker it is separate component with following .ts and .html

```
export class DateTimeFieldComponent {
  @Input('control') dateTime: FormControl;
  @Input('min') minValue: string;
  @Input('max') maxValue: string;
  @Input('selectMode') selectMode: string;

  constructor() { }

  clearValue() {
    this.dateTime.setValue(null);
  }

}
```

```
<div class="input-group date-picker-group">
  <input class="form-control" [formControl]="dateTime"
    [owlDateTimeTrigger]="dateTimePicker" [owlDateTime]="dateTimePicker"
    [min]="minValue" [max]="maxValue"
    placeHolder="Date/Time" [selectMode]="selectMode"/>
  <div class="trigger input-group-btn">
    <button class="btn btn-default" type="button" [owlDateTimeTrigger]="dateTimePicker">
      <i class="material-icons md-16">&#xE916;</i></button>
    <button class="btn btn-default" type="button" (click)="clearValue()">
      <i class="material-icons md-16">&#xE14C;</i></button>
  </div>
</div>
<owl-date-time [pickerType]="'both'" #dateTimePicker></owl-date-time>
```

This code works perfectly if [selectMode] is single. Form control is cleared and placeholder="Date/Time" is displayed again in input field. 
If [selectMode] is range clear is only setting formControl value to null, but input field is not cleared. 

![screenshot_20180308_100101](https://user-images.githubusercontent.com/11602021/37142186-a2ea665c-22b7-11e8-835d-cd804c35f123.png)

I have tried changing clearValue function to following:
```
clearValue() {
    this.dateTime.setValue([null, null]);
  }
```
That one sort of worked date time values are clear from input field but Separator remains.
![screenshot_20180308_100334](https://user-images.githubusercontent.com/11602021/37142301-fd7edeae-22b7-11e8-81f9-dff43fb1d3c5.png)

I am not sure if I am doing something wrong or this may be a bug. 
Thank you for response.

**Comment by DanielYKPan** [comment]
It should be fixed in the latest version.
