### ISSUE TITLE
Seconds selection on time

### ISSUE THREAD

**Issue by vladwoguer** [DanielYKPan/date-time-picker#29]
Is there a way to allow the time picker to entry the seconds?

**Comment by DanielYKPan** [comment]
@vladwoguer 
No, 
but I would add an option to show a second slider in the time picker.

Thanks

**Comment by DanielYKPan** [comment]
@vladwoguer 
Update to the latest package.

Use **[showSeconds]=" true "**, and it would show a slider for configuring second value in time picker.

**Comment by vladwoguer** [comment]
OK, thank you :1st_place_medal:

**Comment by vladwoguer** [comment]
Could you publish the change on npm?

**Comment by DanielYKPan** [comment]
It had been updated

**Comment by dland512** [comment]
For anyone seeing this, you can use this property:

`[showSecondsTimer]="true"`

and you will get a third box for entering the seconds in the time area.
