### ISSUE TITLE
CHOOSE ONLY MONTH

### ISSUE THREAD

**Issue by Hamzabelrhazi** [DanielYKPan/date-time-picker#291]
I want to choose only the month of the year please help me

**Comment by naveenr2112** [comment]
Is it possible to select only Month?

**Comment by DanielYKPan** [comment]
No

**Comment by MFateen** [comment]
This is available in version 6
check the example by @DanielYKPan here
https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker?file=src%2Fapp%2Fyear-month%2Fyear-month.component.ts

**Comment by robertIsaac** [comment]
> This is available in version 6
> check the example by @DanielYKPan here
> https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker?file=src%2Fapp%2Fyear-month%2Fyear-month.component.ts

this link isn't working anymore
