### ISSUE TITLE
[BUG] Range is not shown correctly when set from end of year to beginning of next year

### ISSUE THREAD

**Issue by fhinderer** [DanielYKPan/date-time-picker#292]
Hi,

I noticed an issue while using the range function. When the range begins in one year and ends in another year, the connection between those years (months) is not shown correctly.

Please have a look at the provided screenshot. This can easily be reproduced on the demo page.
In this case December should be selected as well, as the range ends in January.

<img width="545" alt="range_issue" src="https://user-images.githubusercontent.com/37187329/37162779-65ac40e6-22f6-11e8-944f-701ad779b306.png">

Thanks!

Best regards,
Fabian

**Comment by DanielYKPan** [comment]
The bug should be fixed in the latest version.
