### ISSUE TITLE
Add a faster way to pick year or add ability to customize template

### ISSUE THREAD

**Issue by Maden-maxi** [DanielYKPan/date-time-picker#296]
It would be very comfortable to have a two dropdowns(selects) with month and year like this
http://joxi.ru/a2XD7pRTyG5xl2

**Comment by alexsintoni** [comment]
I agree, in particular this feature would be great in case of selecting birthdays.
At the moment it takes too long to select a date 20/30 years ago.

Another option would be to extend the feature "Setting the calendar start view" (described here https://danielykpan.github.io/date-time-picker/) to show also the last 20 years and not only the month list

**Comment by DanielYKPan** [comment]
I see. I am working on it, and try to have a better UI to let user select years.

**Comment by DanielYKPan** [comment]
Update to the picker version 5.2.2

There is a year list which allows user to select a specific year quicker.

**Comment by Maden-maxi** [comment]
Oh sorry! But it steel not so comfortable.

**Comment by alexsintoni** [comment]
I think that the new version is pretty good. Thanks a million for the quick update

**Comment by Maden-maxi** [comment]
@alexsintoni I agree, with new version datepicker UI became is very cool but I think feature with pick month as such as year will be very useful)
