### ISSUE TITLE
It is not translating correctly the time coming from Jackson, so the Time is set to 00:00 in Input

### ISSUE THREAD

**Issue by eduardoalcantara** [DanielYKPan/date-time-picker#298]
I receive from Jacson JSON (Spring Boot): 2018-03-22T22:00:00.000
It displays in the box: 22/3/2018 00:00

I am using the OwlMomentDateTimeModule module, following your procedure at https://danielykpan.github.io/date-time-picker/#locale-formats

**Comment by eduardoalcantara** [comment]
Also can't set the timezone, so when I put 19:00 I get stored n db 22:00 (+3 hours) I am in -3gmt

**Comment by DanielYKPan** [comment]
Your might consider to use [StackBlitz](https://stackblitz.com/) to create demo to re-generate the issue.
Otherwise no way to debug

**Comment by DanielYKPan** [comment]
I would close this for now

**Comment by eduardoalcantara** [comment]
Ok, thank you.
