### ISSUE TITLE
Can't format date with [viewFormat]

### ISSUE THREAD

**Issue by run1t** [DanielYKPan/date-time-picker#3]
Hello,
I tried your module and it's working well thanks :+1: 
Now I try to format my date with `[viewFormat]="dddd"`, unfortunately I's not  working.
I'm using webpack. So maybe I miss something somewhere ...
Can you help me figure it out ? 

Thanks,

**Comment by DanielYKPan** [comment]
@run1t 
Hi,
If you want to format you date, that means you want to get a string from date-time-picker. So you have to set the [returnObject] = " 'string' ".(set it as **" 'string' "** not **"string"**, don't forget the single quote inside the double quote);
PS: 'dddd' is not a valid momentJS format. You might try 'DDDD'.

Hope this helps!!!

**Comment by run1t** [comment]
hi,
I did try what you say and indeed I did forget the single quote, but behind that it's not working and I really can't understand why. By the way the I got the `'dddd'` from the  official momentJs documentation:
```
Format Dates
moment().format('MMMM Do YYYY, h:mm:ss a'); // January 22nd 2017, 11:10:53 pm
moment().format('dddd');                    // Sunday
moment().format("MMM Do YY");               // Jan 22nd 17
moment().format('YYYY [escaped] YYYY');     // 2017 escaped 2017
moment().format();                          // 2017-01-22T23:10:53+01:00
```
Thank's for your help and sorry for the response time.
Ps: I'll try to provide you a peace of code tomorrow.

**Comment by DanielYKPan** [comment]
@run1t 
Can you please tell me how it is not working, maybe show me your console respond or did you try any other format like('MMMM') or others?
