### ISSUE TITLE
Selection of year doesn't work

### ISSUE THREAD

**Issue by ericasenn** [DanielYKPan/date-time-picker#30]
When I try to select a year it doesn't work. The selection only works if I select the year using the arrows of the calendar.

**Comment by DanielYKPan** [comment]
@ericasenn 
When you select a year, the picker wouldn't return the date, but would show the calendar of that year. you have to select a date from that year, and the picker would return the date of that selected year.

**Comment by ericasenn** [comment]
You're right! 
Thanks!!
