### ISSUE TITLE
Date-time-picker cancel and set button action not working

### ISSUE THREAD

**Issue by sunojgeniocode** [DanielYKPan/date-time-picker#300]
Trying to integrate date-time-picker module in angular5 cli project. When i click on calendar will present but no action will happen when click on Cancel/ Set button in the bottom. please help

**Comment by DanielYKPan** [comment]
Your might consider to use [StackBlitz](https://stackblitz.com/) to create a demo to re-generate the issue.

Without any demo to show the issue, I would not answer any question.
I would close this for now.

**Comment by sunojgeniocode** [comment]
Sharing the sample project link.

https://stackblitz.com/edit/angular-cicas4

Current project using angular 5.0.1

**Comment by sunojgeniocode** [comment]
When i upgrade to 5.2.8 its all working fine, thanks for your kind support
