### ISSUE TITLE
How can i disable past dates in date calender

### ISSUE THREAD

**Issue by prakash403** [DanielYKPan/date-time-picker#301]
Hai how can i disable past dates in ngpickdate time .  Now all dates are enable

**Comment by DanielYKPan** [comment]
please read the demo page and README.md. There are examples and explanation.

**Comment by prakash403** [comment]
Yes i can read  but not working i get all dates how can i get minimum date as today date
and maximum dates today plus 2 days

**Comment by prakash403** [comment]
I am totally confused
