### ISSUE TITLE
Set the Time as IST time 

### ISSUE THREAD

**Issue by prakash403** [DanielYKPan/date-time-picker#302]
How to set the time as timezone as IST time in this library

**Comment by DanielYKPan** [comment]
The picker timezone is set to the user's locations. If you want to use different timezone, you could adjust the date time value from the picker in your own javascript code.

**Comment by prakash403** [comment]
Not possible to set please share the example i want to set the timezone as IST

**Comment by prakash403** [comment]
In Date time picker Default takes a System time . Is there Any possibility to set as IST in the given examples and lib

**Comment by DanielYKPan** [comment]
There is no example about this, because the picker dose not do any timezone setting. It simply returns a native Javascript Date object (if you uses OwnMomentDateTimeModule, it returns MomentJS object). You have to adjust the value coming from picker to your desire timezone.

**Comment by prakash403** [comment]
Yes , I am new  thats why how can i set  IST in OwnMomentDateTimeModule

**Comment by prakash403** [comment]
Hai how to set time zone America .. providers:[{ provide: OWL_DATE_TIME_FORMATS, useValue: MY_NATIVE_FORMATS },
    { provide: OWL_DATE_TIME_LOCALE, useValue: 'en' },
    { provide: OWL_DATE_TIME_FORMATS, useValue: MY_MOMENT_FORMATS },
    { provide: OwlDateTimeIntl, useValue: DefaultIntl },
    { provide: OWL_DATE_TIME_FORMATS, useValue: CUSTOM_DATE_TIME_FORMATS },

**Comment by prakash403** [comment]
Hai
