### ISSUE TITLE
Displaced view with normalize.css

### ISSUE THREAD

**Issue by MaKCbIMKo** [DanielYKPan/date-time-picker#304]
In case if you're using [nnormalize.css](https://necolas.github.io/normalize.css/) - it breaks the view of the component (fonts and timepicker controls are displaced).

I'm fine with different fonts and font sizes. But displaced controls - looks ugly (and hard to click).

**Comment by DanielYKPan** [comment]
my demo page is used normalize.css, and it works fine.

If you still have the issue, your might consider to use [StackBlitz](https://stackblitz.com/) to create a demo to re-generate the issue.

I would close this for now.
