### ISSUE TITLE
How to set Timezone  USA  in the Ng date time picker 

### ISSUE THREAD

**Issue by prakash403** [DanielYKPan/date-time-picker#306]
I am using your example  All are working fine But  I read Readme.md for your code i build  sucessfully get the output as take the date and time from system locale my requirement is how to set the Timezone as Dubai in date time picker I am struck from past 3 days onwards.  i am using your lib https://github.com/DanielYKPan/date-time-picker >please help

**Comment by DanielYKPan** [comment]
Yes the date time  value from the picker  is from system locale.
If you want to change the value to different time zone, you have to modify the value in your own javascript code once you get the value from the picker.

**Comment by prakash403** [comment]
Already i tried sir How it possible i am new to angular please  hlp

**Comment by prakash403** [comment]
you have any example please share it
