### ISSUE TITLE
How to set Timezone Singapore in the Ng date time picker

### ISSUE THREAD

**Issue by prakash403** [DanielYKPan/date-time-picker#307]
Yes the date time value from the picker is from system locale.

How can i set the other timezone in javascript Please share any example I am struck .  I want to change to  Singapore date time . I am getting the from system locale Please help

**Comment by DanielYKPan** [comment]
This is place to report issue, you may consider to use other platform such as [Stackoverflow](https://stackoverflow.com/) to ask from help
