### ISSUE TITLE
dateFormat as with previous versions

### ISSUE THREAD

**Issue by piotrratajczak** [DanielYKPan/date-time-picker#308]
Hi, 
I've read info about format/localization - multiple times - still can't figure out how to obtain results similar to those (v.5.0-beta):
 <owl-date-time
          ...
          [dateFormat]="'DD.MM.YYYY'"
          ...
</owl-date-time>

...
 <owl-date-time
          ...
          [dateFormat]="'YYYY/MM/DD'"
          ...
</owl-date-time>

Could you please show an example with two diffrent date formats? Or maybe it can be change dynamically?

**Comment by DanielYKPan** [comment]
There are examples on the demo pages
