### ISSUE TITLE
Can't reset form input with selectMode 'range' using formcontrol reset

### ISSUE THREAD

**Issue by cannibalcow** [DanielYKPan/date-time-picker#310]
When I try reseting the form with form.reset() and the 'selectMode' is 'range' the input value will not reset.
The selectMode 'single' works. 

`<label for="dateBestFrom" class="form-label text-nowrap">Date from - to</label>
          <input name="dateBestFrom" formControlName="dateRange" [owlDateTime]="dateBestFrom" placeholder="YYYY-MM-DD ~ YYYY-MM-DD"
            [owlDateTimeTrigger]="dateBestFrom" class="form-control" [selectMode]="'range'">
          <owl-date-time [firstDayOfWeek]="'1'" [pickerType]="'calendar'" #dateBestFrom></owl-date-time>`

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to show the issue.

I would close this until there is a demo to show the issue.

**Comment by cannibalcow** [comment]
Here is a demo of the issue

https://stackblitz.com/edit/angular-quu9nr

**Comment by DanielYKPan** [comment]
@cannibalcow 
Thanks for reporting the issue. 
The issue should be fixed in the latest version of the picker

Here is the [demo](https://stackblitz.com/edit/angular-i7ykf5) to show the issue been fixed.

**Comment by cannibalcow** [comment]
Thanks, will try it out today!

**Comment by DanielYKPan** [comment]
@SIlver-- 
Thanks for the report.

The latest version should be fixed the issue.

[Demo](https://stackblitz.com/edit/angular-a5sgpz)
