### ISSUE TITLE
Conditionally add or remove selectMode

### ISSUE THREAD

**Issue by kyleabens** [DanielYKPan/date-time-picker#311]
I need to conditionally add and remove selectMode on my input field because depending on the type of event that's selected it can change from range to a single date.  Is there a way to do this that I'm just not aware of?  I was hoping something like the below example would work but it looks like once selectMode is added there is no way to remove the attribute.

```
<div class="form-group">
      <label>Start Date</label>
      <input 
        class="form-control"
        [owlDateTimeTrigger]="startDate" 
        [owlDateTime]="startDate"
        [(ngModel)]="selectedMoments"
        [selectMode]="type.value == 'Range' ? 'rangeFrom' : null"
        formControlName="start"
        name="start"
        placeholder="Select a Start Date">
      <owl-date-time [hour12Timer]="true" #startDate></owl-date-time>
    </div>
```

**Comment by DanielYKPan** [comment]
selectMode could not be set to null. If you want it to be single, set it 'single'.

In addition, use [StackBlitz](https://stackblitz.com/) to show the issue. And I would close this unless there is a demo example to show the issue.
