### ISSUE TITLE
ngModel binding is not working.

### ISSUE THREAD

**Issue by Tejani** [DanielYKPan/date-time-picker#312]
Hi all I am trying to bind user "dob" but it is not display in text control, I have seen through browser inspect like my control is binding below 

`<input _ngcontent-c3="" class="form-control ng-pristine ng-invalid ng-touched" ng-reflect-owl-date-time="[object Object]" ng-reflect-options="[object Object]" ng-reflect-dt-picker="[object Object]" aria-haspopup="true" ng-reflect-model="09/26/1975">`

Model bind
`[(ngModel)]="model.dob"`

I have seen my expected value from `ng-reflect-model="09/26/1975"`  but in my HTML it was showing null can you please provide solution,

**Comment by DanielYKPan** [comment]
This is place to report issue, you may consider to use other platform such as [Stackoverflow](https://stackoverflow.com/) to ask from help
