### ISSUE TITLE
How do I set the date-time-picker to display 24 hour format?

### ISSUE THREAD

**Issue by toddhd** [DanielYKPan/date-time-picker#317]
Ultimately I'd like the date and time format to display similar to:

2018-4-3 13:00:00

And not shot AM/PM

**Comment by DanielYKPan** [comment]
Check out the demo page [Demo](https://danielykpan.github.io/date-time-picker/#locale-formats)

**Comment by atejadac** [comment]
Daniel, do you have a working example of it? I can't seem to understand the demo you reference everytime someone asks about this topic. I, as @toddhd , am trying to display the time in the timepicker as a 24 hour format.

Thank you in advance.

**Comment by divya130** [comment]
hi , even i have to display in 24 hour format did any one got solution ?
