### ISSUE TITLE
UX: Allow change of only end date

### ISSUE THREAD

**Issue by shyamal890** [DanielYKPan/date-time-picker#319]
On selection of range, even if the `end date` input is selected/focused (blue color) and the click on calendar is beyond the `end date`, `start date` is set currently instead `end date` should modified since the `end date` is focused/selected and the day selected is after the `end date`.

**Usecase:**
Imagine range is of 3 months. Currently it resets the range on day selection on calendar when I only wanted to change the `end date`.

**Comment by shyamal890** [comment]
@DanielYKPan any thoughts on this?

**Comment by DanielYKPan** [comment]
There is a selectMode option to set the calendar as rangeFrom or rangeTo
