### ISSUE TITLE
after updateing  ng-date-timepicker  Error: core_1.InjectionToken is not a constructor.

### ISSUE THREAD

**Issue by ashwinirajput** [DanielYKPan/date-time-picker#32]
(index):36 Error: core_1.InjectionToken is not a constructor
  Evaluating http://localhost:888/node_modules/ng-pick-datetime/lib/translations.js
  Evaluating http://localhost:888/node_modules/ng-pick-datetime/lib/dialog.component.js
  Evaluating http://localhost:888/node_modules/ng-pick-datetime/lib/picker.directive.js
  Evaluating http://localhost:888/node_modules/ng-pick-datetime/lib/picker.module.js
  Evaluating http://localhost:888/node_modules/ng-pick-datetime/index.js
  Evaluating http://localhost:888/app/app.module.js
  Evaluating http://localhost:888/app/main.js
  Loading app
    at Object.eval (translations.ts:15)
    at eval (translations.ts:29)
    at eval (translations.ts:29)
    at eval (<anonymous>)
    at evaluate (evaluate.js:106)
    at instantiate.js:354
    at dynamicExecute (register-loader.js:686)
    at doEvaluate (register-loader.js:633)
    at ensureEvaluate (register-loader.js:542)
    at register-loader.js:562
    at Object.eval (dialog.component.ts:10)
    at eval (dialog.component.ts:239)
    at eval (dialog.component.ts:239)
    at eval (<anonymous>)
    at evaluate (evaluate.js:106)

**Comment by DanielYKPan** [comment]
what version, environment you are running

**Comment by ashwinirajput** [comment]
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/common": "2.4.9",
    "@angular/compiler": "2.4.9",
    "@angular/compiler-cli": "2.4.9",
    "@angular/core": "2.4.9",
    "@angular/forms": "2.4.9",
    "@angular/http": "2.4.9",
    "@angular/platform-browser": "2.4.9",
    "@angular/platform-browser-dynamic": "2.4.9",
    "@angular/platform-server": "2.4.9",
    "@angular/router": "3.4.9",
    "core-js": "2.4.1",
    "intl": "^1.2.5",
    "ng-pick-datetime": "^4.0.7",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.3.0",
    "systemjs": "0.20.12",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@types/node": "7.0.8",
    "concurrently": "3.4.0",
    "lite-server": "2.2.2",
    "rollup": "0.41.6",
    "rollup-plugin-commonjs": "8.0.2",
    "rollup-plugin-node-resolve": "3.0.0",
    "rollup-plugin-uglify": "1.0.1",
    "typescript": "2.3.0"
  }
}

**Comment by DanielYKPan** [comment]
Please follow the README example

**Comment by AllenDigital** [comment]
Can you explain the issue here? I've got the same problem when updating and cannot see any missed steps in the README.

**Comment by DanielYKPan** [comment]
@AllenDigital 
@ashwinirajput 
The problem exists because angular 2 dose not have InjectionToken. Angular 2 only has OpaqueToken, which was marked as deprecated. In angular 4, InjectionToken was introduced.

Try to update you angular version to 4.0.1
Here is a [quick start](https://angular.io/docs/ts/latest/guide/setup.html) from angular official.

**Comment by ashwinirajput** [comment]
@DanielYKPan my application run on angular2 and I don't want to upgrade.

**Comment by ashwinirajput** [comment]
@AllenDigital can you figure out this issue I am haveing the same.

**Comment by AllenDigital** [comment]
OK, I must be getting confused here because in the README it says:

"This package now supports Angular 2 and 4"

But looking at your comment it appears only Angular 4 is supported?

**Comment by DanielYKPan** [comment]
@AllenDigital 
Sorry Allen, I forgot to update the README.

**Comment by bruteforce** [comment]
Please update npm url as well.
https://www.npmjs.com/package/ng2-date-time-picker
"This package currently only supports AngularJS 2. If the package running on AngularJs 4, it will appears bugs because Angular 4 move its animation to its own module. Those bugs will be fixed in the next updates"

**Comment by gana280992** [comment]
Dear @DanielYKPan . Is this package will support for angular2 or not? Sorry i didn't get clarity on above discussion about the package supports in which version. I am using angular2.  I am getting the same InjectionToken error so that i have replace InjectionToken into OpaqueToken, the error gets solved but some other issues raised. If it supports angular2 version then kindly give me the example to implement the same.

**Comment by DanielYKPan** [comment]
@gana280992 
Only supports Angular 4

**Comment by GurpreetSandhar** [comment]
ERROR in node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(13,44): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(14,46): error TS1039: Initializers are not allowed in ambient contexts.

**Comment by toddhd** [comment]
I am getting the same error message as GunpreetSandhar - Initializers are not allowed in ambient contexts.
