### ISSUE TITLE
Setting min date to current date doesn't let me select current date

### ISSUE THREAD

**Issue by shobhitvaish** [DanielYKPan/date-time-picker#321]
Hi,

**Issue** - Setting min date to current date doesn't let me select current date

**Code**
`<owl-date-time-inline formControlName="selectedDate" [min]="minDate" [pickerType]="'calendar'"></owl-date-time-inline>`
`minDate: Date = new Date();`

**Date 6th Apr 2018 is not clickable**

![image](https://user-images.githubusercontent.com/24998910/38421642-6a6d24fc-39c5-11e8-8b43-be228749879f.png)

Could you please help?

**Comment by DanielYKPan** [comment]
This is because the `new Date()` function includes the time value.
You have to set the min date like this `new Date(Y, M, D)`

**Comment by ayazdink** [comment]
You need to set the min to current date with 0 hour, 0 minute and 0 second

**Comment by FahimHassanMollah** [comment]
This is because the new Date() function includes the time value.
You have to set the min date like this new Date(Y, M, D)
example : 
 public expiryDateMin = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
