### ISSUE TITLE
Manual entry in the input field for date and time format validation dd/mm/yyyy hh:mm:ss not working

### ISSUE THREAD

**Issue by kargoms** [DanielYKPan/date-time-picker#322]
i have set the datetimepicker format with OwlMomentDateTimeModule as 'dd/mm/yyyy hh:mm:ss' which works fine but while manual entry in the input field associated with the datetimepicker is not working and always picker is setting to 'mm/dd/yyyy' format. please provide any suggestion on this.

**Comment by DanielYKPan** [comment]
Please use StackBlitz](https://stackblitz.com/) and build a live demo to show the issue.

Until then, I would close this issue.

**Comment by kargoms** [comment]
Hi,

I have created the sample app here : [code](https://stackblitz.com/edit/angular-2nocnz)

when i click on the icon text i get the DD/MM/YYYY HH:mm:ss format from the datetime picker but the same format when i edit in the input box then the datetime picker is always setting to MM/DD/YYYY format. I need DD/MM/YYYY HH:mm:ss format on manual entry as well from the datetimepicker also. Please help on this.

**Comment by DanielYKPan** [comment]
Here is your correct version [code](https://stackblitz.com/edit/angular-vvp849?file=app/app.module.ts).

**Comment by kargoms** [comment]
tell him thanks a lot for your help it works fine :)

**Comment by kargoms** [comment]
Hi Daniel,
i want to show error message when incorrect datetime format is entered manually. Please help on this
Here is sample code link `https://stackblitz.com/edit/angular-vvp849`
