### ISSUE TITLE
ERROR TypeError: Cannot read property 'isInSingleMode' of undefined

### ISSUE THREAD

**Issue by viethoanganh79** [DanielYKPan/date-time-picker#323]
i using pickertype is calendar and builder show error

> HomeComponent.html:27 ERROR TypeError: Cannot read property 'isInSingleMode' of undefined
>     at OwlDateTimeComponent.set [as pickerType] (date-time-picker.component.js:94)
>     at updateProp (core.js:12601)....

if i dont use picker type, it dont show error

**Comment by DanielYKPan** [comment]
Use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about

I would close this until it is confirmed as an issue

**Comment by cevc96** [comment]
I have the same problem, some solution for this?

**Comment by WindSaber** [comment]
@cevc96  Just be sure that the <owl-date-time> is before your input and in the same dom component

**Comment by badkicker** [comment]
same issue here. I am using time picker in ngFor in my app

**Comment by WindSaber** [comment]
@badkicker  Try swaping position bwtween directive and input as @viethoanganh79  suggests...that worked for me in past
