### ISSUE TITLE
defaultMoment not synching with current time

### ISSUE THREAD

**Issue by shirsht** [DanielYKPan/date-time-picker#327]
Hi,
When I use a timer with a default starting moment, it opens up fine to the time I set up. When I try to change the time with the arrow keys, it immediately changes to the current time. 
My code:

```
<owl-date-time #timerFrom [type]="'timer'"
                                   [dateFormat]="'HH:mm'"  name="timerFrom" dir="ltr"
                                    [inputId]="'input3'" [defaultMoment]="startAt"></owl-date-time>


startAt: Date = new Date(2019, 2, 15, 12, 0);
```

**Comment by DanielYKPan** [comment]
Please refer to README and the demo page.

There to no defaultMoment
