### ISSUE TITLE
feature request: is there a way to remove the last row of the date picker UI ? 

### ISSUE THREAD

**Issue by sonusRepo** [DanielYKPan/date-time-picker#328]
currently, when we open the datepicker, and if the month is , let's say 'march' of 2018, 
the last row will show days from next month, that is 1 to 7th of april 2018, is there any way I can remove this? thank you in advance. This is one of the best datepickers i have ever used, thank you for the amazing work

**Comment by DanielYKPan** [comment]
Update the picker to latest version

Added [hideOtherMonths] to `owl-date-time` and `owl-date-time-inline`
