### ISSUE TITLE
Does not understand date from input field

### ISSUE THREAD

**Issue by TomasAndersen** [DanielYKPan/date-time-picker#329]
I have set locale to nb (norwegian bokmal). When combining an input field with an icon I am able to choose a date from the picker (eg. 19.april 2018). The input field is then updated with 19.4.2018 (ie DD.MM.YYYY, as is the preferred norwegian date format). When I try to edit the date, lets say I modify 19 to 20 instead, the component does not understand the new format.. this is an invalid date.. if I change the text to 04.19.2018 instead the date is interpretered correctly. This must clearly be some kind of error?

**Comment by DanielYKPan** [comment]
Please consider to use the OwlMomentDateTimeModule as it let MomentJs to handle the locale.
Sometimes Native Javascript Date does weird thing.

**Comment by TomasAndersen** [comment]
Thanks, switching to MomentJs really helped!
