### ISSUE TITLE
Locale not working when calling programmatically

### ISSUE THREAD

**Issue by scssat** [DanielYKPan/date-time-picker#331]
ISSUE 1:
When I call the date-time-picker programmatically I cannot get locale to work. I have tried to import moment/locale/nb, but it still does not work.`  
open() {
    this.timeOpen = true;
    const amazingTimePicker = this.atp.open({
      locale: 'nb',
      time: this.medication.timeFirstDose,
      theme: 'dark',
      arrowStyle: {
        background: 'white',
        color: 'blue'
      }
    });
    amazingTimePicker.afterClose().subscribe(time => {
      this.medication.timeFirstDose = time;
    });
    this.timeOpen = false;
  }
`

**Comment by DanielYKPan** [comment]
Use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about

I would close this until it is confirmed as an proper issue.

**Comment by scssat** [comment]
I agree, since I do not believe it's something wrong with the control...but I have followed U'r recipe fro A to Z. Do U have any sort advice, will be very appreciated. I have probably overlooked something obvious...
