### ISSUE TITLE
Skip year select

### ISSUE THREAD

**Issue by kasskata** [DanielYKPan/date-time-picker#333]
In last version doesn't have years select dialog option. Can I skip that year view ?

**Comment by DanielYKPan** [comment]
No.
That is how you select a date if you want to change the year value.

**Comment by kasskata** [comment]
Don't want to change year value. only months and get current year value. Is that possible?

**Comment by DanielYKPan** [comment]
Then you just choose the current year, then choose the month

**Comment by kasskata** [comment]
Ok, thanks, sorry for bother.
