### ISSUE TITLE
Open date-time-picker on tab key

### ISSUE THREAD

**Issue by v2amruta** [DanielYKPan/date-time-picker#335]
I want to open date-time-picker when we are going to textbox using tab key.

**Comment by DanielYKPan** [comment]
Here are the keyboards shortcuts to handle the picker:
ALT + DOWN_ARROW -- Open the picker
ESCAPE -- Close the picker

If u still prefer to using tab to open the picker, you could assign owl-date-time to a web variable like this:
`
<owl-date-time #dt='owlDateTime'></owl-date-time>
`
And use OwlDateTimeComponent.open() and OwlDateTimeComponent.close() in your tab function.

**Comment by kargoms** [comment]
Hi Daniel,

How to select the date and time using the keyboard? With ALT + DOWN_ARROW  i am able to open the picker but how do i select the date and time from the picker using the keyboard keys. Could you please provide any solution on this.
