### ISSUE TITLE
Unable to see year view in date-time-picker

### ISSUE THREAD

**Issue by v2amruta** [DanielYKPan/date-time-picker#336]
Following is the image of date-time-picker with year view which is shown on click of arrow besides month-year view. Get this from https://danielykpan.github.io/date-time-picker/

![date-time-picker-no-year-view](https://user-images.githubusercontent.com/12995140/39176900-9a4549fc-47cb-11e8-9d57-e6fefde99f20.PNG)

In my case, it is showing me month view instead of year view after click on month-year view. What i have to do to see year view???

**Comment by DanielYKPan** [comment]
No idea what your said above.

There are three startView in the picker 'month'(default), 'year' and 'multi-year'. And every time you click on the arrow, it would show the multi-year to allow user to select the desired year, and then picker would navigate to the 'year' view to allow user to select the desired month and then back the month view you selected.

**Comment by v2amruta** [comment]
Thank you DanielYKPan!!!!  Now i am able to see arrow and multi-year view as well after upgrading this package to version 5.2.6.
