### ISSUE TITLE
Make locale for Romanian

### ISSUE THREAD

**Issue by CriPstian** [DanielYKPan/date-time-picker#34]
Hello, 
as you suggest in the Readme I am creating an issue for adding the full locale translation for the ones not found in the `momentjs` package, so here it is, if I let something out please let me know.
This is a suggestion of how I think it should look like. Hope it helps. 
```TypeScript
/**
 * ro - Romanian
 */

export const LANG_RO_TRANS = {
    'time picker': 'Selector Timp',
    'today': 'Astăzi',
    'set time': 'Setează Ora',
    'close': 'Închide',
    'confirm': 'Confirmă',
    'hour': 'Oră',
    'minute': 'Minut',
    'second': 'Secondă',
};
```

Have a great evening

**Comment by DanielYKPan** [comment]
@CriPstian 
Thanks man.
