### ISSUE TITLE
Error using with angular 5

### ISSUE THREAD

**Issue by sidsamant** [DanielYKPan/date-time-picker#343]
ng-pick-datetime@5.2.6, angular@5.0.0

```
<input [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1" placeholder="Date Time">
                                <owl-date-time #dt1></owl-date-time>
```
Following error occurs in Chrome console:
`Uncaught Error: Template parse errors:
Can't bind to 'owlDateTime' since it isn't a known property of 'input'`

Related issue #228

**Comment by DanielYKPan** [comment]
this is because you haven't implemented the OwlDateTimeModule into your app.

This is not an issue from the picker and please use other platforms to ask general questions about Angular

**Comment by DanielYKPan** [comment]
Pleas use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by sidsamant** [comment]
It worked after I exported the plugin modules in my shared module. Sorry for the trouble and Thanks

**Comment by xkLander** [comment]
For me it worked like a charm, first it did not but then I had to remove it from the main app module and at it to the module where the specific components belonged. Entirely my fault.

**Comment by thurimerla** [comment]
Hi @sidsamant  and @xkLander ,

I am also facing same issue in my **Ionic Application**, Could you please tell me what you did to remove this error.
I'm getting this error.

**Error**: Template parse errors:
Can't bind to 'owlDateTimeTrigger' since it isn't a known property of 'input'. 
("/ion-label><input placeholder="Date Time:" [(ngModel)]="dateTime" [ERROR ->][owlDateTimeTrigger]="dt" [owlDateTime]="dt">
<owl-date-time #dt></o"): ng:///ConsumerTicketPageModule/ConsumerTicketPage.html@218:87

Can't bind to 'owlDateTime' since it isn't a known property of 'input'.
 ("<input placeholder="Date Time:" [(ngModel)]="dateTime" [owlDateTimeTrigger]="dt" [ERROR ->][owlDateTime]="dt"><owl-date-time #dt></owl-date-time>
"): ng:///ConsumerTicketPageModule/ConsumerTicketPage.html@218:113
'owl-date-time' is not a known element:

Thanks in Advance and sorry for my bad English.

Please give me reply.

**Comment by xkLander** [comment]
Hey @thurimerla , just make sure to import the import OwlDateTimeModule and OwlNativeDateTimeModule in the correct Module that can reach your component.
import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';

Then just use it anywhere
<div>
                <mat-form-field fxFlex floatPlaceholder="never">
                  <input matInput [(ngModel)]="bestTimeToContact" placeholder="Select Date and Time" autocomplete="off"
                         [owlDateTimeTrigger]="dt" [owlDateTime]="dt">
                  <owl-date-time #dt></owl-date-time>
                </mat-form-field>

                <button mat-button (click)="chooseBestTimeToContact()">Done</button>
              </div>

            </div>

**Comment by thurimerla** [comment]
Hi @xkLander ,

I tried what you said, but still i'm getting same error.

**Comment by sidsamant** [comment]
Hi,

   I haven't done a lot of research on an experience I had with Angular 5, ng-pick-datetime@5.2.6, ng-pick-datetime-moment@1.0.5 .

   If the parent component had [Change detection detached](https://angular.io/api/core/ChangeDetectorRef#detach)  and then subsequent [detectChanges()](https://angular.io/api/core/ChangeDetectorRef#detectChanges), would refresh the component's view.

But the DatePicker popup would not show up.

It would work if [markForCheck](https://angular.io/api/core/ChangeDetectorRef#markforcheck) is used instead.

Hope the tip works for you.

**Comment by thurimerla** [comment]
Hi @sidsamant ,

Can you share sample code ?

**Comment by trinhcanhphuc** [comment]
> Hey @thurimerla , just make sure to import the OwlDateTimeModule and OwlNativeDateTimeModule in the correct Module that can reach your component.
> import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';
> 
> Then just use it anywhere
> 
> ```
> <div>
>                 <mat-form-field fxFlex floatPlaceholder="never">
>                   <input matInput [(ngModel)]="bestTimeToContact" placeholder="Select Date and Time" autocomplete="off"
>                          [owlDateTimeTrigger]="dt" [owlDateTime]="dt">
>                   <owl-date-time #dt></owl-date-time>
>                 </mat-form-field>
> 
>                 <button mat-button (click)="chooseBestTimeToContact()">Done</button>
>               </div>
> 
>             </div>
> ```

Thank you very much.
I imported modules: "import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';" to module which includes component. It worked.

**Comment by thurimerla** [comment]
Hi @trinhcanhphuc ,

It works for me in Ionic3

Thank you very much giving reply.

Sorry for my bad English.

**Comment by profile4vaibhav** [comment]
How to print date just on console from owl-date-time picker in angular 6?

**Comment by anjaliagg10** [comment]
I am still not able to use it in my project. I have tried all solutions mentioned above. 

Error:

> ERROR Error: Uncaught (in promise): Error: Template parse errors:
> Can't bind to 'owlDateTime' since it isn't a known property of 'input'. ("
> 
>  
>           <input [ERROR ->][owlDateTime]="dt" [owlDateTimeTrigger]="dt">
>           <owl-date-time #dt></owl-date-time>

I have imported it in my app.module.ts file.

**Comment by dinumarathe** [comment]
NgModel is a angular directive that comes with the FormsModule. Getting the error means that you didn’t imported the FormsModule in your app.module.ts. Import it like below :

import { FormsModule } from '@angular/forms';

**Comment by SmoothJM** [comment]
Hi, I got a problem that "Class OwlDateTimeModule/OwlNativeDateTimeModule is not an Angular module" when I import OwlDateTimeModule and OwlNativeDateTimeModule into my NgModule. Could you please tell me how to deal with it?
