### ISSUE TITLE
AM/PM Firefox and French

### ISSUE THREAD

**Issue by marcelcandidoferreira** [DanielYKPan/date-time-picker#345]
Hi, 

I'm using the plugin with the property Hour12Timer = true.
In english/chrome the date is displayed in the input as: 05/02/2018, 12:00 AM
In french/firefox the date is displayed in the input as: 02/05/2018 à 00:00

As you can see in french/firefox it shows 24 hours format, not 12.

Can you help me?
Thanks,
Marcel

**Comment by DanielYKPan** [comment]
the property `Hour12Time` is not designed to set the date time format in the input. Instead, it set the format of the timer in the picker.

If you want to set the format for the input, please follow [this](https://danielykpan.github.io/date-time-picker#locale-formats)

**Comment by marcelcandidoferreira** [comment]
Hi Daniel again.

I'm setting the locale format dinamically dateTimeAdapter.setLocale('fr');
When I do that, the date is displayed in the input as: 02/05/2018 à 00:00
If I use 'en', then the date is displayed in the input as: 05/02/2018, 12:00 AM

I saw in the Intl.DateTime convention, something like: dateTimeAdapter.setLocale('fr-hc-h12') but it doesn't work.

Can  you help me?
