### ISSUE TITLE
Emptying input field gives invalid date

### ISSUE THREAD

**Issue by TomasAndersen** [DanielYKPan/date-time-picker#346]
Hi.

I have made a small calender picker component which is reused in several pages. I need to know if a date entered in the text field (not from the picker off course) is invalid. Ie for the value 15.15.2018 (DD.MM.YYYY) the month 15 triggers invalid. The reason for this is that I have chosen to emit the datevalue to the parent component if the value is ok, a string with the value 'invalid' if it is not valid and the value 'reset' if I reset the value.

This is my HTML code:

```
<input class="tekstboks input-liten block"
         type="text"
         [(ngModel)]="dateValue"
         (ngModelChange)="dateTime.invalid ? emitInvalid() : onDateInputChange($event)"
         placeholder="dd.mm.åååå"
         [owlDateTime]="dt1"
         #dateTime="ngModel">
<span class="label-tilleggsinfo trigger" [owlDateTimeTrigger]="dt1">
  <div class="kalenderknapp"></div>
</span>
<owl-date-time [pickerType]="'calendar'"
                 [firstDayOfWeek]="1"
                 #dt1>
  </owl-date-time>

```
I have made two methods to back up the ngModelChange event:

```
emitInvalid() {
      this.notify.emit('invalid');
  }

```
and

```
onDateInputChange(newDate: Moment) {
    console.log('this.dateValue:' + this.dateValue);

    if (newDate != null) {
      console.log('onDateInputChange date: ->' + newDate + '<-');

      if (newDate.isValid()) {
        console.log('valid date');
        this.notify.emit(this.toBackendDateString(newDate));
      } else {
        console.log('invalid date');
        this.notify.emit('invalid');
      }
    } else {
      console.log('onDateInputChange other: ->' + newDate + '<-');
      this.notify.emit('reset');
    }
  }
```

 
If I enter 15.15.2018 in the input field I see that the invalid text is emitted to my parent.
If I delete one char at a time from right to left using backspace, I see that it is emitting invalid all the way until I have deleted all but the chars '15.' as this is a valid date (or atleast start of one). If I continue to delete all chars the date is null and the dateTime.invalid resolves to false, hence valid.

If I enter 15.15.2018 in the input field and it is invalid and instead selects all the text in the input field and then press backspace all text is gone, but the dateTime.invalid expression is true.. hence invalid..
This is possibly some logical error in my code, but would be helpful for any contributions.

Also I would like to have an easier way of being able to pass on that the value is invalid...

The real problem for making things this complicated is that I have an issue with the date parameter (Moment type):
As the input text is invalid the newDate: Moment parameter resolves to **null** and I am therefore unable to differ between when I should emit reset and invalid..

Hope I made this understandable... 
If someone has found a better way of solving this I would be very grateful.

**Comment by DanielYKPan** [comment]
There are five validation errors that can be checked:
1, A value that violates the min property will have a `owlDateTimeMin` error.
2, A value that violates the max property will have a `owlDateTimeMax` error.
3, A value that violates the owlDateTimeFilter property will have a `owlDateTimeFilter` error.
4, An invalid date-time value that input has will have a `owlDateTimeParse` error.
5, If the 'from' and 'to' values in range selection are invalid ('from' value after 'to', or 'to' value before 'from'), it will have a `owlDateTimeRange` error.

You could find a segment about this (Validation Errors) in the [demo](https://danielykpan.github.io/date-time-picker/) page.

Besides, you could use [StackBlitz](https://stackblitz.com/) to build an simple app and show the issue you are mention about. That would make things clearer.

**Comment by TomasAndersen** [comment]
Hi Daniel. Thanks for pointing out the owlDateTimeParse error.

I still have an issue with the value that is fired in the event each time I type text in the input field.
I suspect that there might be an error with the validation logic in the date-time-picker component.

I have adjusted the html:

```
<input id="kalender-input"
         class="tekstboks input-liten block"
         type="text"
         [(ngModel)]="dateValue"
         (ngModelChange)="onDateInputChange($event, dateTime.invalid, dateTime.errors?.owlDateTimeParse)"
         placeholder="dd.mm.åååå"
         [owlDateTime]="dt1"
         #dateTime="ngModel">
  <span class="label-tilleggsinfo trigger" [owlDateTimeTrigger]="dt1">
    <div class="kalenderknapp"></div>
  </span>
  <owl-date-time [pickerType]="'calendar'"
                 [firstDayOfWeek]="1"
                 #dt1>
  </owl-date-time>
```

Here is the start of the typescript method triggered on ngModelChange:

```
  onDateInputChange(newDate: Moment, invalid: boolean, error: any) {
    console.log('newDate as string: ' + (!isNullOrUndefined(newDate) ? this.toBackendDateString(newDate) : 'null'));
    console.log('invalid:' + invalid);

    if (!isNullOrUndefined(error)) {
      console.log('error.text:' + error.text);
    }
    ..

  toBackendDateString(date: any) {
    const datestr = this.datePipe.transform(date, 'yyyy-MM-dd');
    return datestr;
  }

```

If I enter text in the input field I get the wrong value in the owlDateTimeParse.text field if the value is invalid. It shows the previous value instead. Let me try to explain using a scenario:

Step 1: If I enter 1 in the input field the following is logged in the console (from the method above)
newDate as string: 2018-05-01
invalid:false

Step 2: Input field value set to 15
newDate as string: 2018-05-15
invalid:false

Step 3: Input field value set to 15.1
newDate as string: 2018-05-15
invalid:false

Step 4: Input field value set to 15.15 (should be invalid)
newDate as string:null
**invalid:false**

It seems to me that the date-time-picker component does not flag invalid value in the validation logic even if the newDate value has been set to null because it cannot be interpreted.

Step 5:
If I add a . so that the text is 15.15. the following is logged in the console:
newDate as string:null   (the date is still null as it cannot be interpreted)
invalid:true (now the validation is flagging an error)
**error.text:15.15**

Notice the error.text value (it does not include the dot I entered in the input field).. 
For me it seems like the text contained in the error field is showing the previous value of the input field. 
Can it be that the date-time-picker component has some error regarding this?

I hope I managed to explain this properly..

Thank you for all help!

**Comment by TomasAndersen** [comment]
I am unable to reproduce this in StackBlitz. The same code acts differently in StackBlitz and in my application. So I guess I have to start comparing to find out why. You may close this issue then. Sorry for the inconvenience and thanks for the help.

**Comment by TomasAndersen** [comment]
Actually I found out why. According to Angular6 release notes they have modified ngModelChange to fire after value has been updated. In previous versions the update has been fired prior to value change, which then explains all this... :(
