### ISSUE TITLE
How to show seconds in input box

### ISSUE THREAD

**Issue by BosH9** [DanielYKPan/date-time-picker#347]
how to show selected seconds in the text box.?
do we need to pass any value/ format? 
for ex: i need to show as 4/1/2018, 2:11:10 AM.

![image](https://user-images.githubusercontent.com/7275569/39589734-a53f0eb2-4f1c-11e8-9c06-62dcf6adc119.png)

**Comment by DanielYKPan** [comment]
Yes, you do need to modify the default date time format.
You could read more about from [here](https://danielykpan.github.io/date-time-picker/#locale-formats)
