### ISSUE TITLE
Is native angular 6 support planned?

### ISSUE THREAD

**Issue by piecko** [DanielYKPan/date-time-picker#349]
I like this date-picker. It currently relies on cdk 5.2.0. 
After migrating my project to Angular 6, I noticed that the datepicker and its cdk-package-dep are not rxjs 6-compatible. That's most likely because of the changed imports. Currently I can use rxjs-compat to get successful builds. Are you planning to move your dependencies to version 6?
I ask, because it might potentially break compatiblity with any angular 5.

**Comment by DanielYKPan** [comment]
Yes, I am working on it.

**Comment by piecko** [comment]
You are the best

**Comment by DanielYKPan** [comment]
Updated to latest version of the picker (6.0.0)

Now it would supports Angular 6+ apps.
