### ISSUE TITLE
Can this be used with ng-bootstrap modal?

### ISSUE THREAD

**Issue by tannirum** [DanielYKPan/date-time-picker#350]
Thanks Date time picker is working fine with angular 5. But when used with ng-bootstrap modal (v2.0.0) (https://ng-bootstrap.github.io/#/components/modal/examples) the date time picker is hiding under the modal.
![date-time-picker-ng-bootstrap-modal](https://user-images.githubusercontent.com/17487258/39649233-f814c3fc-4f99-11e8-8862-094965902950.PNG)

**Comment by DanielYKPan** [comment]
@tannirum 
You need to adjust the picker's z-index in your own css/scss/sass files.

This is not an issue of the picker. I would close this.

**Comment by tannirum** [comment]
Thanks @DanielYKPan. I will add  z-index as suggested. In between I tried with Angular material dialog and it's working fine.

**Comment by tannirum** [comment]
Issue resolved after updating from z-index:1000 to z-index:1999 !important in picker.min.css
