### ISSUE TITLE
problem when integrate with bootstrap modals

### ISSUE THREAD

**Issue by ajmeersha** [DanielYKPan/date-time-picker#351]
when i use this picker in bootstrap modal it show behind the modal and cant able to choose date.. i think its because of z-index property.. can u solve this issue

**Comment by DanielYKPan** [comment]
Yes, it is about the z-index. But you could adjust the picker's z-index via your own css/sass/scss file. I mean overwrite the default in you own file

**Comment by tannirum** [comment]
Update z-index:1000 to z-index:1999 !important in all places in the file picker.min.css
