### ISSUE TITLE
[Feature] Need ability to add class for Popup element of picker

### ISSUE THREAD

**Issue by vvip-68** [DanielYKPan/date-time-picker#362]
It is extremely necessary to have ability for adding class to popup panel, as it implemented in
< mat-select > component of Material Design
`< mat-select ... panelClass="login-select" >`
This code provides additional class to popup:
`<div class="ng-trigger ng-trigger-transformPanel ng-tns-c3-4 mat-select-panel mat-primary **login-select** ng-star-inserted mat-select-panel-done-animating" ng-reflect-klass="mat-select-panel mat-primary" ng-reflect-ng-class="login-select" style="transform-origin: 50% 19.5px 0px; font-size: 13px; opacity: 1; min-width: calc(100% + 32px); transform: scaleY(1);"><div class="mat-select-content ng-trigger ng-trigger-fadeInContent" style="opacity: 1;">`
In this case it is possible set position of Popup element over css.
It is better, if ability to add class would be on level higher, to < div > with class="cdk-overlay-pane" as I suggested [on](https://github.com/DanielYKPan/date-time-picker/issues/358) Request: how to change position of popup? #358

**Comment by DanielYKPan** [comment]
Update the picker to latest version.

Added [backdropClass] and [panelClass] for `owl-date-time`
