### ISSUE TITLE
version compatibility issue 

### ISSUE THREAD

**Issue by raviguru123** [DanielYKPan/date-time-picker#363]
I just want to know which version should I use for the following environment 

angular/cli: 1.3.1
node: 8.2.1
angular/animations: 4.4.7
angular/common: 4.4.7
angular/compiler: 4.4.7
angular/core: 4.4.7
angular/forms: 4.4.7
angular/http: 4.4.7
angular/platform-browser: 4.4.7
angular/platform-browser-dynamic: 4.4.7
angular/platform-server: 4.4.7
angular/router: 4.4.7
angular/cli: 1.3.1
angular/compiler-cli: 4.4.7
angular/language-service: 4.4.7

**Comment by DanielYKPan** [comment]
ng-pick-datetime@6.*.* only support cli:6+ projects or angular 6+
ng-pick-datetime@5.*.* only support angular 5+
