### ISSUE TITLE
Remove rangeSeparator when "to" is not selected

### ISSUE THREAD

**Issue by ZgjimDida** [DanielYKPan/date-time-picker#365]
I want to remove the rangeSeparator when I select only the "from" date. It was like this by default in the old version, but in the new version it doesn't remove it when selecting only one date.

**Comment by DanielYKPan** [comment]
I guess this is because the new version add 'rangeFrom' and 'rangeTo' type.

**Comment by ZgjimDida** [comment]
I see that. But the rangeFrom, and rangeTo are meant for when you have two separate inputs. I don't see how you would use that, in one input. Having the ability to select 'from' and 'to' from one input, but if only the 'from' date is selected to remove the separator.

**Comment by DanielYKPan** [comment]
All right. But why you want to remove the separator when only the 'from' id selected?

**Comment by ZgjimDida** [comment]
Yes, exactly like that. But when i select [selectMode]="rangeFrom", it disables the selection of the 'to' date. I want to be able to select both, but remove the separator when only one of them is selected.

**Comment by DanielYKPan** [comment]
Yes. But why you want to remove the separator when only one of them is selected

**Comment by ZgjimDida** [comment]
It just doesn't look good. You can see the pictures from the old and the new version. I don't know if this is possible to do, but I just need it to look like in the old version.

You can that in the old one it is removed and in the new one it is still shown. 
![calendar1](https://user-images.githubusercontent.com/3892425/40554433-fa8988cc-6045-11e8-8a73-9fd9e582e921.PNG)
![calendar2](https://user-images.githubusercontent.com/3892425/40554434-fac0974a-6045-11e8-9b0f-fc1772f4f0c3.PNG)
