### ISSUE TITLE
Editing time picker using keyboard doesnt work

### ISSUE THREAD

**Issue by kovalanzeemart** [DanielYKPan/date-time-picker#366]
Here is what i set
export const ZM_MOMENT_FORMATS = {
  parseInput: 'DD/MM/YYYY',
  fullPickerInput: 'DD/MM/YYYY',
  datePickerInput: 'DD/MM/YYYY',
  timePickerInput: 'LT',
  monthYearLabel: 'MMM YYYY',
  dateA11yLabel: 'LL',
  monthYearA11yLabel: 'MMMM YYYY',
};
And in html <owl-date-time [pickerType]="'timer'" #cutOffTime></owl-date-time> 
Without OwlMomentDateTimeModule i am able to edit the time using key board.  But after adding the formats using OwlMomentDateTimeModule, it works if i use the picker but when editing using keyboard just sets the time to 00 00.

**Comment by DanielYKPan** [comment]
Pleas use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.
