### ISSUE TITLE
Parse/output as timestamps

### ISSUE THREAD

**Issue by kmturley** [DanielYKPan/date-time-picker#367]
thanks for the great date/time picker!

One thing i'm having to workaround but thought was a feature, is converting timestamps to Date objects for use with the picker:

```
<input matInput formControlName="dateStart" placeholder="From" [owlDateTimeTrigger]="dt1" [owlDateTime]="dt1" required />
<owl-date-time #dt1></owl-date-time>
```
```
this.event['dateStart'] = new Date(this.event['dateStart']);
```

And then back again at the end:
```
this.form.value['dateStart'] = new Date(this.form.value['dateStart']).getTime();
```

It seems strange to me that passing a timestamp Number does not automatically convert!

In your Stackblitz consider the difference:
https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker?file=src%2Fapp%2Fbasic%2Fbasic.component.ts
```
public dateTime = 1526677222000;
public dateTime = new Date(1526677222000);
```

I see you have a function to do this here:
https://github.com/DanielYKPan/date-time-picker/blob/84db263d344de93e9634e1a4563b47232c8819f7/src/date-time/adapter/native-date-time-adapter.class.ts#L297

But using breakpoints, I can see that the code is not triggered even though I'm importing the modules:

```
import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';
@NgModule({
  imports: [
    OwlDateTimeModule,
    OwlNativeDateTimeModule
  ],
```

Also the date format outputted is ISO string:
2018-05-18T21:00:22.000Z

Can we have timestamp format for output? That seems to be the standard for database APIs?

Maybe I am using it wrong, in which case would be great to include a timestamp demo, to show off the feature!

**Comment by DanielYKPan** [comment]
I guess you could transform your timestamps value into a Native Javascript Date Object before you bind the value into your form. I keep the picker ngModel binding to Native Javascript Date Object or any other form of Date Object(MomentJS). I hope this makes sense.

**Comment by kmturley** [comment]
Ya I understand I can work around using a second binding and converting before/after. That's kind of how I'm currently doing it.

Just wondering why the code to convert a Number to a Date is there, but not triggered... And also why you are inputting/outputting ISO string format, and not Unix timestamp (which seems to be the standard)?

For comparison the Angular Material date picker accepts timestamp inout and output:
https://material.angular.io/components/datepicker/examples
