### ISSUE TITLE
Scrollbar are displayed when the calendar is displayed at the bottom of a form

### ISSUE THREAD

**Issue by heyanctil** [DanielYKPan/date-time-picker#37]
When the datetime picker is displayed at the bottom of a form, scrollbar are displayed to show calendar. Is it possible that the DOM element is create outside the form to show up outside the div element without overflow?

Best Regards

![image](https://cloud.githubusercontent.com/assets/7291291/25244664/a640455a-25cf-11e7-9366-989ae647e552.png)

**Comment by DanielYKPan** [comment]
@heyanctil 
any suggestions to do that?

**Comment by heyanctil** [comment]
Right now, no hehehe
