### ISSUE TITLE
Refresh component labels on language change

### ISSUE THREAD

**Issue by Pasab** [DanielYKPan/date-time-picker#370]
Hello,

I've tried to implement the OwlDateTimeIntl class as a provider in my module   
 {
      provide: OwlDateTimeIntl,
      useClass: DateTimePickerLabelsConfig,
      deps: [TranslateService]
    }
 but it doesn't refresh the buttons labels properly if I change my language application. 

A ctrl + f5 fix the problem but that's not a solution.

Could you develop something to refresh labels dynamically please ?

**Comment by DanielYKPan** [comment]
I have no idea what you mean refresh label dynamically.

Pleas use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by Pasab** [comment]
I refered to the **Localizing labels and messages** paragraph. In order to set labels with a properties class, we need to declare it in a module provider. 

@NgModule({
    imports: [OwlDateTimeModule, OwlNativeDateTimeModule],
    providers: [
        {provide: OwlDateTimeIntl, useClass: DefaultIntl},
    ],
})

Or I can't refresh labels dynamically this way, it would be useful to set labels values directly in the component calling the datetime picker api like you did with the locale setting : 

export class AppExample {
    constructor(dateTimeAdapter: DateTimeAdapter<any>) {
        dateAdapter.setLocale('ja-JP'); // change locale to Japanese
    }

I develop a multi languages application, I need to instant refresh labels if language is changed.

**Comment by DanielYKPan** [comment]
Sorry, this is not supported. You might look for a work-around for your case.

**Comment by gustavolira** [comment]
I have this same problem
"I develop a multi languages application, I need to instant refresh labels if language is changed."
