### ISSUE TITLE
time-picker overlapped while using bootstrap modal

### ISSUE THREAD

**Issue by saigalamatya** [DanielYKPan/date-time-picker#372]
I am having an issue with time-picker. I am trying to implement it in a bootstrap modal. When I click on the field that gets the time picker dropdown, the dropdown gets overlapped by the modal. And whenever I close the modal, the time-picker shows up. How can I implement it without being overlapped? 
Here's the screenshot of the modal & the field that uses time picker is "Show Time":
![capture1](https://user-images.githubusercontent.com/20023657/40983932-68f123d4-6900-11e8-9268-125264c7c21d.PNG)

Here's the screenshot after I close the modal:
![capture2](https://user-images.githubusercontent.com/20023657/40984056-b4a29a60-6900-11e8-985b-e7ea0aa2244a.PNG)

Here's the component code:
`
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">
  Add Showtime
</button>

<div class="modal fade bd-example-modal-lg" id="theaterModal" tabindex="-1" role="dialog" aria-labelledby="theaterModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="theaterModalLabel">Add Showtime</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form (ngSubmit)="f.form.valid && onSubmit(f)" #f="ngForm">
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6">
                <div class="form-group" [ngClass]="{ 'has-error': f.submitted && !theaterId.valid }">
                  <label for="theaterId">Id *:</label>
                  <span class="error" *ngIf="f.submitted && theaterId.errors?.required">&nbsp;&nbsp;&nbsp;&nbsp;Name Required</span>
                  
                  <select 
                    name="theaterId" 
                    class="custom-select" 
                    [(ngModel)]="model.theaterId" 
                    #theaterId="ngModel" 
                    required
                  >
                    <option selected>Select Theater Id</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                  </select>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group" [ngClass]="{ 'has-error': f.submitted && !movieId.valid }">
                  <label for="type">Type *:</label>
                  <span class="error" *ngIf="f.submitted && movieId.errors?.required">&nbsp;&nbsp;&nbsp;&nbsp; Movie Id Required</span>
                  
                  <select 
                    name="movieId" 
                    class="custom-select" 
                    [(ngModel)]="model.movieId" 
                    #movieId="ngModel" 
                    required
                  >
                    <option selected>Select Movie Id</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                  </select>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                
                <div class="form-group" [ngClass]="{ 'has-error': f.submitted && !showDate.valid }">
                  <label for="showDate">Show Date *:</label>
                  <span class="error" *ngIf="f.submitted && showDate.errors?.required">&nbsp;&nbsp;&nbsp;&nbsp;Show Date Required</span>
                  <input
                    type="date"
                    name="showDate" 
                    class="form-control" 
                    [(ngModel)]="model.showDate" 
                    #showDate="ngModel"
                    required
                  >
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group" [ngClass]="{ 'has-error': f.submitted && !showTime.valid }">
                    <label for="showTime">Show Time *:</label>
                    <span class="error" *ngIf="f.submitted && showTime.errors?.required">&nbsp;&nbsp;&nbsp;&nbsp;Show Time Required</span>
                    
                    <input 
                      [owlDateTimeTrigger]="dt4" 
                      [owlDateTime]="dt4"
                      class="form-control" 
                      name="showTime" 
                      [(ngModel)]="model.showTime" 
                      #showTime="ngModel"
                      required 
                    >
                    <owl-date-time [pickerType]="'timer'" #dt4></owl-date-time>
                  </div>  
              </div>
            </div>
            
            <div class="row">
              <div class="col-md-6">
                <div class="form-group" [ngClass]="{ 'has-error': f.submitted && !format.valid }">
                    <label for="format">Format *:</label>
                    <span class="error" *ngIf="f.submitted && format.errors?.required">&nbsp;&nbsp;&nbsp;&nbsp;Format Required</span>
                    
                    <select 
                      name="format" 
                      class="custom-select" 
                      [(ngModel)]="model.format" 
                      #format="ngModel" 
                      required
                    >
                      <option selected>Select Format</option>
                      <option value="1">2D</option>
                      <option value="2">3D</option>
                    </select>
                  </div>  
                </div>
            </div>
        </div>
      </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-secondary" data-dismiss="modal" (click)="resetForm(f)">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>`

**Comment by DanielYKPan** [comment]
Overwrite the css z-index for class `cdk-overlay-container` to suit your demands

**Comment by laurabelli** [comment]
Overwriting the css z-index for class `cdk-overlay-container` make the picker visible, but inputs for minutes and hours are not accessible, and the user can only use the arrows.
Any ideas?
