### ISSUE TITLE
In mode "rangeTo ~ rangeFrom" how select only date?

### ISSUE THREAD

**Issue by MarceloBonifazio** [DanielYKPan/date-time-picker#374]
In mode "rangeTo ~ rangeFrom" how select only date, without time?
And one more thing, how I can create some business rules, type: rangeFrom <= rangeTo + 1 month

This is my imput:

````
<input [owlDateTimeTrigger]="dt1" [owlDateTime]="dt1"
           [min]="min" [max]="max"
           [selectMode]="'rangeFrom'" class="form-control dt-border">
<owl-date-time [pickerType]="'calendar'" [pickerMode]="'dialog'" #dt1></owl-date-time> 
<input [owlDateTimeTrigger]="dt2" [owlDateTime]="dt2"
           [min]="min" [max]="max"
           [selectMode]="'rangeTo'" class="form-control dt-border">
<owl-date-time [pickerType]="'calendar'" [pickerMode]="'dialog'" #dt2></owl-date-time>

**Comment by DanielYKPan** [comment]
1, Set the pickerType to 'calendar' and set the dateTime format, you can learn more about this from [here](https://danielykpan.github.io/date-time-picker/#locale-formats)

2, set min and max value to restrict your date time range.
