### ISSUE TITLE
Wrong value from time-picker

### ISSUE THREAD

**Issue by dancornilov** [DanielYKPan/date-time-picker#377]
![image](https://user-images.githubusercontent.com/24212761/41241275-2a2cb0e2-6da5-11e8-9dd4-73e89891451c.png)
When i choose 27 june from datepicker, in my variables i receive 26 june
![image](https://user-images.githubusercontent.com/24212761/41241305-3efad13e-6da5-11e8-940e-231c74e0dae2.png)

Where i can set timezone?

**Comment by DanielYKPan** [comment]
The value coming from picker is a Javascript Date Object (MomentJs Object if you are using OwlMomentDateTimeModule) and it should contain the timezone value which should be your system's timezone.
You could adjust the value to you own timezone value.
