### ISSUE TITLE
What if i dont want ISO date format when using custom format at moment.js

### ISSUE THREAD

**Issue by Rachit-rkb** [DanielYKPan/date-time-picker#378]
When using owl-date-time picker with custom format  the value which is validated with moment.js  should be in format YYYY-MM-DD due to this code.
` var extendedIsoRegex = /^\s*((?:[+-]\d{6}|\d{4}-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/;
   `
**At line: 2161**(the second "-"character in regex does not allow to have different format like "/" or "*").

What if the date format at the class in .ts file is different like: YYYY/MM/DD

When converting to different format the value on view is removed (I know what is causing all this problem in present code) but i wanted to know a feasible solution for this.

**Comment by DanielYKPan** [comment]
I am sorry I don't know what you tried to do.

You might consider to use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by Rachit-rkb** [comment]
I am adding the images to make you better understand my problem.

I have made changes on the moment-js.ts file for having a different format of ng-model which is different from YYYY-MM-DD; I have changed it to YYYY/MM/DD.

![screenshot 2 copy](https://user-images.githubusercontent.com/20870995/41290514-bd6f402a-6e6a-11e8-9513-a4f36500a7ca.png).

I am changing the value of ngModel variable on (**ngModelChange**) method.

![screenshot 3 copy](https://user-images.githubusercontent.com/20870995/41290580-f1fbfe32-6e6a-11e8-8aac-334b35228eb0.png)

As you can see when i pick a new date the value of the ngModel variable is changed but the input box becomes blank.

![screenshot 4 copy](https://user-images.githubusercontent.com/20870995/41290616-0ea5ee80-6e6b-11e8-960e-601c46a57693.png)


The date is visible only if the ngModel value is in format **"YYYY-MM-DD"** (not visible if in format **"YYYY/MM/DD"**).

How can i achieve this ;having different format in my ngModel variable and visible date on input.

**Comment by DanielYKPan** [comment]
Do not show image, show the actual app link.

**Comment by Rachit-rkb** [comment]
https://stackblitz.com/edit/github-95krdj

this is the link ,Please use Picker with momentJs (second last input)

**Comment by DanielYKPan** [comment]
picker could only accept Native Javascript Date Object (MomentJS Object if you are using moment.js)

```
export class MomentJsComponent implements OnInit {

  public dateTime = new moment(); // MomentJS Object
  value: any;

  constructor() {
  }

  ngOnInit() {
  }

  private onChange(_value) {
    if (_value && _value._d && (typeof _value._i !== 'string' || _value._i.length === 10)) {
      _value = new Date(_value);
      this.dateTime = moment(_value).format("YYYY/MM/DD"); // Now You changed it to String. Error!!!!!!
    }
  }

}
```

**Comment by Rachit-rkb** [comment]
Can you tell me then why does **YYYY-MM-DD** works?

`export class MomentJsComponent implements OnInit {

  public dateTime = new moment(); // MomentJS Object
  value: any;

  constructor() {
  }

  ngOnInit() {
  }

  private onChange(_value) {
    if (_value && _value._d && (typeof _value._i !== 'string' || _value._i.length === 10)) {
      _value = new Date(_value);
      this.dateTime = moment(_value).format("YYYY-MM-DD"); // This Works fine!!!!!!
    }
  }

}`

**Comment by DanielYKPan** [comment]
I am not gonna comment this any more as this is not an issue from the picker.

You might consider learn more about Typescript, Javascript and Native Date Object.

**Comment by Rachit-rkb** [comment]
OK, thanks.
