### ISSUE TITLE
got date from service and setted the time range, date didn't show up

### ISSUE THREAD

**Issue by mrjihai** [DanielYKPan/date-time-picker#379]
I got start date and end date from servic and  used [(ngModel)] to bind the dates to  time range[] to set the date. But nothing show up.

 my sample code:
<input
                                            [owlDateTimeTrigger]="start"
                                            [owlDateTime]="start"
                                            placeholder="Start Date"
                                            [(ngModel)]="tab.moment"
                                            [selectMode]="'rangeFrom'" >

<input
                                            [owlDateTimeTrigger]="end"
                                            [owlDateTime]="end"
                                            placeholder="End Date"
                                            [(ngModel)]="tab.moment"
                                            [selectMode]="'rangeFrom'">

http.get(url).subscribe( res =>{tab.moment[0] = date1, tab.moment[1] = date2})

**Comment by DanielYKPan** [comment]
Pleas use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by thurimerla** [comment]
Hi @mrjihai ,
Did you find any solution for this issue ?


Thanks in advance
