### ISSUE TITLE
selectionMode="'multiple'"

### ISSUE THREAD

**Issue by saurabhrathod35** [DanielYKPan/date-time-picker#381]
[selectionMode]="'multiple'" not working on every version 
stackblitz provide the only selectMode but multiple not work

**Comment by DanielYKPan** [comment]
there is no `multiple` option. Please refer to README.MD

**Comment by saurabhrathod35** [comment]
please Provide multiple date selection like event calendar

**Comment by DanielYKPan** [comment]
Sorry, there is no `multiple` at this moment.
