### ISSUE TITLE
DateTimeChange Event

### ISSUE THREAD

**Issue by arjunsingh6976** [DanielYKPan/date-time-picker#382]
dateTimeChange event not getting triggered

**Comment by arjunsingh6976** [comment]
I want an event to be trigger on date or time selection respectively.

**Comment by DanielYKPan** [comment]
`dateTimeChange` event in `input[owlDateTime]` would trigger in when any date value or time value is changed. You could compare the return event's value to your previous value to see if its date or time value changed.

**Comment by arjunsingh6976** [comment]
dateTimeChange event is not getting triggered when the date or time is changed

<input class="date-control" name="datetime" [owlDateTimeTrigger]="dt1" (dateTimeChange)="pickerDateChange()" 
 [owlDateTime]="dt1" [selectMode]="'range'" [(ngModel)]="selectedDate"  [rangeSeparator]="'--'" 
 [min]="minStartDate" [max]="ClassEndDate" />


  pickerDateChange() {
    console.log('DateChange');
  }
