### ISSUE TITLE
dateTimeChange event is not getting triggered

### ISSUE THREAD

**Issue by arjunsingh6976** [DanielYKPan/date-time-picker#383]
dateTimeChange event is not getting triggered when the date or time is changed

<input class="date-control" name="datetime" [owlDateTimeTrigger]="dt1" (dateTimeChange)="pickerDateChange()"
[owlDateTime]="dt1" [selectMode]="'range'" [(ngModel)]="selectedDate" [rangeSeparator]="'--'" />
<owl-date-time [pickerMode]="dialog" [hour12Timer]="true" #dt1></owl-date-time>

pickerDateChange() {
console.log('DateChange');
}

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by arjunsingh6976** [comment]
https://stackblitz.com/edit/angular-p9rpbq

**Comment by arjunsingh6976** [comment]
https://stackblitz.com/edit/angular-p9rpbq?embed=1&file=src/index.html

**Comment by DanielYKPan** [comment]
It works in your example.

It console log the text once you clicked the set button.

**Comment by arjunsingh6976** [comment]
But while selecting date on calendar is there any event triggered and based on that i want to manipulate to date

**Comment by DanielYKPan** [comment]
Sorry, there is no such event.
