### ISSUE TITLE
Swap positions of 'Set' and 'Cancel' buttons

### ISSUE THREAD

**Issue by Deilan** [DanielYKPan/date-time-picker#386]
Is there a way to swap positions of 'Set' and 'Cancel' buttons?

**Comment by DanielYKPan** [comment]
this is not configurable.

**Comment by DanielYKPan** [comment]
Actually, this is configurable through css.
The buttons parent element is used `display: flex`.

You could use `order` on the set button or the cancel button element to set the position. If you are not familiar with `display:flex`, you could google it.
