### ISSUE TITLE
Customize firstDayOfWeek

### ISSUE THREAD

**Issue by Deilan** [DanielYKPan/date-time-picker#387]
How to customize `firstDayOfWeek`? In 'ru' locale the first day of week is monday, but the component displays it's sunday.

**Comment by DanielYKPan** [comment]
Please refer to README.md and there is a property `[firstDayOfWeek]`

**Comment by Deilan** [comment]
@DanielYKPan Thank you, not sure why I have missed that. :) Is there a chance it would be fixed in the scope of locale settings provider?

**Comment by DanielYKPan** [comment]
@Deilan No.
