### ISSUE TITLE
Timer Gets Disabled

### ISSUE THREAD

**Issue by arjunsingh6976** [DanielYKPan/date-time-picker#389]
![timer_gets_disabled](https://user-images.githubusercontent.com/36946680/41638732-80cc1828-7478-11e8-9b13-5dd6adf21ad4.png)

I was using the same code uploaded on stackblitz. Its working on stackblitz but not on local server.

Initially its not get disabled but once you start increase hours or minutes when minutes count reach to 59 its get disabled and on hours when count reach to 12 its get disabled

**Comment by arjunsingh6976** [comment]
stackblitz url : https://stackblitz.com/edit/angular-p9rpbq?embed=1&file=src/index.html

**Comment by DanielYKPan** [comment]
Not sure what you mean, your stackblitz demo works fine for me.

**Comment by arjunsingh6976** [comment]
I mean to say when you change hour or minute clicking  on up and down arrow button its get disabled

**Comment by DanielYKPan** [comment]
Your stackblits demo works fine for me.
You might consider update the picker's version to latest in your local development.

I close this as this is not an issue.
