### ISSUE TITLE
Localization does not localize date values

### ISSUE THREAD

**Issue by Braste** [DanielYKPan/date-time-picker#39]
Setting locale to "de" does not translate the date values:
- Days: 
   - Monday, Tuesday.... instead of Montag, Dienstag....
   - 1st, 2nd, 3rd instead of 1., 2., 3. (There is no shortcut for First, second, etc. besides a period in German)
- Month: January, February.... instead of Januar, Februar....

**Comment by normandjulian** [comment]
Hi,

Did you try to add this line in your app.module.ts : 
`import '../node_modules/moment/locale/de';`

**Comment by Braste** [comment]
Yes, i added it and it is the solution, but there isn't any hint in the documentation, so this is an issue in my eyes.

**Comment by DanielYKPan** [comment]
@Braste 
This is not about the date-time-picker package. This is about how you use momentJS in your SystemJS app.

cheers.
