### ISSUE TITLE
Can't resolve '@angular/cdk/keycodes'

### ISSUE THREAD

**Issue by alexsintoni** [DanielYKPan/date-time-picker#391]
Hi,

I like your date-time-picker.

Today I installed last version 6.0.5 of ng-pick-datetime.

I followed the instruction at https://www.npmjs.com/package/ng-pick-datetime but when I try to launch the app I receive the following error:

Module not found: Error: Can't resolve '@angular/cdk/keycodes' in '/home/alex/Development/workspace/kekse/frontend/node_modules/ng-pick-datetime/date-time'

I guess I made an error somewhere but I can't figure it out.
Can you please help me on it?

I thank you in advanced.

**Comment by DanielYKPan** [comment]
Npm Install the `@angular/cdk` package.

**Comment by alexsintoni** [comment]
Hi,

I was guessing to do that. I have just found out that you actually listed that dependency at https://www.npmjs.com/package/ng-pick-datetime

I apologize to have disturbed you for it.

Anyway, it works and thanks a million for the help.
