### ISSUE TITLE
how can we use different date format in single page?

### ISSUE THREAD

**Issue by rahulgiri** [DanielYKPan/date-time-picker#392]
i tried to update provider value but the owl date picker parse formate is not updated.

**Comment by DanielYKPan** [comment]
This is NOT a issue from the picker. I would close this.

You could learn more about formation from [here](https://danielykpan.github.io/date-time-picker/#locale-formats)

**Comment by rahulgiri** [comment]
@DanielYKPan , I already used the code below to use custom format.

`import { NgModule } from '@angular/core';
import { OwlDateTimeModule, OwlNativeDateTimeModule, OWL_DATE_TIME_FORMATS} from 'ng-pick-datetime';

// learn more about this from
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat
export const MY_NATIVE_FORMATS = {
    fullPickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric'},
    datePickerInput: {year: 'numeric', month: 'numeric', day: 'numeric'},
    timePickerInput: {hour: 'numeric', minute: 'numeric'},
    monthYearLabel: {year: 'numeric', month: 'short'},
    dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
    monthYearA11yLabel: {year: 'numeric', month: 'long'},
};

@NgModule({
    imports: [OwlDateTimeModule, OwlNativeDateTimeModule],
    providers: [
        {provide: OWL_DATE_TIME_FORMATS, useValue: MY_NATIVE_FORMATS},
    ],
})
export class AppExampleModule {
}
`

but if i need to update the value of OWL_DATE_TIME_FORMATS provider in ngOnInt, Is it possible?

**Comment by rahulgiri** [comment]
that was my bad. got the solution. 


need to set multi: true in providers section and  pass  @Optional()
        @Inject(OWL_DATE_TIME_FORMATS)
        protected dateTimeFormats: OwlDateTimeFormats in constructor and update it in ngOnInit.

**Comment by pamanes** [comment]
@rahulgiri could you please help out? I am trying to change the format on button click or on ngOnInit but I can't make it work. Do you have a full example?
