### ISSUE TITLE
Possibility to change style in real-time

### ISSUE THREAD

**Issue by alexsintoni** [DanielYKPan/date-time-picker#393]
Hi,

first of all I want to thank you for your support. I want also to congratulate about this component which is very good.

I wirte you to ask if it would be possible for the next version to supply a scss style file where configure the style in real-time.
In particular I would like to use this component with [Nebular](http://akveo.com/ngx-admin/#/pages/dashboard) framework where it is possible to change the style using a selector.

If I have the scss style file for this calendar component I can change the background color, the date selected color etc...

Again, thanks a million in advance for your help

**Comment by DanielYKPan** [comment]
You could overwrite the picker's default css style in your own scss file. The picker default scss file is in the source code.

The css selector would be found in your browser's dev tools.

**Comment by alexsintoni** [comment]
That's cool, thanks a million.

If I may suggest something, I think it would be great to add the picket style documentation to the very good one at [Ng Date Time Picker](https://danielykpan.github.io/date-time-picker/)

That is very well done and maybe you can add at the end a Style section.

Also, I am trying to open the picker from a modal window but it appears behind it instead of in front.
Do you have any suggestion on how to fix it?

Again thanks a million
