### ISSUE TITLE
Disabled input issue

### ISSUE THREAD

**Issue by dancornilov** [DanielYKPan/date-time-picker#394]
I want one think, when user choose date he can't edit this date direct from input, only from datepicker.
<img width="421" alt="screen shot 2018-06-25 at 6 32 17 pm" src="https://user-images.githubusercontent.com/24212761/41859988-23c776f4-78a6-11e8-85ca-1baf578534b2.png">
<img width="217" alt="screen shot 2018-06-25 at 6 32 24 pm" src="https://user-images.githubusercontent.com/24212761/41859989-23e8f5f4-78a6-11e8-8440-3cff4c7f73c4.png">

I try use for input - [disabled]="true" and for owl-date-time selector [disabled]="true" but not work :(

**Comment by DanielYKPan** [comment]
Please google html text input before asking any questions.
