### ISSUE TITLE
Option to allow body scroll

### ISSUE THREAD

**Issue by nickngsr** [DanielYKPan/date-time-picker#395]
Is there a way of stopping the scroll block while the calendar is open? If it is not possible, you must show the calendar as dialog if the viewport < 468px in height.

**Comment by DanielYKPan** [comment]
Blocking the body scrolling is intentional.

There is a property `[pickerMode]` to make the calendar as a dialog.

**Comment by nickngsr** [comment]
I'm aware of this, my point is I want normal behaviour to be a popup, however in the case where you have a viewport that is too small, it will cut off half of the calendar and you can't do anything about it.

Is it possible to get the ability to switch the CDK to reposition scroll strategy instead of block strategy via the use of a variable?

**Comment by Londeren** [comment]
I have the same situation. Could you add some option for this?

**Comment by DanielYKPan** [comment]
Updated the picker to latest version.
Now the picker position has been optimised. And `owl-date-time` also has a new property `[scrollStrategy]` which accept ScrollStrategy object from angular/cdk.
