### ISSUE TITLE
An error - Angular 6 with Material

### ISSUE THREAD

**Issue by bdairy** [DanielYKPan/date-time-picker#397]
I've installed the date-time picker,, with Moment JS provder.. and followed the correct steps..BUt I am getting this error : 
EROR TypeError: this.overlay.position(...).flexibleConnectedTo(...).withTransformOriginOn is not a function
And it is completely broken.
.
Here is my Module:

```
import { OwlDateTimeModule, OWL_DATE_TIME_FORMATS } from 'ng-pick-datetime';
import { OwlMomentDateTimeModule } from 'ng-pick-datetime-moment';
```

```
export const MY_FORMATS = {
  parse: {
    dateInput: 'LL',
  },
  display: {
    dateInput: 'LL',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  },
};
```

```
@NgModule({
  imports: [
 CommonModule,
    FormsModule,
 OwlDateTimeModule, OwlMomentDateTimeModule
],
  providers: [
      {provide: OWL_DATE_TIME_FORMATS, useValue: MY_FORMATS}
],....
```

and My component.html as follows:
```
<input [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1" placeholder="Date Time">
<owl-date-time #dt1></owl-date-time>
```

**Comment by bdairy** [comment]
Thanks,, Great work BTW

**Comment by takahser** [comment]
Sorry, I think it had to do with some cached node modules. After running `rm -rf ./node_modules` and reinstalling, it works with both versions I mentioned.

**Comment by atejadac** [comment]
Having exactly the same error. I have tried to do what @takahser did (deleting node/modules and reinstalling) and also what you @DanielYKPan suggested (update angular cdk) but the error is still showing. I'm following exactly the **Get started** steps in order to use it and the error persists.
