### ISSUE TITLE
An error - TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by N-Franck** [DanielYKPan/date-time-picker#398]
Hi!

I've installed the datetimepicker into an application Angular 4/Angular CLI.
I've inserted this following code in my view file : 

> <input [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1">
      <owl-date-time #dt1></owl-date-time>

I've included OwlDateTimeModule and OwlNativeDateTimeModule in my module file.

When i've arrived on my page, i have the fallowing error in my console : 

>ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at new OwlDialogService (dialog.service.js:36) ...

Thanks for you help

**Comment by DanielYKPan** [comment]
Please read the README.md. 
This picker only support Angular 6+ app

**Comment by N-Franck** [comment]
Ah darn ! I did not see this part, sorry.
Thanks for your help
