### ISSUE TITLE
popup dialog too small

### ISSUE THREAD

**Issue by miojoffey** [DanielYKPan/date-time-picker#399]
i am using angular version 5. i was able to integrate your component, but how do i change the size such that it would be readable anough? i have a pretty big screen, yet i am having issues using the component as it is too small, here https://clip2net.com/s/3V8yMRv

how do i set the size. thanks

**Comment by DanielYKPan** [comment]
this date time picker is designed responsively. Just change the font size of class `.owl-dt-container` to whatever your like.

**Comment by jayantakarmakar03** [comment]
thanks its working
