### ISSUE TITLE
Styles are not Applied in this Module and UI is Scattered

### ISSUE THREAD

**Issue by hardy12994** [DanielYKPan/date-time-picker#401]
I have include css by <Link> tag - 
as -
```sh
<link rel="stylesheet" href="node_modules/ng-pick-datetime/assets/style/picker.min.css">

```

Here are the Screen Shots -

![lo](https://user-images.githubusercontent.com/27506127/42165836-d84da9e2-7e26-11e8-8b10-880c9aaf1615.png)
![lo1](https://user-images.githubusercontent.com/27506127/42165840-dbe95c72-7e26-11e8-900b-6c0e5f8ef99c.png)

Please Reffer to Above Screen Shots

**Comment by DanielYKPan** [comment]
This is not an issue from the picker. I would close this.

That's where the style file located. And you have to refer to it in your project environment.
