### ISSUE TITLE
Localization labels & messages not working

### ISSUE THREAD

**Issue by joshuakeck** [DanielYKPan/date-time-picker#405]
Hi Daniel,
I'm trying to use the localization & messages like in your example / docs here, but it doesn't seem to work:
https://danielykpan.github.io/date-time-picker/#locale-formats 

It will throw the same errors like in the "Localization" example on stackblitz :
https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker

```
ERROR
Error: Unable to process animations due to the following failed trigger transitions
@transformPicker has failed due to:

- `query("@fadeInPicker")` returned zero elements. (Use `query("@fadeInPicker", { optional: true })` if you wish to allow this.)

```
I'm using Angular 6 and the newest version (6.0.8) of your date time picker.

Thanks!

**Comment by DanielYKPan** [comment]
Thanks, and the example should be fixed now.

When we use a customised localization intel, we need to extends the origin class `OwlDateTimeIntl`;

```
export class MyCustomIntl extends OwlDateTimeIntl = {
}
```

**Comment by starman2015** [comment]
export class MyCustomIntl extends OwlDateTimeIntl = {
}

WRONG!

Must be: 

export class DefaultIntl extends OwlDateTimeIntl {
  /** A label for the up second button (used by screen readers).  */
  upSecondLabel = 'Add a second';

  /** A label for the down second button (used by screen readers).  */
  downSecondLabel = 'Minus a second';

  /** A label for the up minute button (used by screen readers).  */
  upMinuteLabel = 'Add a minute';

  /** A label for the down minute button (used by screen readers).  */
  downMinuteLabel = 'Minus a minute';

  /** A label for the up hour button (used by screen readers).  */
  upHourLabel = 'Add a hour';

  /** A label for the down hour button (used by screen readers).  */
  downHourLabel = 'Minus a hour';

  /** A label for the previous month button (used by screen readers). */
  prevMonthLabel = 'Previous month';

  /** A label for the next month button (used by screen readers). */
  nextMonthLabel = 'Next month';

  /** A label for the previous year button (used by screen readers). */
  prevYearLabel = 'Previous year';

  /** A label for the next year button (used by screen readers). */
  nextYearLabel = 'Next year';

  /** A label for the previous multi-year button (used by screen readers). */
  prevMultiYearLabel = 'Previous 21 years';

  /** A label for the next multi-year button (used by screen readers). */
  nextMultiYearLabel = 'Next 21 years';

  /** A label for the 'switch to month view' button (used by screen readers). */
  switchToMonthViewLabel = 'Change to month view';

  /** A label for the 'switch to year view' button (used by screen readers). */
  switchToMultiYearViewLabel = 'Choose month and year';

  /** A label for the cancel button */
  cancelBtnLabel = 'Cancel';

  /** A label for the set button */
  setBtnLabel = 'Select';

  /** A label for the range 'from' in picker info */
  rangeFromLabel = 'From date';

  /** A label for the range 'to' in picker info */
  rangeToLabel = 'To date';

  /** A label for the hour12 button (AM) */
  hour12AMLabel = 'AM';

  /** A label for the hour12 button (PM) */
  hour12PMLabel = 'PM';
}

**Comment by starman2015** [comment]
https://danielykpan.github.io/date-time-picker/#locale-formats
Previously, useValue: DefaultInt was used, but now useClass: DefaultIntl is used. In the example on the site, you changed const to a class, but forgot about the class content.

**Comment by mohan1899** [comment]
The format of the class  DefaultDateTimeIntl  should be 
import { Injectable } from '@angular/core';
import { OwlDateTimeIntl } from '@danielmoncada/angular-datetime-picker';

@Injectable()
export class DefaultDateTimeIntl extends OwlDateTimeIntl {
    public cancelBtnLabel = 'Cancel';
    public setBtnLabel = 'Apply Date/Time';
}

**Comment by souravsaraf123** [comment]
This answer worked for me : 

https://github.com/DanielYKPan/date-time-picker/issues/338#issuecomment-498917702

**Comment by DantonGodoy** [comment]
> 

You saved me hours of headaches. Thanks! This implementation should be included in the demo page as  a basic example.

**Comment by suprabhat15** [comment]
> The format of the class DefaultDateTimeIntl should be import { Injectable } from '@angular/core'; import { OwlDateTimeIntl } from '@danielmoncada/angular-datetime-picker';
> 
> @Injectable() export class DefaultDateTimeIntl extends OwlDateTimeIntl { public cancelBtnLabel = 'Cancel'; public setBtnLabel = 'Apply Date/Time'; }

This is not working in my case. Another solutions if possible?
