### ISSUE TITLE
afterPickerOpen not working as expected after upgrading to date-time picker version 6+

### ISSUE THREAD

**Issue by Rachit-rkb** [DanielYKPan/date-time-picker#407]
afterPickerOpen event is fired before the date-time widget opens up; it does not use happen in version <6.

I am attaching a stackblitz link ;Kindly use **Basic**(first input field).

[stack blitz link showing the problem](https://stackblitz.com/edit/github-34z7sd-jok3j7)

Expected : The event should be fired after the widget has opened up(widget is visible on screen).

**Comment by DanielYKPan** [comment]
Updated to the latest version (6.0.10).
It should be fixed.
