### ISSUE TITLE
Dispaly date format as DD/MM/YYYY 

### ISSUE THREAD

**Issue by ajmeersha** [DanielYKPan/date-time-picker#408]
display date as dd/mm/yyyy format only obtained by using locale en-GB but it changes the local time also.. how can i obtain this without changing the locale (like moment format('dd/mm/yyyy') )

**Comment by ajmeersha** [comment]
when i change the locale to en-GB it show the correct time in dd/mm/yyyy format, but the value return from the picker has 4hr and 30min difference with local time

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by ajmeersha** [comment]
https://stackblitz.com/edit/github-dwqnv9 check the localization

**Comment by DanielYKPan** [comment]
This is not an issue from the picker. Please learn about Angular json pipe and basic Native Javascript Date Object. You may google them.
