### ISSUE TITLE
You cannot specify an optional minimum date / time and maximum date / time

### ISSUE THREAD

**Issue by AimeeTan** [DanielYKPan/date-time-picker#41]
just like:
min-date Date, mininum selectable date
max-date Date, maximum selectable date
min-hour number, mininum selectable hour
max-hour number, maximum selectable hour

**Comment by DanielYKPan** [comment]
@AimeeTan 
I think you could do that with the value return from the picker.
Not necessary to implement this in the picker.

**Comment by WalnussPower** [comment]
@DanielYKPan 
it may not be necessary, but it would be a nice functionality though

**Comment by SabriJaA** [comment]
I need this options too plz

**Comment by DanielYKPan** [comment]
I guess the picker is just a box to show the calendar and the time clock. What date value (or time value) suites for your app is based on individual app. So you could simply limit the value by the value return from the picker (**dateTimePickerChange**).

**Comment by SabriJaA** [comment]
Issue: https://github.com/DanielYKPan/date-time-picker/pull/51

**Comment by SabriJaA** [comment]
Issue: https://github.com/SabriJaA/date-time-picker

**Comment by Braste** [comment]
It is a difference between handling the returned value and restricting the user from selecting a wrong value in the first place. Just handling wrong inputs isn't enought in most situations. So thank you, SabriJaA, hopefully, it will be merged.

**Comment by SabriJaA** [comment]
@Braste I fork this project and duplicate here -> https://github.com/steve-ferrero/ng-pick-datetime
I added :
[minDate]="2017-01-01"
[maxDate]="2017-07-01"
[week]="true" enable/disable
[holiday]="true" enable/disable

npm install @web-atrio/date-time-picker --save

**Comment by DanielYKPan** [comment]
Update to the latest package. Now the picker added [minMoment] and [maxMoment] to define what valid moment could be selected.
