### ISSUE TITLE
upgrade from 6.0.8 to 6.0.10 breaks angular-cli prod build

### ISSUE THREAD

**Issue by chrishawn** [DanielYKPan/date-time-picker#410]
not sure what this is, an odd one for sure, but no code changes everything works great in 6.0.8 but when going to 6.0.10 and then doing a `ng build --configuration=production` picker no longer shows, but i can see the css shadow popup when i trigger it, no console errors, i suspect a css bug or conflict somewhere.

**Comment by DanielYKPan** [comment]
It works fine in [Stackblitz](https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker)
