### ISSUE TITLE
TypeError: t is not a function

### ISSUE THREAD

**Issue by etonyali** [DanielYKPan/date-time-picker#411]
When I add this to my project, on build, I get this error:
`main.eedac21dd0e2131da8c3.js:1 ERROR Error: Uncaught (in promise): TypeError: t is not a function
TypeError: t is not a function`

Any idea?

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by etonyali** [comment]
It doesn't happen when I serve it which that's what StackBlitz does. It happens when the app completely built with --prod flag. I can show you if you like.

**Comment by DanielYKPan** [comment]
Sure
