### ISSUE TITLE
Question!! format

### ISSUE THREAD

**Issue by nico281** [DanielYKPan/date-time-picker#412]
Hi, how are you?? 
It could be possible to to set a different format for specific date component?
I'm making a form builder but i need to manage the format individually for each date input i use. 
Setting the format in the standard way makes all my component share the same format, even if i manage to change the format var on each component.

Cheers

**Comment by DanielYKPan** [comment]
There is no way to configure format for each date time input.

Workaround:
you could create a new Module for each your input.
