### ISSUE TITLE
Calendar is not positioned correctly

### ISSUE THREAD

**Issue by Londeren** [DanielYKPan/date-time-picker#414]
There are a lot of space above the calendar but buttons don't fit to the page 
<img width="364" alt="screen shot 2018-07-16 at 11 58 35" src="https://user-images.githubusercontent.com/757427/42750663-b2a6c1ae-88f0-11e8-890a-7302a0c13819.png">

**Comment by DanielYKPan** [comment]
Which version of the picker r u using?

I tested it, but it looked fine for me.

**Comment by Londeren** [comment]
`"ng-pick-datetime": "^6.0.10",`

**Comment by DanielYKPan** [comment]
Thanks. I saw the issue.

**Comment by DanielYKPan** [comment]
Updated the picker to latest version.
Now the picker position has been optimised. And `owl-date-time` also has a new property `[scrollStrategy]` which accept ScrollStrategy object from angular/cdk.
