### ISSUE TITLE
Datepicker 'dateTimeChange' event not fire on selected date

### ISSUE THREAD

**Issue by tarunmishra592** [DanielYKPan/date-time-picker#415]
Open [demo page](https://danielykpan.github.io/date-time-picker/) Chrome and scroll to basic example.
Tap on basic input. Datepicker opens.
Tap on same date which is selected. Datepicker does not close.
The Datepicker should close tap on selected date.

**Comment by DanielYKPan** [comment]
`dateTimeChange` event of course not being fired if you on select the already selected date. It only be fired if the date time value changed.

I would fixed be issue `picker not close if tap on the selected date` issue in the next update.

**Comment by unspike** [comment]
@DanielYKPan Hey, could you provide the changes or when the new update will be released? thx.
