### ISSUE TITLE
New possible feature: [disabledDates]="invalidDates" [disabledDays]="[0,6]"

### ISSUE THREAD

**Issue by alexsintoni** [DanielYKPan/date-time-picker#416]
Hi,

as usual I thank you for your help and great tool.
I was thinking if it is possible to add a new feature for this data-time-picker to disable the selection of specific dates or days (Monday, Tuesday, ...) maybe passing to arrays as input to the component like:

```
<owl-date-time
                          ...
                          [disabledDates]="invalidDates"
                          [disabledDays]="[0,6]">
                          ...
</owl-date-time>
```

[PrimeNG Calendar](https://www.primefaces.org/primeng/#/calendar) has similar fetaure.
It would be great to have it here too.

Again thanks a million

**Comment by Kremlick** [comment]
I could also use an eventDate for special days that i want to know when im using the datepicker.

**Comment by DanielYKPan** [comment]
No need for this. Because there is a property `[owlDateTimeFilter]`, and you could provide a function to filter dates. You could read more about this from the README.md and demo page.

**Comment by alexsintoni** [comment]
Hi @DanielYKPan 
thanks a million for your help. I tried it and it works fine.
