### ISSUE TITLE
Not working with Angular Material

### ISSUE THREAD

**Issue by saravanaams** [DanielYKPan/date-time-picker#418]
Hi,

I'm using material with Angular 6.

I have tried integrating this plug-in in my application.

I'm getting the below error.

![image](https://user-images.githubusercontent.com/8102616/42987051-82d5ccea-8c15-11e8-99e8-2ac470c14c1b.png)

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by saravanaams** [comment]
Hi,

[https://angular-qatkhn.stackblitz.io/](url)

Please check this link

**Comment by DanielYKPan** [comment]
Your link is a dead link.

**Comment by saravanaams** [comment]
![image](https://user-images.githubusercontent.com/8102616/42993340-c22302e2-8c28-11e8-9f86-7c500db8b4f1.png)

It's not at all loading after adding the code

**Comment by saravanaams** [comment]
**app.module.ts**
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

import {MatButtonModule,MatCheckboxModule,MatCardModule,MatGridListModule,MatInputModule,MatFormFieldModule,MatIconModule,MatToolbarModule,MatSelectModule,MAT_LABEL_GLOBAL_OPTIONS, MatSidenavModule, MatListModule,MatDatepickerModule } from '@angular/material';

import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    OwlDateTimeModule, 
    OwlNativeDateTimeModule,
    FormsModule
  ],
  exports:[ ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { 
  
}
`
**app.component.html**
`<mat-form-field owlDateTimeMaterialTrigger [autoDialog]="true">
            <input [owlDateTime]="dt" matInput readonly placeholder="Select the date and time" [(ngModel)]="startDate">
            <owl-date-time #dt></owl-date-time>
          </mat-form-field>`

And i have followed the steps you have mentioned in Github.
