### ISSUE TITLE
Classes instead of colors

### ISSUE THREAD

**Issue by iCodr8** [DanielYKPan/date-time-picker#42]
On every hover or an another action, the color changes via "style"-tag. This is nice, but there should be an additional class, so that the styling it could be overwritten via css.

**Comment by DanielYKPan** [comment]
@iCodr8 
I have an option [theme] to customise the color of the picker. If there was an additional class to overwritten the style, it would not have any effect as the javascript styling has a higher priority.

Are you suggesting that I should not customise the picker color via javascript?

Cheers.

**Comment by iCodr8** [comment]
The problem is that the theme option is not enough for me. I need more flexibility than to only change the color. So it would be nice to add an additional class to that parts where the style tag is used.

For example:

`.picker-day` is on every day, but on today and the current selected item is not an extra class. Only the style tag is different.

So it would be nice to have for example the classes `picker-day picker-day-today` and `picker-day picker-day-current` on the class tag.

**Comment by DanielYKPan** [comment]
@iCodr8 
I got what you mean.
Thanks for the suggestion. I will look at it in next couple days.

**Comment by DanielYKPan** [comment]
@iCodr8 

I added **picker-day-today** for today, **picker-day-selected** for the day you selected, **picker-month-current** for the month displayed, **picker-year-current** for the year displayed.

What else classes should I add?

**Comment by iCodr8** [comment]
I think that's enough.

**Comment by DanielYKPan** [comment]
@iCodr8 
Update to version 4.1.2, it should be alright.
