### ISSUE TITLE
[feature] Add ability to set picker identifier dynamically

### ISSUE THREAD

**Issue by thomasbird1984** [DanielYKPan/date-time-picker#420]
So I have an app where I created a wrapped around the `date-time-picker`, it would be nice to be able to dynamically set `dt1` instead of it having be a fixed static identifier.

```html
<input [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1" placeholder="Date Time">
<owl-date-time #dt1></owl-date-time>
```

**Comment by DanielYKPan** [comment]
there is no way to do that
