### ISSUE TITLE
min Date with Format

### ISSUE THREAD

**Issue by steBancaNovara** [DanielYKPan/date-time-picker#425]
how can I set minDate with <owl-date-time-inline>? 
<owl-date-time-inline [min]="min" [(ngModel)]="dateSelected" [pickerType]="'calendar'"></owl-date-time-inline>  

min:Date=new Date().
 How can I set new Date('dd/MM/yyyy')?

**Comment by DanielYKPan** [comment]
min date format is the same as you dateSelected format.
'How to set your dateSelected format' could be found [here](https://danielykpan.github.io/date-time-picker/#locale-formats)

**Comment by steBancaNovara** [comment]
Ok. I 've asked format date because I can't set min as current Date with min=new Date().

**Comment by steBancaNovara** [comment]
How can I set min as current Date? It doesn't work with min=new Date().
