### ISSUE TITLE
Set date clicking outside

### ISSUE THREAD

**Issue by juankmarin** [DanielYKPan/date-time-picker#427]
Hi, is possible set the selected date-time when you click outside the picker?

**Comment by DanielYKPan** [comment]
No idea what you mean by 'clicking outside the picker and selecting date'

**Comment by MarkovEvgeni** [comment]
I suppose that **juankmarin** means selecting the date by closing the dialog and not clicking the "Set" button.

**Comment by DanielYKPan** [comment]
If the picker is a calendar only, there is no "Set" btn and it would selecting the date by closing the dialog.
But if there is a timer, it would be a "Set" btn to confirm the value.

**Comment by darrynhoskingluna** [comment]
+1 on this as a feature, it should set the date time on focus lost / clicking out of the time picker. This has been a stumbling block for the users of my website as they never click set and dont realise the date & time they have configured has not actually been reflected into the input box.
