### ISSUE TITLE
Help !!! Input doesnt show seconds value. [showSecondsTimer]="true" is set

### ISSUE THREAD

**Issue by azstate** [DanielYKPan/date-time-picker#428]
I have set the [showSecondsTimer]="true" but when I set time (Hrs, Mins, Secs) popup closes and in the input section I can see only the Date Hrs and Mins. Seconds are missing 

How to show seconds in the input text box?? 

    <label class="example-input-wrapper">
        Date Time:
        <input placeholder="Date Time:"
               [(ngModel)]="dateTime"
               [owlDateTimeTrigger]="dt" [owlDateTime]="dt" [owlDateTimeFilter]="">
        <owl-date-time #dt [showSecondsTimer]="true"> </owl-date-time>
    </label>

**Comment by DanielYKPan** [comment]
showSecondsTimer would make the picker has a box to configure the seconds value.
If you want to show the second value in your input, you have to configure the format. You could learn more about the format from [here](https://danielykpan.github.io/date-time-picker/#locale-formats)

**Comment by rajantha** [comment]
I also encountered the same issue. I have configured my native format as follows.

export const MY_NATIVE_FORMATS = {
    fullPickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric'},
    datePickerInput: {year: 'numeric', month: 'numeric', day: 'numeric'},
    timePickerInput: {hour: 'numeric', minute: 'numeric', **second: 'numeric**'},
    monthYearLabel: {year: 'numeric', month: 'short'},
    dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
    monthYearA11yLabel: {year: 'numeric', month: 'long'},
};
