### ISSUE TITLE
Time showing in input field for picker type calendar

### ISSUE THREAD

**Issue by laijuthomas** [DanielYKPan/date-time-picker#429]
I have an reactive form input field which have a date value coming from API. 
```
<input class="form-control" [owlDateTimeTrigger]="dt1" [owlDateTime]="dt1" formControlName="order_date" placeholder="mm/dd/yyyy">
<owl-date-time [pickerType]="'calendar'" #dt1 ></owl-date-time>
```
The issue is even though I am passing only date value, the input shows time also. But when I click on the picker the time goes.

I just want to show only date . Someone already mentioned about this issue earlier #247

**Comment by DanielYKPan** [comment]
It should be already be fixed. What version of the picker are u using?

**Comment by DanielYKPan** [comment]
I tested it and it works fine to me.

Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by laijuthomas** [comment]
Here is StackBlitz link
https://angular-ogtn4q.stackblitz.io

**Comment by DanielYKPan** [comment]
Share the code as well. The link you provided is only a demo.

**Comment by laijuthomas** [comment]
Updated the StackBlitz link

**Comment by DanielYKPan** [comment]
No. It still only the demo. Share it with the code panel.

**Comment by laijuthomas** [comment]
https://stackblitz.com/edit/angular-ogtn4q

**Comment by DanielYKPan** [comment]
Update the picker to latest version. The issue should be fixed.

**Comment by laijuthomas** [comment]
Its fixed now. Thank you
