### ISSUE TITLE
Buttons are not localized

### ISSUE THREAD

**Issue by nrbw** [DanielYKPan/date-time-picker#43]
I tried to use date-time-picker today and used the localized version with [locale]="'fr'".
It works well but the buttons are not localized and still displayed in english.

Is there a way to localize buttons ?

**Comment by DanielYKPan** [comment]
@nrbw 
This is because I haven't implemented the locale for 'fr'.
Could you please help me to build it?

`
LANG_EN_TRANS = {
    'time picker': 'Time Picker',
    'today': 'Today',
    'set time': 'Set Time',
    'close': 'Close',
    'confirm': 'Confirm',
    'hour': 'Hour',
    'minute': 'Minute',
    'second': 'Second',
};
`

**Comment by nrbw** [comment]
Some translations are not easy to adapt, here's a first shot:


Time Picker: Choix du temps
Today: Aujourd'hui
Set Time: Modifier l'heure
Close: Fermer
Confirm: Confirmer
Hour: Heure
Minute: Minute
Second: Seconde

**Comment by nrbw** [comment]
Some translations are not easy to adapt, here's a first shot:


Time Picker: Choix du temps
Today: Aujourd'hui
Set Time: Modifier l'heure
Close: Fermer
Confirm: Confirmer
Hour: Heure
Minute: Minute
Second: Seconde

**Comment by DanielYKPan** [comment]
@nrbw 
All right, thanks.

It will be in next update.

**Comment by nrbw** [comment]
As a side question, when do you plan to release a version with this commit ?

**Comment by DanielYKPan** [comment]
@nrbw 
The reason why I haven't released a new version because there are still bugs.

Hopefully, it will be done in this weekend.
cheers.

**Comment by DanielYKPan** [comment]
@nrbw 
Update to package version 4.1.2

Cheers.

**Comment by nrbw** [comment]
Thanks @DanielYKPan , I have a better view in situation. May I give better translations for 2 items ?

Time Picker: Choisir l'heure
Set Time: Confirmer l'heure

**Comment by nrbw** [comment]
I've issued a pull request for the new translation
