### ISSUE TITLE
Possibility to click directly on 'From' to 'To' for Picker with rangeFrom and rangeTo selection

### ISSUE THREAD

**Issue by alexsintoni** [DanielYKPan/date-time-picker#430]
Hi,

I wrote it many times but I really like this component so I use it a lot.

In one project I used the feature Picker with rangeFrom and rangeTo selection with 2 input:

```
<label>
    Date Time Range From:
    <input [owlDateTimeTrigger]="dt12" [owlDateTime]="dt12"
           [(ngModel)]="selectedMoments"
           [selectMode]="'rangeFrom'">
    <owl-date-time #dt12></owl-date-time>
</label>

<label>
    Date Time Range To:
    <input [owlDateTimeTrigger]="dt13" [owlDateTime]="dt13"
           [(ngModel)]="selectedMoments"
           [selectMode]="'rangeTo'">
    <owl-date-time #dt13></owl-date-time>
</label>
```
It came in my mind that, to be more efficient from the user point of view, it would be good to be able to click directly on 'From' and 'To' part of the view instead of closing the from calendar and open the to calendar. 
Also because if I already wrote the to calendar but I want to change the from I have to close it again, etc... 
For the user would be better to be able to change from and to just with one view without closing it.

What do you think?

Again thank you for your help

**Comment by DanielYKPan** [comment]
Year, that situation would be in 'range' mode.

**Comment by alexsintoni** [comment]
Hi @DanielYKPan ,

yes like in 'range' mode but I would prefer to show to the users 2 <input ...> components so I can write specifically 2 lables 'From' and 'To' instead of having the single <input> and showing ~ in the range.

Do you think it is possible for you? or too complicated?

Anyway thanks again for your help.

**Comment by DanielYKPan** [comment]
I have no idea what you try to do.
If you have to tow inputs for tow pickers, then you have to confirm the value for each inputs and you can not change the value (B input) from picker A.
