### ISSUE TITLE
How to have non editable Date, user can change the time.

### ISSUE THREAD

**Issue by azstate** [DanielYKPan/date-time-picker#432]
I am using the custom formatting. In the datetime picker popupp user can change only the Time field. I want to fix the date to today's date. Only time can be changed.
How to achieve this?

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by azstate** [comment]
I am using this 
    <label class="example-input-wrapper">
        Date Time:
        <input placeholder="Date Time:"
               [(ngModel)]="dateTime"
               [owlDateTimeTrigger]="dt" [owlDateTime]="dt" [min]="dateTime" [max]="dateTime">
        <owl-date-time #dt [showSecondsTimer]="true"></owl-date-time>
    </label>

it is from https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker?file=src%2Fapp%2Fmoment-js%2Fmoment-js.component.html

If I set min and max it allows take current date only. But it restricts time too. I want time to be editable.

**Comment by azstate** [comment]
I want user to change the time and not the date. Date should be todays date. User should not be able to select any other date. If I set the min/max value it restricts the date selection but at the same time it restricts the time selection as well. I want time drop down enabled.

**Comment by DanielYKPan** [comment]
Then you may consider to use the picker as timer (set pickerType to timer), and set the min to something like 2018/08/02, 00:00:00 and max to something like 2018/08/02 23:59:59

**Comment by azstate** [comment]
Okay. Thank you Daniel. I was thinking of that option but I want to show date as well. As it is required in some other scenario. So in the current implementation there is no way to have both and disable one.

**Comment by gregor-srdic** [comment]
you can hide the input, connected to opening the datepicker modal (opacity:0), invoke click event on it from some other button, and display the date manually ...
