### ISSUE TITLE
How can I increase animation speed?

### ISSUE THREAD

**Issue by issy123** [DanielYKPan/date-time-picker#433]
Takes 2 seconds for that thing to popup

**Comment by DanielYKPan** [comment]
There is no way to customise the animation speed.
The popup picker animation speed is 100ms
And the dialog picker animation speed is 500ms.

You could disable the angular animation by importing `NoopAnimationsModule`

**Comment by issy123** [comment]
Well i like the animation, don't like the speed. Could there be any way in the future to configure this?

importing `NoopAnimationsModule` might ruin other animations doesn't it?

**Comment by DanielYKPan** [comment]
I think the default speed is quite reasonable. I don't know why you need 2 seconds to to finish the popup animation

**Comment by issy123** [comment]
Well just to make it faster, it felt like 2 seconds.
I appreciate your time and if it isn't possible I can understand it totally
