### ISSUE TITLE
Wrong format in picker input

### ISSUE THREAD

**Issue by vvip-68** [DanielYKPan/date-time-picker#434]
I have two <owl-date-time> picker on page. Picker uses Moment date formatting.
`<owl-date-time #dtpicker [firstDayOfWeek]="fieldLabelConstants.firstDayOfWeek"  panelClass="ntp-dt-calendar-popup">
...
</owl-date-time><owl-date-time #dtp_start [firstDayOfWeek]="fieldLabelConstants.firstDayOfWeek" panelClass="ntp-dst-popup" pickerType="calendar" startView="year"></owl-date-time>`
First picker type defined as "both", second as "calendar". Although I think bug is occurs even if single picker of type "calendar" is used...
Moment formatter is:
`export const MOMENT_CUSTOM_FORMATS = {
  parseInput: 'DD-MMM-YY, HH:mm',
  fullPickerInput: 'DD-MMM-YY, HH:mm',
  datePickerInput: 'MMM-DD',
  timePickerInput: 'HH:mm',
  monthYearLabel: 'MMMM YYYY',
  dateA11yLabel: 'LL',
  monthYearA11yLabel: 'MMMM YYYY',
};
`
Pay attention in difference in format in "both" and 'calendar' type.
At the Picker component initialization first I see call of:
`    Object.defineProperty(OwlDateTime.prototype, "formatString", {
        get: function () {
            return this.pickerType === 'both' ? this.dateTimeFormats.fullPickerInput :
                this.pickerType === 'calendar' ? this.dateTimeFormats.datePickerInput :
                    this.dateTimeFormats.timePickerInput;
        },
        enumerable: true,
        configurable: true
    });
`
in date-time.class.js (here pickerType has default value 'both' and get formatString from fullPickerInput), next follow call of
`
    Object.defineProperty(OwlDateTimeComponent.prototype, "pickerType", {
        get: function () {
            return this._pickerType;
        },
        set: function (val) {
            if (val !== this._pickerType) {
                this._pickerType = val;
                if (this._dtInput && this.initiated) {
                    this._dtInput.formatNativeInputValue();
                }
            }
        },
        enumerable: true,
        configurable: true
    });
`
in date-time-picker.component.js; here this.initiated is false and format string stay unchanged as fullPickerInput.
After page is rendered, <input> field related with picker is formatted as fullPickerInput. Only after picker reselect value from popup, displayed value format changed to datePickerInput.

**Comment by DanielYKPan** [comment]
relative to #429

**Comment by DanielYKPan** [comment]
Update the picker to latest version. The issue should be fixed.
