### ISSUE TITLE
Edit seconds in the inputfield

### ISSUE THREAD

**Issue by issy123** [DanielYKPan/date-time-picker#436]
When I set `showSecondsTimer` to true, i am able to edit the seconds in the fancy GUI. However I would like to display and edit the seconds in the inputfield.

How?

**Comment by DanielYKPan** [comment]
`showSecondsTimer` would make the picker have a timer box for second value. If you want to have the seconds in the input field, you have to config a new dateTime format. You could learn more from [here](https://danielykpan.github.io/date-time-picker/#locale-formats)

**Comment by issy123** [comment]
Thanks! 
Sidenote: 
you have to use `import { OwlMomentDateTimeModule } from 'ng-pick-datetime-moment';` for the formats to work.
Source: https://github.com/DanielYKPan/date-time-picker/issues/246
