### ISSUE TITLE
Inputfield edit date does not reflect the ngmodel

### ISSUE THREAD

**Issue by issy123** [DanielYKPan/date-time-picker#437]
using `"ng-pick-datetime": "^6.0.10"`
When I edit the input field (not GUI) and try to change the month to the next month it will return `null`

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Comment by issy123** [comment]
Good thing you mentioned that, i was not able to reproduce this bug!
