### ISSUE TITLE
Time in Input not updated

### ISSUE THREAD

**Issue by Observablerxjs** [DanielYKPan/date-time-picker#439]
Steps to reproduce:
1- open the demo: https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker?file=src%2Fapp%2Fmoment-js%2Fmoment-js.component.html
2- go to 'Setting the Calendar Start View' and click on the input 'Date Time (picker starts at specific moment): ' 
3- choose for example 14:30 (or any value different of 10:30)
4- click a second time on the input 'Date Time (picker starts at specific moment): ' 
5- and just press set without changing anything

Actual output: the time displayed is not updated and stays at 14:30. It seems that the ngModel isn't updated correctly.

Expected output: the time displayed is 10:30

**Comment by DanielYKPan** [comment]
ngModel is updated correctly.

That example shows you what ever your ngModel value is, the picker would always starts at at specific moment.

**Comment by Observablerxjs** [comment]
I agree that the picker always start at a specific moment (10:30 in the example), however setting ngModel isn't correct, at least from a logical point of view. After the step 3, ngModel = " Sun Mar 03 2019 **14:30:30** GMT-0500 (Eastern Standard Time)" which is correct. After step 5 logically ngModel should be updated to : " Sun Mar 03 2019  **10:30:30** GMT-0500 (Eastern Standard Time)" but the time displayed is still 14:30:30. Hope it's clear enough.

**Comment by DanielYKPan** [comment]
Updated to latest version. Issue should be fixed.
