### ISSUE TITLE
Range from date field option , date is not binding when when we change the pickerType to calendar.

### ISSUE THREAD

**Issue by lijugeorgedev** [DanielYKPan/date-time-picker#440]
`<label class="example-input-wrapper">
        Date Time Range From:
        <input placeholder="Date Time Range From:"
               [(ngModel)]="dateTimeRange"
               [selectMode]="'rangeFrom'"
               [owlDateTimeTrigger]="dtRange2" [owlDateTime]="dtRange2">
        <owl-date-time #dtRange2 [pickerType]="'calendar'"></owl-date-time>
      ##</label>`

Stackblitz link : https://stackblitz.com/edit/github-fxdejx

**Comment by DanielYKPan** [comment]
Updated to latest version. Issue should be fixed.
