### ISSUE TITLE
Time picker in Chrome and IE shows different time

### ISSUE THREAD

**Issue by azstate** [DanielYKPan/date-time-picker#441]
Hello, I am using time picker and it works perfectly fine in chrome.
But the same code in IE shows different time. Time is 4pm (MST) when I click on time picker the default selected time is 8pm. Is there any other setting required in IE?

**Comment by DanielYKPan** [comment]
The Demo page examples works fine to me in both Chrome and IE.

Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.
