### ISSUE TITLE
Angular reactive forms: unable to use patchValue 

### ISSUE THREAD

**Issue by deepakkr09** [DanielYKPan/date-time-picker#443]
dateInput(date) {
    date = this.dateFormat(date).toString();
    this.form.controls[this._date.key].patchValue(date);
  }
  dateFormat(date) {
    const day = date.getDate();
    let month = date.getMonth() + 1;
    if (month < 10) {
      month = '0' + month;
    }
    const year = date.getFullYear();
    const hour = date.getHours();
    const minutes = date.getMinutes();
    const seconds = date.getSeconds();
    const time = hour + ':' + minutes + ':' + seconds;
    const dateChange = year + '-' + month + '-' + day;
    if (this._date.module === 'societyContainer') {
      return dateChange;
    } else if (this._date.module === 'valdityForInviteCodeContainer') {
      date = dateChange + ' ' + time;
      return date;
    }
  }

<---HTML-->
<div class="margin_left" [formGroup]="form">
  <mat-form-field class="date-width">
    <input matInput [min]="_date.minDate" [placeholder]="_date.placeholder" [formControlName]="_date.key" [owlDateTimeTrigger]="dtPicker2"
      (dateTimeChange)="dateInput($event.value)" [owlDateTime]=" dtPicker2 ">
    <owl-date-time #dtPicker2></owl-date-time>
  </mat-form-field>
</div>

When dateInput function is called It clear out input without patching any value.

**Comment by DanielYKPan** [comment]
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.
