### ISSUE TITLE
Unable to set date time range programmatically

### ISSUE THREAD

**Issue by AlexBokhankovich** [DanielYKPan/date-time-picker#446]
I need to set date time ranges programmatically by button press. When I set array element at position 0 or 1 nothing change in input. So, how can I set date time programmatically?
Please see changed RangeComponent https://stackblitz.com/edit/github-deglx3?file=src%2Fapp%2Frange%2Frange.component.html for repro.

**Comment by DanielYKPan** [comment]
the way you set the [0] value could not trigger ngModel to detect change.
You need create a new array.

**Comment by AlexBokhankovich** [comment]
Thank you a lot, that did the trick
