### ISSUE TITLE
Disbale previous dates

### ISSUE THREAD

**Issue by macin40** [DanielYKPan/date-time-picker#447]
Can someone help me to disable the past , so that user cannot select the past dates??
- Thanks in Advance

**Comment by DanielYKPan** [comment]
There is a min, max and filter properties. Please read the README.md and the demo page

**Comment by macin40** [comment]
@DanielYKPan Thanks...... I got this, actually I was passing wrong format to `min` field.

**Comment by ratiuandreea** [comment]
I found a little problem here.
I have a picker of type calendar and I am trying to disable the previous dates.
I have a min value set up pretty simple: min = moment(); but what happens is that now I cannot select today anymore. It is enabled as if I can select it, but when I click on it, it does not get selected. 
Is this a know issue or is this fixable?
