### ISSUE TITLE
Min value that we set in component not getting set if we change picker type to calendar

### ISSUE THREAD

**Issue by lijugeorgedev** [DanielYKPan/date-time-picker#448]
If we set the minimum value to current date then we can't set that date if pickertype is calendar

`<label class="example-input-wrapper">
        Date Time:
        <input placeholder="Date Time:"
               [(ngModel)]="dateTime1"
               [min]="min" [max]="max"
               [owlDateTimeTrigger]="dt1" [owlDateTime]="dt1">
        <owl-date-time [pickerType]="'calendar'" [startAt]="startAt" #dt1></owl-date-time>`

**Comment by DanielYKPan** [comment]
You need to set the min to current date with 0 hour, 0 minute and 0 second

**Comment by lijugeorgedev** [comment]
thanks man it actually set to the current time. Sorry for the trouble
