### ISSUE TITLE
Issue with datepicker on mobile device when opening in a modal window & usage of class .footer

### ISSUE THREAD

**Issue by djlatscho** [DanielYKPan/date-time-picker#45]
I use the datepicker in a moda window. When you want to open it on a mobile device, the footer is cut off.

![bildschirmfoto 2017-05-12 um 11 08 04](https://cloud.githubusercontent.com/assets/5719156/25991490/9abe0ede-3703-11e7-9555-d4f4652ed59d.png)

When I deselect the height in class .picker-popup it gets shown completely.

![bildschirmfoto 2017-05-12 um 11 08 14](https://cloud.githubusercontent.com/assets/5719156/25991521/b65493ac-3703-11e7-86fc-dd426fc375ca.png)

You can find the class .picker-popup in dialog.component.js in line 175. I deleted height:100% and now it works fine for me. I tried to overwrite it with CSS, but for that I am not smart enought. ;-) Maybe you can give me a hint how to do that. That does not work:
```
.picker-popup {
height: auto !important;
}

```

Another thing is that you use a class called .footer. This gets overwritten, if someone uses the same class. Maybe you change that to a more individual name to prevent race conditions in any ways.

**Comment by djlatscho** [comment]
Overwriting the CSS worked. I tried at the wrong place in my css files.

**Comment by DanielYKPan** [comment]
@djlatscho 
Update package to version 4.1.2 and it should be alright.
