### ISSUE TITLE
Missing range 

### ISSUE THREAD

**Issue by LostInAngular** [DanielYKPan/date-time-picker#450]
Hi Daniel,

i have a bug for you (or at least I think it's a bug).

if you go to your [StackBlitz](https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker) and follow these steps:

1) Find the range selection and click to open it.
2) choose start date in august and end date in September.
3) When you choose the end date in September, the calendar will move to September page so click < (left arrow) to go back to august. ![step3](https://user-images.githubusercontent.com/42342183/44041159-03490952-9f15-11e8-84f6-3fe427a722a7.PNG)
4) Now if you change time, your selection of days disappears and both start date and end date will point to 6th of august.
![step3](https://user-images.githubusercontent.com/42342183/44041264-48fe7e0a-9f15-11e8-9f0f-3c9fae781126.PNG)

**Comment by DanielYKPan** [comment]
I don't think this is a bug. Because when you change back to Aug, the picker's value now point to Aug 6, and when you change to time, it change the time of Aug 6
