### ISSUE TITLE
Time picker shows different time on select

### ISSUE THREAD

**Issue by azstate** [DanielYKPan/date-time-picker#451]
Hello, I am using the custom date time picker.
I have populated the time in the input field, when I click on the text box it shows different time in Time Picker. If text box is empty it shows the correct time. What am I doing wrong while assigning value to textbox. I am assigning the time this way
this.myTime  = new moment(new Date(), 'M/D/YYYY h:mm:ss a');

**Comment by azstate** [comment]
It works fine in chrome. I am facing this issue only in IE

**Comment by DanielYKPan** [comment]
The Demo page examples works fine to me in both Chrome and IE.

Please use StackBlitz to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.
