### ISSUE TITLE
Styling issues with Bootstrap v3.7

### ISSUE THREAD

**Issue by atom-morgan** [DanielYKPan/date-time-picker#452]
I recently upgraded `date-time-picker` to v6.0.15 and I'm getting a weird styling conflict with Bootstrap v3.7.

<img width="587" alt="screen shot 2018-08-12 at 3 53 41 pm" src="https://user-images.githubusercontent.com/3698634/44066300-8f715844-9f3d-11e8-9f2e-f8f505d8d447.png">

As you can see, the picker is much smaller than it's default and this is only happening once I add Boostrap to `angular.json`.

```
"styles": [
  "node_modules/bootstrap/dist/css/bootstrap.min.css",
  "node_modules/ng-pick-datetime/assets/style/picker.min.css",
  "src/styles.css"
],
```
Has anyone else run into this issue with a possible solution?

The picker displays normally without Bootstrap.

**Comment by DanielYKPan** [comment]
this is because the picker is designed responsive. And when you and the bootstrap, the bootstrap change your font size of your web.

Change the font size of the picker could solve the problem.

**Comment by atom-morgan** [comment]
Thanks @DanielYKPan. In case anyone else stumbles upon this the solution is as follows:

```css
::ng-deep .owl-dt-container {
  font-size: 1.5rem;
}
```

**Comment by jondoes** [comment]
Hey @atom-morgan  , Are you facing this type of issue ? 

![Screenshot from 2019-04-20 11-26-10](https://user-images.githubusercontent.com/5745996/56453630-d56ac580-6362-11e9-95ed-50d2ae7a19bf.png)

I'm facing this issue. Can you help to fixed this issue ?
