### ISSUE TITLE
Change appearance of current visible date format

### ISSUE THREAD

**Issue by macin40** [DanielYKPan/date-time-picker#456]
Hello , I want to change the current date format to `yyyy-mm-dd hh-mm` with 24 hr date format,
Please help! 
Thanks in advance
![image](https://user-images.githubusercontent.com/22330484/44381832-be53a980-a52f-11e8-9517-28e8c2cd1cb9.png)

**Comment by darwin4416** [comment]
Did you checked this tutorial https://danielykpan.github.io/date-time-picker/

**Comment by NandKishorrech** [comment]
export const DATE_NATIVE_FORMATS = {
fullPickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', hour12: false},
datePickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour12: false},
timePickerInput: {hour: 'numeric', minute: 'numeric', hour12: false},
monthYearLabel: {year: 'numeric', month: 'short'},
dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
monthYearA11yLabel: {year: 'numeric', month: 'long'},
};

add this line at module.ts:
{ provide: OWL_DATE_TIME_FORMATS, useValue: DATE_NATIVE_FORMATS },

**Comment by macin40** [comment]
> export const DATE_NATIVE_FORMATS = {
> fullPickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', hour12: false},
> datePickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour12: false},
> timePickerInput: {hour: 'numeric', minute: 'numeric', hour12: false},
> monthYearLabel: {year: 'numeric', month: 'short'},
> dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
> monthYearA11yLabel: {year: 'numeric', month: 'long'},
> };

Not working , just the timeformat is changed! Rest remains the same
Can you help me in formatting in  ```yyyy-mm-dd hh-mm```
