### ISSUE TITLE
Date is being submitted before I select it.

### ISSUE THREAD

**Issue by jasmincore** [DanielYKPan/date-time-picker#46]
As I open the dialog the current moment is submitted without any event select date or click on confirm button.

It submits date which I set as the default date. It submits the given value by default without any instructions?

      <button *ngIf="selectedMeeting?.startDateTime" **[dateTimePicker]="selectedMeeting.startDateTime"** class="btn btn-row " (dateTimePickerChange)="onDateTimeChanged($event,'start')" [disabled]="!isOrganizer() || isStartedOrCompleted()">
                <span>Starts</span><span class="sbi-blue">{{selectedMeeting.startDateTime | commonDate:'D MMM YYYY  HH:mm' }}</span>
            </button>

**Comment by DanielYKPan** [comment]
@jasmincore 
I guess this is because you used the directive in the html button tag.

Try to use it in a input tag and it should be fine.

**Comment by jasmincore** [comment]
Thanks very much for the quick replay. Will try it.

**Comment by jasmincore** [comment]
<input type="text" *ngIf="selectedMeeting?.startDateTime" [ngModel]="selectedMeeting.startDateTime | commonDate:'D MMM YYYY  HH:mm'" [dateTimePicker]="selectedMeeting.startDateTime" class="btn btn-row " (dateTimePickerChange)="onDateTimeChanged($event,'start')" [disabled]="!isOrganizer() || isStartedOrCompleted()">


A problem still persists after change control button to input.

**Comment by DanielYKPan** [comment]
What do you mean by "Date is being submitted"?

**Comment by rorystandley** [comment]
I think I understand what the issue is. I have noticed this also. 

`(dateTimePickerChange)="setMoment($event)`

This is triggered when a user clicks on a day, it is then also triggered again when you click on confirm.

**Comment by jasmincore** [comment]
Yes that was the issue.

**Comment by DanielYKPan** [comment]
Update ng-pick-datetime to latest version.

Now the picker would not return value by clicking a day. It only returns value by clicking on **Confirm** button. You could also overwrite this behaviour by setting `**[autoClose]=" true "**`

**Comment by jasmincore** [comment]
Yes. It works now. Thanks for the great support.
