### ISSUE TITLE
Change Date Output Value

### ISSUE THREAD

**Issue by akleimrey** [DanielYKPan/date-time-picker#461]
More of a support request than anything else... I mean, I have seen how the representational view can be changed, but in a form it's always in the ISO-8601 standard. But in the backend I have to send a date formatted more like this.
"31-08-2018"

**Comment by DanielYKPan** [comment]
This is not a part of the picker. The picker would only output Javascript Native Date Object (Moment Object if you use OwlMomentDateTimeModule)
