### ISSUE TITLE
Question: Usage with Bootstrap4?

### ISSUE THREAD

**Issue by kw-s** [DanielYKPan/date-time-picker#462]
Is there a way to use the picker with bootstrap4 or is it Angular Material - only?

**Comment by esejuli94** [comment]
I think it doesn't matter because it uses its own styles. You have to import them to your project with:
`@import "~ng-pick-datetime/assets/style/picker.min.css";`

I'm using MaterializeCSS and I just had to make some minor changes to fix some styles. But it shouldn't be a problem.
