### ISSUE TITLE
How to disable picker input?

### ISSUE THREAD

**Issue by arquadrado** [DanielYKPan/date-time-picker#463]
I need to disable the picker and the input but I have failed to do so. The picker works with the disabled prop as described in the documentation but the input does not. Just setting the `disabled` prop in the input does not work neither hacky solution of setting `[attr.disabled]="shouldDisable ? '' : null"`. Any clue one what might me wrong?

P. S.: If I remove the `owlDateTime` attribute from the input I can disable it normally.

**Comment by DanielYKPan** [comment]
use `[disabled]='true'` on your input

**Comment by arquadrado** [comment]
If you reread my comment you will see that I said that neither `[disabled]="true"` or `[attr.disabled]="disabledCondition ? '' : null"`. Like I said if I remove the `[owlDateTime]` attribute from the input element it works with `[disabled]="true"`. Any clues?

**Comment by arquadrado** [comment]
Try on the year-month component, where a formControl is used instead of ngModel.

**Comment by DanielYKPan** [comment]
If you are using formControl in your input, you can't just simply use `[disabled]="true"` to disable the input. This is another question. And you could google how to disable formControl input and this is not an issue from the picker.
