### ISSUE TITLE
24-Hour time format support

### ISSUE THREAD

**Issue by darshan-bodawala** [DanielYKPan/date-time-picker#465]
Here I have the requirement to show the 24-hour format of time in date-time picker. Currently there is provision to select the time in 24-hour format. However when we set the time, it shows time in 12-hour format. So can you please help me on this?

Current output: 8/28/2018, 6:00 PM
Expected output: 8/28/2018, 18:00

Thanks in advance.

**Comment by DanielYKPan** [comment]
You need to configure the date time format. Please read [her](https://danielykpan.github.io/date-time-picker/#locale-formats)

**Comment by NandKishorrech** [comment]
export const DATE_NATIVE_FORMATS = {
    fullPickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', hour12: false},
    datePickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour12: false},
    timePickerInput: {hour: 'numeric', minute: 'numeric', hour12: false},
    monthYearLabel: {year: 'numeric', month: 'short'},
    dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
    monthYearA11yLabel: {year: 'numeric', month: 'long'},
  };

add this line at module.ts:
{ provide: OWL_DATE_TIME_FORMATS, useValue: DATE_NATIVE_FORMATS },

**Comment by PrabakarKaruppasamy** [comment]
@NandKishorrech 

I have tried but it is not working. Can u please help me out. I shared below my angular Cli version and ng Date time Picker version.

ng-pick-datetime: ^5.0.0-beta.15
@angular/common: ~5.0.0,
@angular/compiler: ~5.0.0,
@angular/compiler-cli: ~5.0.0,
@angular/core": "~5.0.0,
