### ISSUE TITLE
Time picker allows us to add invalid character.

### ISSUE THREAD

**Issue by vigneshpkamath** [DanielYKPan/date-time-picker#466]
Steps to reproduce:
- Enter the valid time (numerals) to the time picker HH: MM. 
- Edit the value with alphabets.
- Click set.

Expected result:
- The user should be prevented from entering invalid time.

Actual result:
- Value gets reset to 12:00 AM in the input field.

Screenshot:

![timepicker](https://user-images.githubusercontent.com/16129807/44841874-04acb500-ac62-11e8-85aa-a717d7e93ab8.png)

**Comment by DanielYKPan** [comment]
Yes, this is actually intended behaviour.
If the user type any invalid value in timer input, it would reset it to 00.

**Comment by gangadharsm** [comment]
Hi,

same issue i m also facing.
Enter the character first time it converting to 00, after converted to 00, then again i enter the character , that time it is not converting to 00. 
issue is still exist. Please check
