### ISSUE TITLE
include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application

### ISSUE THREAD

**Issue by AhmadRaza786** [DanielYKPan/date-time-picker#467]
I am facing the issue with ng-pick-datetime. I have populated the date input field but whenever i click on the field it give me the following error.
`Found the synthetic property @backdropAnimate. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`

How can i resolve this error ?

**Comment by DanielYKPan** [comment]
Import either those module in your app module
