### ISSUE TITLE
Getting Injection error

### ISSUE THREAD

**Issue by Rachit-rkb** [DanielYKPan/date-time-picker#469]
Everything was working fine but when a created a new project and did npm install after that i got this error

### zone.js:388 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[DateTimeAdapter -> InjectionToken OWL_DATE_TIME_LOCALE]: 
  StaticInjectorError(Platform: core)[DateTimeAdapter -> InjectionToken OWL_DATE_TIME_LOCALE]: 
    NullInjectorError: No provider for InjectionToken OWL_DATE_TIME_LOCALE!
Error: StaticInjectorError(AppModule)[DateTimeAdapter -> InjectionToken OWL_DATE_TIME_LOCALE]: 
  StaticInjectorError(Platform: core)[DateTimeAdapter -> InjectionToken OWL_DATE_TIME_LOCALE]: 
    NullInjectorError: No provider for InjectionToken OWL_DATE_TIME_LOCALE!

**Using Angular 5 and similar compatible ng-pick-datetime**
Any idea?

**Comment by DanielYKPan** [comment]
Update your Angular version and Angular cdk version

**Comment by alok-srivastav** [comment]
My project is in **Angular5** and have **v5.2.6** of **ng-pick-datetime** installed. It runs fine on local but getting error on production build: 
![image](https://user-images.githubusercontent.com/34713672/47296213-340eeb00-d62f-11e8-84f2-549cf37f136f.png)

As I cannot update the angular version to 6. Please suggest any alternate way if.
