### ISSUE TITLE
Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.

### ISSUE THREAD

**Issue by OmkarJadhav21** [DanielYKPan/date-time-picker#470]
Here is  versions list
-----------------------------------------------------------------------------------
- Angular CLI: 1.7.4
-     "@angular/animations": "^5.2.0",
-     "@angular/cdk": "5.2.5",
-     "eonasdan-bootstrap-datetimepicker": "4.17.47",
-----------------------------------------------------------------------------------
I am using Angular 5 & install this datetimpicker using command 
`npm install ng-pick-datetime@5.2.6 --save`
I tried by changing the version of cdk upto 6.0.0 step by step ,also  I change the version of picker from 5 to latest but still this issue not solved.It occurs after building application using ` ng build --prod` .
___________________________________________________________
Here is the HTML-
` <mat-form-field>
                        <input matInput readonly type="text" placeholder=DateTime" [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1" formControlName="dateTime">
                        <owl-date-time #dt1></owl-date-time>
   </mat-form-field>`

**Comment by DanielYKPan** [comment]
#369

**Comment by viethien** [comment]
Hello @OmkarJadhav21 , did you fix this issue? I got same issue with angular 5.2.8 and ng-pick-datetime 5.2.6 ?
