### ISSUE TITLE
how can i use it in ie brower

### ISSUE THREAD

**Issue by fuzitu** [DanielYKPan/date-time-picker#471]
how can i use it in ie brower??
in chrom i can set time by` this.selectedMoments = [new Date(year, (month - 1), day, 0, 0), new Date(year, (month - 1), day, 23, 59)];`,but in ie 
![image](https://user-images.githubusercontent.com/25705181/44971157-1904f080-af87-11e8-95c2-6ae2a805244a.png) it does,t work!!

**Comment by DanielYKPan** [comment]
I don't the choice of browser matter.

Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.
