### ISSUE TITLE
Increase Font Size of Calendar Text

### ISSUE THREAD

**Issue by santoshgoswami2017** [DanielYKPan/date-time-picker#473]
Hello, 
I created a sample application with NPM in angular 6 and also import its css in style.scss file.
but when I check its output at that time its font-size is too small.
so I override its class to increase font-size but it also not work.

example:
.owl-dt-calendar-table .owl-dt-calendar-cell-content {
  font-size: 1.5em !important;
}

.owl-dt-calendar-table .owl-dt-calendar-cell {
  font-size: 1.5em !important;
}

so, how can i increase font-size of text ? 

![owel](https://user-images.githubusercontent.com/28086924/44975347-d25fc800-af7f-11e8-9ec1-5d0d01f63fe0.png)

**Comment by santoshgoswami2017** [comment]
ok... thanks

**Comment by suhas86** [comment]
Even i am facing same issue because i am using boostrap. I tried to override but it doesn't work.

**Comment by suhas86** [comment]
> ok... thanks

If you are still facing the issue you could place your css in global style.css

**Comment by akrzysztofek** [comment]
You can also try updating css style with: 

`.owl-dt-popup { transform-origin: left top;  transform: scale(1.5, 1.5); }`

It will proportionally increase control's size by 50%.
