### ISSUE TITLE
Missplaced calendar

### ISSUE THREAD

**Issue by adde71** [DanielYKPan/date-time-picker#474]
For some reason the calendar covers the entire field that triggers the calendar, any idea of how to solve this? (The field that triggered the calendar is hidden behind it)

<img width="352" alt="image" src="https://user-images.githubusercontent.com/24638505/45123700-0d245480-b168-11e8-8bba-00f11e3736c0.png">

**Comment by DanielYKPan** [comment]
This is intended behaviour. Normally, the picker would display under the input. But if there is not enough space under the input, the picker's place would be adjusted in order to show in the view.

**Comment by adde71** [comment]
The thing is that there's enough space for it to place under the input.

**Comment by DanielYKPan** [comment]
If that's the case, please use [StackBlitz](https://stackblitz.com/) to build an app to show the issue you mentioned above.
