### ISSUE TITLE
Issue with Month Year DatePicker max Date and Min Date Validation

### ISSUE THREAD

**Issue by jagan27101986** [DanielYKPan/date-time-picker#476]
Hi,
I am facing an issue when i have provided MIN and MAX date for OWL Month Year Calendar. The issue i am seeing is such that the expect min and max dates, all other month and year are disabled; however i am able to choose the other years and months irrespective of min and max date configuration.

Could you please check and provide a fix.

**Comment by DanielYKPan** [comment]
Actually, this is an intended behaviour. When there are min and max restrictions, months or years out of that min and max range could still be selectable. We still want to show the calendar of that month and year even it is not between min and max.

**Comment by jagan27101986** [comment]
Yes, however if want to restrict the month and year within min and max, how can I do it . Please advise, as my requirement is to choose only between min and max dates

**Comment by DanielYKPan** [comment]
As I said before, this is an intended behaviour. Min and Max could restrict the value you could choose. Months or years out of the min and max range could still be clickable to show the calendar of that month and year, but the dates on the calendar could be selected.

**Comment by alfaraj** [comment]
Hi Daniel, thanks for your efforts. Are you thinking to make this "intended behavior" as an optional functionality, to be added as a feature?

**Comment by smilingwq** [comment]
@DanielYKPan @jagan27101986 @alfaraj 
one way to prevent invalid year & month & day selectable, it works for me. Hopefully it helps .
```scss
.owl-dt-calendar-table .owl-dt-calendar-cell-disabled {
  pointer-events: none;
}
```
