### ISSUE TITLE
Change the font-color according to the theme

### ISSUE THREAD

**Issue by surazzarus** [DanielYKPan/date-time-picker#478]
I am able to change the background color according to my theme using `panelClass` and it does change. But how can I change the font-color?

**Comment by DanielYKPan** [comment]
through you css, just like the way you set the background color. You could inspect the original css in your browser's developer tools.

**Comment by Thomas0921** [comment]
> I am able to change the background color according to my theme using `panelClass` and it does change. But how can I change the font-color?

You can find the **picker.min.css** in your **node_modules>ng-datetime-picker>asset**, you can change all the blue theme to the color you prefer. happy coding
