### ISSUE TITLE
on Chrome, hours and minutes sliders are not updated correctly

### ISSUE THREAD

**Issue by dmesmin** [DanielYKPan/date-time-picker#48]
on Chrome, hours and minutes are not updated correctly while using sliders.
The values written on the slider buttons and the time header are not updated

![issuechrome](https://cloud.githubusercontent.com/assets/2893508/26112160/1e933760-3a25-11e7-87ba-2471972d461e.png)

On the screenshot, you can see that the hour slider has been dragged to '20' but the values haven't been updated on the button and in the header.
As soon as the mouse hover the 'set time' button, the values are updated

**Comment by DanielYKPan** [comment]
@dmesmin 
It is hard to debug from the inform you provided, as I tested it on chrome and didn't get the result you had.

Can you provide more inform about how you got this result?
did this result have any console error?
what's your app setting?
what version of angular you r running?

**Comment by dmesmin** [comment]
Hi Daniel,
Here is a live version with the issue https://test-calendar-dd4ba.firebaseapp.com/

Code for the input:
`<input class="picker-input" [ngModel]="myDate" [(dateTimePicker)]="myDate" [mode]="'dropdown'" (dateTimePickerChange)="setValue(myDate)">`

More details:
This sample is built using ionic and angular 4.1.0.
No console error, it's quite working actually except the hour and minute 'updates'

**Comment by DanielYKPan** [comment]
@dmesmin 
That's odd. I would look at it and try to fix it. Thanks for you details.

**Comment by DanielYKPan** [comment]
@dmesmin 
I tested it in a new blank ionic project and it worked well.

What version of the picker r u using?

**Comment by dmesmin** [comment]
I'm using "ng-pick-datetime": "4.1.2"
I've also tested with several 4.x.x versions with the same result

how do you run your ionic project ? Please try with the browser platform:
`ionic cordova platform add browser
ionic run browser`

**Comment by DanielYKPan** [comment]
@dmesmin 
I see the problem.

As you said before, "As soon as the mouse hover the 'set time' button, the values are updated".
But that's so weird. Because I didn't do any hover function on the 'set time' btn.

I guess the problem exists because **ionic run browser** command builds the app running at mobile device browsers.

But when running a desktop browser, like
<img width="778" alt="screen shot 2017-05-19 at 10 43 43 am" src="https://cloud.githubusercontent.com/assets/5952855/26228849/5e73fee8-3c80-11e7-921e-43debd62077e.png">

It works fine.

**Comment by dmesmin** [comment]
yes you're right, `ionic run browser` aims to be run on mobile browsers (but it can also be run on desktop browser). However I'm not using `ionic serve` on my project because it's here only to test the app while making it.
Does that mean that mobile browsers are not supported by this lib ?

**Comment by DanielYKPan** [comment]
@dmesmin 
It definitely supports the mobile browsers.

I guess  when **ionic run browser** aims to be run on mobile devices and you test it in desktop browsers, weird things happen.

**Comment by dmesmin** [comment]
If I test on mobile browsers (eg. open https://test-calendar-dd4ba.firebaseapp.com  on Android), It's not working either. This is not the issue here

**Comment by DanielYKPan** [comment]
can you tell me what the difference is between **ionic serve** and **ionic run browser**?

**Comment by DanielYKPan** [comment]
Update to latest picker version. It should be fixed.
