### ISSUE TITLE
Can not patchValue in reactive form

### ISSUE THREAD

**Issue by chuduyunhuan** [DanielYKPan/date-time-picker#481]
Hello,

I met a problem recently. I use the date-time-picker in angular 6 reactive form. After creating the formGroup, I want to patchValue about the time input, but it never succeeded.
Here is how i use it:
            <input required
              [owlDateTime]="datePick"
              [owlDateTimeTrigger]="datePick"
              placeholder="Select Time"
              [min]="this.vo.minDate"
              (keydown)="$event.preventDefault()"
              formControlName="time">
            <owl-date-time #datePick
              [pickerType]="'calendar'"></owl-date-time>

this.grantForm.patchValue({ time: '11/27/2020' });

Look forward to your reply and thanks a lot.

**Comment by DanielYKPan** [comment]
Please use [StackBliz](https://stackblitz.com/) to build a demo to show the issue you mentioned about.
I would close this until it is confirmed to be an issue.

**Comment by manishconfidosoft** [comment]
does owlDateTime work with reactive forms?

**Comment by topratedpvtltd** [comment]
> does owlDateTime work with reactive forms?

I am also having above problem

**Comment by mnj01121990** [comment]
I have the same error. Campaign developer abandoned the project(
