### ISSUE TITLE
Can I use this DateTimePicker in my Ionic Project and Please suggest me which version of Picker I have to Install ???

### ISSUE THREAD

**Issue by thurimerla** [DanielYKPan/date-time-picker#482]
Hi @DanielYKPan and @ivanvs ,

I would like to use this date-time-picker in my project.  I mentioning my project dependency details and project Ionic and Angular version below.

**My Desktop Angular Version details**  

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.0-rc.4
Node: 8.11.3
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6 (cli-only)
@angular-devkit/build-optimizer   0.0.35
@angular-devkit/core              0.5.6 (cli-only)
@angular-devkit/schematics        0.5.6 (cli-only)
@schematics/angular               0.5.6 (cli-only)
@schematics/update                0.5.6 (cli-only)
rxjs                              5.5.11
typescript                        2.4.2
webpack                           3.8.1

**My Ionic Project Verion Details** 

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (C:\Users\Lucky Krish\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Lucky Krish\AppData\Local\Android\sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.3.0
   OS                : Windows 10

And **My project Package.json file dependencies**

"dependencies": {
        "@angular/animations": "5.2.10",
        "@angular/common": "5.2.10",
        "@angular/compiler": "5.2.10",
        "@angular/compiler-cli": "5.2.10",
        "@angular/core": "5.2.10",
        "@angular/forms": "5.2.10",
        "@angular/http": "5.2.10",
        "@angular/platform-browser": "5.2.10",
        "@angular/platform-browser-dynamic": "5.2.10",
        "@angular/router": "5.2.10",
        "@ionic-native/android-permissions": "^4.9.1",
        "@ionic-native/camera": "^4.11.0",
        "@ionic-native/core": "4.7.0",
        "@ionic-native/device": "^4.10.0",
        "@ionic-native/geolocation": "^4.9.1",
        "@ionic-native/http": "^4.12.2",
        "@ionic-native/keyboard": "^4.11.0",
        "@ionic-native/push": "^4.12.2",
        "@ionic-native/screen-orientation": "^4.11.0",
        "@ionic-native/splash-screen": "4.7.0",
        "@ionic-native/status-bar": "4.7.0",
        "@ionic/pro": "1.0.20",
        "@ionic/storage": "2.1.3",
        "angular-new-router": "github:angular/router",
        "app-scripts": "0.0.0",
        "cordova-common": "^2.2.5",
        "cordova-ios": "4.5.5",
        "cordova-plugin-advanced-http": "^2.0.1",
        "cordova-plugin-android-permissions": "^1.0.0",
        "cordova-plugin-camera": "^4.0.3",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-file": "^6.0.1",
        "cordova-plugin-geolocation": "^4.0.1",
        "cordova-plugin-ionic-keyboard": "^2.0.5",
        "cordova-plugin-ionic-webview": "^1.1.19",
        "cordova-plugin-screen-orientation": "^3.0.1",
        "cordova-plugin-sms": "^1.0.5",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "elementtree": "^0.1.7",
        "es6-promise-plugin": "^4.2.2",
        "ion2-calendar": "^2.2.0",
        "ionic-angular": "3.9.2",
        "ionic2-date-picker": "^1.1.3",
        "ionic2-super-tabs": "^4.2.2",
        "ionicons": "3.0.0",
        "jquery": "^3.3.1",
        "node-sass": "^4.9.3",
        "properties-parser": "^0.3.1",
        "q": "^1.5.1",
        "reflect-metadata": "^0.1.2",
        "rxjs": "5.5.11",
        "sw-toolbox": "3.6.0",
        "typescript": "~2.4.2",
        "zone.js": "0.8.26"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.9",
        "typescript": "~2.6.2"
    },

Please suggest me which version of Picker I have to Install ???

**Comment by thurimerla** [comment]
Hi @DanielYKPan ,

I would like to ask you regarding this issue, Do you have any idea to resolve my issue or not ??

If not means please tell me and please don't stay in silent mode.

If you give reply I am very thankful to you @DanielYKPan

**Comment by DanielYKPan** [comment]
Please read the README.md
