### ISSUE TITLE
Class constructor BasePortalOutlet cannot be invoked without 'new'

### ISSUE THREAD

**Issue by PunkHaz4rd** [DanielYKPan/date-time-picker#485]
I'm having the message "Class constructor BasePortalOutlet cannot be invoked without 'new'" in the console when I try to open the picker as a modal.
The picker don't show.

I'm using :
    "ng-pick-datetime": "^6.0.16",
    "ng-pick-datetime-moment": "^1.0.7",

Thanks

**Comment by DanielYKPan** [comment]
Use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about

I would close this until it is confirmed as an issue

**Comment by PunkHaz4rd** [comment]
After trying different things, the message no longer appear when I remove  pickerMode="dialog" from the <owl-date-time> tag.
I don't have the time to make a stackblitz and rebuild the whole setup since I use a lot of things coupled together, Angular/Material, OwlDateTimeModule and OwlMomentDateTimeModule.

I guess I'll use it without the dialog look.

**Comment by rmn-kmr** [comment]
I also get this issue.

https://github.com/DanielYKPan/date-time-picker/issues/628

**Comment by rmn-kmr** [comment]
Got this same issue in my application too.

https://github.com/DanielYKPan/date-time-picker/issues/628

**Comment by nasgolfren** [comment]
Same here.... removing param "pickerMode" helped!
