### ISSUE TITLE
Request: Add a unique html id on the Cancel button and the Set button.

### ISSUE THREAD

**Issue by MKollodge-GeoComm** [DanielYKPan/date-time-picker#489]
Want to be able to set the color of the Cancel button apart from the Set button. Being able to reference an id for each in my styles.css would be nice.

ex: 
  id="owl-dt-control-cancel-button"
  id="owl-dt-control-set-button"

**Comment by DanielYKPan** [comment]
You could use css selector the select the particular btn to set the css style you like.
