### ISSUE TITLE
Selected Date is not effecting after changing month or year to another. It is making User Mistakes 

### ISSUE THREAD

**Issue by thurimerla** [DanielYKPan/date-time-picker#490]
Hi @DanielYKPan ,

Please check your <a href="https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker" target="_blank"> Starckblitz</a> , It is making user mistakes with date selection.

By default it is showing current date as default date, I selected default date in the same month after selecting I was changed to another month and year.

After changing month and year , date is not highlighting in that month, and at this point I was clicked **SET** button it showing only Default date in my Input field.

See this attached file.

![date-time-picker__dateissue](https://user-images.githubusercontent.com/38013298/46205791-a5fd5880-c33f-11e8-988e-06a16c32e7e2.gif)

So please change Date on every click event on Calendar either  freeze **SET** button until user selects the Date of the Particular month and  year.

Thanks in advance if you consider my request, It making user mistakes so please change this scenario of date selection.

**Comment by DanielYKPan** [comment]
This is an intended behaviour.

**Comment by thurimerla** [comment]
Hi  @DanielYKPan ,

Is it right scenario ?? , Remember one thing , all users are not developers.

It is great plugin but this scenorio not good at all.

Thanks for giving reply.

**Comment by razvan-urs** [comment]
IMHO this is a bug. When changing month/year - the selected day is not highlighted anymore, but if you press 'Set', the day is updated to the day of the newly selected month.

Very confusing for a user and inconsistent. When you press the 'Next' or 'Previous' month button, your selected month is already changing +-1, but the selected day still highlights in the previous month selection.
