### ISSUE TITLE
Peer dependencies in Angular 6

### ISSUE THREAD

**Issue by devnpl** [DanielYKPan/date-time-picker#499]
![peerdependencies](https://user-images.githubusercontent.com/20554938/46966113-0c5ad880-d0ad-11e8-8c5e-3237db8b045b.JPG)

I am working with Angular since 5 months. I have updated angular from 5 to 6. To build online I should not have any warning in my project but got some. 

I have not understand  peer dependencies. How can I install them?

Thanks

**Comment by DanielYKPan** [comment]
just npm install the right version
