### ISSUE TITLE
Invalid form when using pipe in ngModel.

### ISSUE THREAD

**Issue by Gabb1995** [DanielYKPan/date-time-picker#501]
<input matInput [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1" [ngModel]="element.expires_at|date:'yyyy/MM/dd HH:mm:ss'" (ngModelChange)="element.expires_at = $event" placeholder="{{element.expires_at|date:'yyyy/MM/dd HH:mm:ss'}}" value="{{element.expires_at|date:'yyyy/MM/dd HH:mm:ss'}}">
              <owl-date-time #dt1 [startAt]="element.expires_at" [showSecondsTimer]="true"></owl-date-time>

![peek 2018-10-18 15-49](https://user-images.githubusercontent.com/20728259/47159131-73ff6680-d2ed-11e8-9f47-7f27ff30e6c7.gif)

If I remove the pipe from ngModel no invalid form input is given but date is not the right format:

              <input matInput [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1" [ngModel]="element.expires_at" (ngModelChange)="element.expires_at = $event" placeholder="{{element.expires_at|date:'yyyy/MM/dd HH:mm:ss'}}" value="{{element.expires_at|date:'yyyy/MM/dd HH:mm:ss'}}">
              <owl-date-time #dt1 [startAt]="element.expires_at" [showSecondsTimer]="true"></owl-date-time>

![peek 2018-10-18 15-51](https://user-images.githubusercontent.com/20728259/47159226-af019a00-d2ed-11e8-80b5-f0bbf971722e.gif)

Any ideas on how I can fix this? I am assuming it happens because owlDateTime expects Date Object but when I use the pipe it turns it into a string?

**Comment by DanielYKPan** [comment]
You r 100% correct, the picker only accept date object

**Comment by Gabb1995** [comment]
any idea if I can fix it somehow so its not invalid? or is it impossible?
