### ISSUE TITLE
allow [owlDateTime] directiveon any elements 

### ISSUE THREAD

**Issue by domiSchenk** [DanielYKPan/date-time-picker#502]
This Component cannot be used with ionic .
It would be great to allow it for any elements not only on inputs.

```
 <ion-input 
     [(ngModel)]="value" 
     [formControlName]="field"
     [owlDateTime]="dt1" <-- Not allowed
     [owlDateTimeTrigger]="dt1"> <-- only this works

</ion-input>
```

**Comment by DanielYKPan** [comment]
Please use [StackBliz](https://stackblitz.com/) to build a demo to show the issue you mentioned about.
I would close this until it is confirmed to be an issue.
