### ISSUE TITLE
Timezone is off by one (PST vs PDT) when code is served from a server but works locally.

### ISSUE THREAD

**Issue by yharaskrik** [DanielYKPan/date-time-picker#504]
I am in PDT (-7:00).
Our servers are is EDT (-3:00) (but system clock is in UTC)

Locally when I get the date (through ngModel) using the NativeDateTime module it is correct at -7:00 from UTC but when the code is built and deployed to our servers then served to me the same Datetime picker gives me the time in PST (-8:00). 

```<mat-form-field class="w-100">
<input matInput [owlDateTime]="dt1" [owlDateTimeTrigger]="dt1"
placeholder="Start Time"
[(ngModel)]="date1"/>
<owl-date-time [hour12Timer]="true" #dt1
(afterPickerClosed)="checkDate()"></owl-date-time>
</mat-form-field>```

```
    checkDate(): void {
        console.log('Using dates: ', this.date1, this.date2);
    }```

Any ideas as to why it would be an hour off?

**Comment by DanielYKPan** [comment]
the picker would provide the Javascript date object in the browser's timezone. The picker is pure front-end, nothing about your server location. You should adjust the timezone in your backend.
