### ISSUE TITLE
Show local time inside picker but send Utc to server

### ISSUE THREAD

**Issue by Exerlol** [DanielYKPan/date-time-picker#506]
Hello, first of all thanks for great plugin and all the work you've put in it!
Now let me explain what I'm trying to accomplish - I was wondering if its possible to show LOCAL date and time inside picker but once form is submitted its converted to UTC... I tryed setting 
`{ provide: OWL_MOMENT_DATE_TIME_ADAPTER_OPTIONS, useValue: { useUtc: true } }`
and date and time sent to server is ok, but picker is showing UTC time as well (which in my time zone is -2 hours)... I've tried creating my own custom DateTimeAdapter but since documentation is kinda poor on this subject I've had no luck... If needed I can copy what I've got so far... Any help is well appreciated! Thanks in advance!

**Comment by DanielYKPan** [comment]
This is not part of the picker. For general purpose, the picker would always provide Date Object for the local browser. You could modify the object in your own component into any form (UTC, or any others format), before sending value to your backend
