### ISSUE TITLE
'backdropClass' and 'panelClass' do not appear to have an affect

### ISSUE THREAD

**Issue by lstrahan** [DanielYKPan/date-time-picker#507]
backdropClass and panelClass do not appear to do anything. Below is an example o how I am applying them to the control. But when I do this the appearance of the datetime picker does not change in any way.

**control.html**
`<input [(ngModel)]="dateValue"
    [owlDateTimeTrigger]="dt" [owlDateTime]="dt">
<owl-date-time #dt backdropClass="myBackdropClass" panelClass="myPanelClass "></owl-date-time>`

**control.css**
.myBackdropClass {
      background: red;
      color: blue;
}

.myPanelClass {
  background: green;
  color: yellow;
}

**Comment by DanielYKPan** [comment]
The backdropClass and panelClass do apply to backdrop and panel. And you css setting might be overwritten by other css. You should set you css setting's priority
