### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by Dhinendran** [DanielYKPan/date-time-picker#508]
ERROR in node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(13,44): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(14,46): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng-pick-datetime/date-time/date-time-picker.component.d.ts(2,62): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/ng-pick-datetime/dialog/dialog-config.class.d.ts(2,32): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/ng-pick-datetime/dialog/dialog-container.component.d.ts(3,34): error TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/ng-pick-datetime/dialog/dialog-container.component.d.ts(4,84): error TS2307: Cannot find module '@angular/cdk/portal'.
node_modules/ng-pick-datetime/dialog/dialog-ref.class.d.ts(2,28): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/ng-pick-datetime/dialog/dialog.service.d.ts(6,59): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/ng-pick-datetime/dialog/dialog.service.d.ts(7,31): error TS2307: Cannot find module '@angular/cdk/portal'.

**Comment by Yin-Xie** [comment]
the same to me

**Comment by yonnyviz** [comment]
Me too...

**Comment by DanielYKPan** [comment]
Please use [https://stackblitz.com/](Stackblitz) to build app to show the error you mention about. I would close this until it is confirmed to be an issue.
