### ISSUE TITLE
ng build --prod not working

### ISSUE THREAD

**Issue by Yin-Xie** [DanielYKPan/date-time-picker#510]
main.9bd87d08aa935f352ced.js:1 ERROR Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.

**Comment by DanielYKPan** [comment]
Please use [https://stackblitz.com/](Stackblitz) to build app to show the error you mention about. I would close this until it is confirmed to be an issue.
