### ISSUE TITLE
24 hour format display 

### ISSUE THREAD

**Issue by vatsaldashani** [DanielYKPan/date-time-picker#512]
I need 24-hour format display time in an input tag
![qaqaq](https://user-images.githubusercontent.com/44401963/47360850-1b193f00-d6ee-11e8-9283-4895419dd53d.png)

**Comment by DanielYKPan** [comment]
Please the read the README and the demo page

**Comment by vatsaldashani** [comment]
I need a display of 6:01 instead  of 18:01
see the pic.

**Comment by divya130** [comment]
have  you got solution @vatsaldashani,  even i have to display in 24 hour format

**Comment by NandKishorrech** [comment]
export const DATE_NATIVE_FORMATS = {
    fullPickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', hour12: false},
    datePickerInput: {year: 'numeric', month: 'numeric', day: 'numeric', hour12: false},
    timePickerInput: {hour: 'numeric', minute: 'numeric', hour12: false},
    monthYearLabel: {year: 'numeric', month: 'short'},
    dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
    monthYearA11yLabel: {year: 'numeric', month: 'long'},
  };

add this line in module.ts:
  { provide: OWL_DATE_TIME_FORMATS, useValue: DATE_NATIVE_FORMATS }, 

you will get 24hrs format time.
