### ISSUE TITLE
Initializers are not allowed in ambient contexts

### ISSUE THREAD

**Issue by Yin-Xie** [DanielYKPan/date-time-picker#515]
Initializers are not allowed in ambient contexts

**Comment by DanielYKPan** [comment]
Please use https://stackblitz.com/ to build app to show the error you mention about. I would close this until it is confirmed to be an issue.

If you continue to spam me, I would block you forever

**Comment by mluis** [comment]
I'm having this issue under these versions:
Angular CLI: 7.1.0
Node: 8.10.0
OS: linux x64
Angular: 5.2.11
