### ISSUE TITLE
Initializers are not allowed in ambient contexts while using typescript@2.7.2

### ISSUE THREAD

**Issue by Harish-flujo** [DanielYKPan/date-time-picker#516]
ERROR in node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(13,44): error TS1039: Initializers are not allowed in ambient contexts.

node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(14,46): error TS1039: Initializers are not allowed in ambient contexts.

**Comment by ilyshkafeed** [comment]
Update TypeScript

**Comment by alok-srivastav** [comment]
Hey @ilyshkafeed , to which version of typescript I should update?

Currently I am using typescript version of **^2.8.1** and @angular/cli of version 1.7.3 and @angular/compiler-cli of version ^5.2.9. Tried updating the version to the latest even.

Still facing the issue!! Please suggest.

**Comment by rohit-aneja** [comment]
`npm install ng-pick-datetime@6.0.16`

Works on angular 6

**Comment by Maulik009** [comment]
@ilyshkafeed worked at my end by updating typescript by following command :
`npm install -g typescript@latest`
