### ISSUE TITLE
z-index is not work

### ISSUE THREAD

**Issue by taipeiwu** [DanielYKPan/date-time-picker#53]
z-index is not work in ng2-admin.
![1495923730096](https://cloud.githubusercontent.com/assets/8307585/26524701/93946320-436e-11e7-8d4e-267a7ae5bffd.jpg)

but I use another package(ng2-daterangepicker) in ng2-admin can work.
![1495924083333](https://cloud.githubusercontent.com/assets/8307585/26524720/077679d6-436f-11e7-8fbc-d47e4e8d84ad.jpg)

**Comment by DanielYKPan** [comment]
@taipeiwu 
just overwrite the z-index in your globe css file

.picker-box { z-index: Whatever_Suits_You !important; }

**Comment by taipeiwu** [comment]
@DanielYKPan , I have been overwrite the z-index in my globe css file, but is not working.
![abcdefg](https://cloud.githubusercontent.com/assets/8307585/26529049/383e781c-43eb-11e7-994c-97ae4c4245da.png)
