### ISSUE TITLE
[Request] disabling animation

### ISSUE THREAD

**Issue by johaven** [DanielYKPan/date-time-picker#57]
Is it possible to add an option to disable dropdown/popup animation ?

**Comment by DanielYKPan** [comment]
@johaven 
Just override the css in your global css file
eg
`
.picker-dropdown {
  animation: none !important;
}
`
or
`
.picker-popup {
  animation: none !important;
}
`

**Comment by johaven** [comment]
.owl-moment-picker {
  top: 100px !important;

  &.owl-picker-popup {
    animation: none !important;
    -webkit-animation: none !important;
    -moz-animation: none !important;
  }
}

With sass overwrite it's not woking, any idea ?
