### ISSUE TITLE
I faced same issue when build at --prod mode.

### ISSUE THREAD

**Issue by dhananjaykaushik** [DanielYKPan/date-time-picker#571]
I faced same issue when build at --prod mode.
@DanielYKPan  did you fix this issue for version 5.2.6 and 5.2.8. We can't upgrade angular to new version.
Can you provide step by step to fix this issue with angular 5.2.8?

_Originally posted by @viethien in https://github.com/DanielYKPan/date-time-picker/issues/369#issuecomment-446031783_

**Comment by dhananjaykaushik** [comment]
Still facing this issue. Need help ?

**Comment by Shpiller** [comment]
yes

**Comment by Shpiller** [comment]
I got this error only with aot compilation on. When update values of datetime on my form.

"Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal."

I have in my package json
"ng-pick-datetime": "7.0.0",
"@angular/cdk": "7.3.3",

**Comment by dhananjaykaushik** [comment]
I'm facing this issue still too
    "@angular/cli": "~6.2.4",
    "@angular/cdk": "^6.4.6",
    "@angular/cdk-experimental": "^6.4.5",
    "ng-pick-datetime": "^5.2.6"

@DanielYKPan please respond

**Comment by Shpiller** [comment]
I'm sorry, it's my mistake.
I had this erro on other library, not date-time-picker

All works on package json
"ng-pick-datetime": "7.0.0",
"@angular/cdk": "7.3.3",

**Comment by dhananjaykaushik** [comment]
@Shpiller goof for you. But I am still facing the issue

**Comment by thefiscina** [comment]
Também estou enfrentando esse problema em produção!

Alguém achou alguma solução?

[English]
I'm also facing this problem in production!
Has anyone found a solution?

vendor.b472475a451305a2fb8c.bundle.js:1 ERROR Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.
    at vendor.b472475a451305a2fb8c.bundle.js:1
    at t.e.attach (vendor.b472475a451305a2fb8c.bundle.js:1)
    at e.attach (vendor.b472475a451305a2fb8c.bundle.js:1)
    at t.openAsPopup (vendor.b472475a451305a2fb8c.bundle.js:1)
    at t.open (vendor.b472475a451305a2fb8c.bundle.js:1)
    at e.handleClickOnHost (vendor.b472475a451305a2fb8c.bundle.js:1)
    at Object.handleEvent (main.4ea0619a36621196dea5.bundle.js:1)
    at Object.handleEvent (vendor.b472475a451305a2fb8c.bundle.js:1)
    at Object.handleEvent (vendor.b472475a451305a2fb8c.bundle.js:1)
    at Ki (vendor.b472475a451305a2fb8c.bundle.js:1)

**Comment by thefiscina** [comment]
@dhananjaykaushik Não sei o que era esse erro... mas dei um downgrade e funcionou.

[English]
@dhananjaykaushik  I do not know what that mistake was ... but I gave it a downgrade and it worked.

"@angular/cdk": "^5.2.4",
"@angular/common": "^5.2.0",
"ng-pick-datetime": "^5.2.5",
"ng-pick-datetime-moment": "^1.0.6",

npm install ng-pick-datetime@5.2.5 --save

**Comment by dhananjaykaushik** [comment]
I switched the library and it worked :)

**Comment by Ragini26** [comment]
@dhananjaykaushik  which library you are using ?

**Comment by Ragini26** [comment]
I am facing the same issue .. 
  "@angular/cdk": "^5.2.5",
 "ng-pick-datetime": "^5.2.5",
please help

**Comment by dhananjaykaushik** [comment]
https://ng-bootstrap.github.io/#/components/datepicker/overview
Now I'm using this with some custom modifications
