### ISSUE TITLE
TypeError: this._document.createElement is not a function

### ISSUE THREAD

**Issue by mykytaknyzevkiy** [DanielYKPan/date-time-picker#575]
I got this error when click input only on build prod version

**Comment by BrothelBoy** [comment]
same，
Have you solved it?

**Comment by tolapuramakrishna** [comment]
any solution to this?

**Comment by Vishwas-yadav** [comment]
I have Resolved this issue by re-installing:  "ng-pick-datetime": "^7.0.0"
