### ISSUE TITLE
Feature-Request: Open Datepicker via Button / Icon (attribute mode?)

### ISSUE THREAD

**Issue by tobigit** [DanielYKPan/date-time-picker#59]
Nice datepicker, thank you for this!

It would  be nice when the picker could be opened via a datepicker-icon or a button.
If I could pass an selector of dom-element which then open the calendar I would be happy.

**Comment by DanielYKPan** [comment]
@tobigit 
This is a angular directive, so you could use it in a button or a icon.

**Comment by lutchit** [comment]
Hello @DanielYKPan, do you have an exemple how to do this behaviour ?
The following code doesn't work:

```
<md-icon (click)="datePicker1.click()" class="detailPickerIcon">date_range</md-icon>
<input #datePicker1 class="detailPicker" [value]="momentVariable | date:'medium'" [(ngModel)]="momentVariable" dateTimePicker [hourTime]="'12'"
      readonly [maxMoment]=pickerToday (onChange)="setMoment($event)" [disabled]="!printerService.isCurrentPrinter">
```

Thank you !

**Comment by burnaDLX** [comment]
It seems like this doesn't work in the latest version... can anyone confirm this?

**Comment by burnaDLX** [comment]
I made a [simplified plunkr](https://plnkr.co/edit/PkEJSC9qs75jYWSCXimc?p=preview) to reproduce this issue. Can you help me?

**Comment by PerfectlyNormal** [comment]
I fixed it by adding a button `<button type="button" class="btn btn-default" (click)="departureTime.onInputClick($event);">` where `departureTime` is the reference to the datepicker. (`#datePicker1` in your example, @lutchit )
