### ISSUE TITLE
Translate widget buttons

### ISSUE THREAD

**Issue by maxvt0** [DanielYKPan/date-time-picker#60]
Hi, I have question about translations. Can I anyhow translate buttons like "Today" "Set Time" etc.
Enything else works great but i cannot find anywhere info how to translate those buttons.

**Comment by DanielYKPan** [comment]
@maxvt0 
What language r u looking for?

**Comment by maxvt0** [comment]
I am looking for Polish Language.

**Comment by DanielYKPan** [comment]
use `[locale]=" 'pl' "` attribute

**Comment by maxvt0** [comment]
I used it, but buttons did not change it's Labels.
And sorry but I forgot to add that i am using version for Angular 2.* not for 4.*

**Comment by DanielYKPan** [comment]
Sorry, it only support angular 4.

**Comment by maxvt0** [comment]
OK. If so i will need to update my project. Thanks for help
