### ISSUE TITLE
Shame on you for stealing my code

### ISSUE THREAD

**Issue by MurhafSousli** [DanielYKPan/date-time-picker#606]
I am reporting you to Github for stealing 2 of my projects which are protected under GNU v3 license

https://github.com/DanielYKPan/ng-memory

https://github.com/murhafsousli/memory

----------------------

https://github.com/DanielYKPan/ng-puzzle

https://github.com/murhafsousli/8puzzle

You call your self a passionate developer! but you are actually a passionate thief.

Don't you feel ashamed when you steal other people projects and publish them as they are your own handy work.

Shame on you.

**Comment by DanielYKPan** [comment]
This code was intended to as the my process of Learning Angular. Never trying to steal or sell anyone's I.P. I have made this repo as private. sorry for any troubles.
