### ISSUE TITLE
Can you add these two new languages?

### ISSUE THREAD

**Issue by druidamix** [DanielYKPan/date-time-picker#61]
Hi,
Would you add the two languages I paste? Catalan and Spanish.

And release a new version.

Thanks 

/**
 * ca
 */

export const LANG_CA_TRANS = {
    'time picker': 'Selector de Temps',
    'today': 'Avui',
    'set time': 'Selecciona Temps',
    'close': 'Tancar',
    'confirm': 'Confirmar',
    'hour': 'Hora',
    'minute': 'Minut',
    'second': 'Segón',
};

/**
 * es
 */

export const LANG_ES_TRANS = {
    'time picker': 'Selector de Tiempo',
    'today': 'Hoy',
    'set time': 'Seleccionar Tiempo',
    'close': 'Cerrar',
    'confirm': 'Confirmar',
    'hour': 'Hora',
    'minute': 'Minuto',
    'second': 'Segundo',
};

**Comment by DanielYKPan** [comment]
@druidamix 
Thanks,
it will be in next release.
