### ISSUE TITLE
when I open div in full screen than ng-pick-datetime not open in full Screen.

### ISSUE THREAD

**Issue by kevalpanchalHops** [DanielYKPan/date-time-picker#617]
when I open Div in full screen than ng-pick-datetime not open its not work in full screen.

**Comment by tanganellilore** [comment]
I think the proble is similar to this one #587

**Comment by kevalpanchalHops** [comment]
But there is not any popup its just full screen in some div and date picker is with in.

**Comment by tanganellilore** [comment]
dipend where the div is positioned, and if your div have bsolute or not activated.
attach some example

**Comment by kevalpanchalHops** [comment]
HTML CODE::
<div class="example-wrapper" #mainDiv>
    <h2>Basic</h2>

    <label class="example-input-wrapper">
        Date Time:
        <input placeholder="Date Time:"
               [(ngModel)]="dateTime"
               [owlDateTimeTrigger]="dt" [owlDateTime]="dt">
        <owl-date-time #dt></owl-date-time>
    </label>

    <h4>Value From Picker: {{dateTime}}</h4>
</div>
<button (click)="open()">fullscreen</button>

ts Code :: 
import { Component, ElementRef, Input, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular';

  @ViewChild('mainDiv',null) mainDiv: ElementRef;

  open(){
    this.GoInFullscreen(this.mainDiv.nativeElement);
  }

  GoInFullscreen(element) {
	if(element.requestFullscreen)
		element.requestFullscreen();
	else if(element.mozRequestFullScreen)
		element.mozRequestFullScreen();
	else if(element.webkitRequestFullscreen)
		element.webkitRequestFullscreen();
	else if(element.msRequestFullscreen)
		element.msRequestFullscreen();
  }
}

**Comment by tanganellilore** [comment]
Sorry but this not help us.
Use [stackblitz.com](stackblitz.com) to replicate the situation.

Probably in fullscreen's request the div go out from screen.
Consider that RequestFullScreen not compatibilty with Opera, Safari and all mobile browser.

Moreover, inspection mode in the div can help us to understand where is the problem

**Comment by kevalpanchalHops** [comment]
stackblitz :: https://stackblitz.com/edit/angular-h2svj5?embed=1&file=src/app/app.component.html

**Comment by tanganellilore** [comment]
cdk overaly problem : [https://github.com/angular/components/issues/10679](https://github.com/angular/components/issues/10679)

Not related to this library. This library use cdk-overlay to render the panel, i think the bug is related to cdk-overlay library

**Comment by kevalpanchalHops** [comment]
This issue solved by just adding in provider OverlayContainer.
{ provide: OverlayContainer, useClass: FullscreenOverlayContainer }
thaks @tanganellilore .
