### ISSUE TITLE
other control events stop firing after date selection

### ISSUE THREAD

**Issue by Jrssnyder** [DanielYKPan/date-time-picker#62]
I am using a Visual Studio template created via the "dotnet new angular" command (with which you may or may not be familiar) - it creates an angular 2 template, which leverages webpack.

I have a form which is working fine in all respects, until I add the ng2-date-time-picker control. The control works fine in terms of passing the selected values to a variable on the component when I set it up as explained here: https://www.npmjs.com/package/ng2-date-time-picker.

My markup:
<input name="manualTime" id="manualTime" #manualTime="ngModel"
			   [ngModel]="punchPageDto.timeInfo.manualTime | date: 'short'"
			   [dateTimePicker]="punchPageDto.timeInfo.manualTime"
			   (dateTimePickerChange)="handleTimeOverride($event)"
			   [mode]="'dropdown'"
			   [hourTime]="'12'"
			   readonly />

However, after the value is saved to punchPageDto.timeInfo.manualTime in the handleTimeOverride method, the following happens:
-- The submit button no longer triggers the (submit) method bound to the form.
-- Checkboxes on the form stop firing a (change) event.

It is as if the datepicker control does not return event handling to the main form. I do note, however, that (click) events continue to fire.

I like this control, but I obviously can't use it if other controls on my form (including the submit button) become nonresponsive. 

Any ideas?

**Comment by DanielYKPan** [comment]
@Jrssnyder 
Sorry, https://www.npmjs.com/package/ng2-date-time-picker has been deprecated.
 You may try https://www.npmjs.com/package/ng-pick-datetime 

The new package only support angular 4.* project

**Comment by salok8705** [comment]
@DanielYKPan  
Hi Daniel , i have gone through your documenation for ng-pick-datetime and it says following:
The picker has been updated for Angular 6+ apps. If you are still using Angular 5, you should install the picker version 5.2.6. npm install ng-pick-datetime@5.2.6 --save
Added Output Events yearSelected, monthSelected.

I am using angular 5.1.0 and want to implement year-month view only which needs "yearSelected" and "monthSelected"  handler and i followed all the steps but still these handlers are not getting called.
i have followed everything which is given in following url:
https://stackblitz.com/github/DanielYKPan/owl-examples/tree/date-time-picker?file=src%2Fapp%2Fyear-month%2Fyear-month.component.ts

could you please help me in this ...thanks in advance :)

**Comment by DanielYKPan** [comment]
ng-pick-datetime@5.2.6 is no longer maintained. So new feature "yearSelected" is only in Version 6

**Comment by magebharath** [comment]
I am using Angular 7 bur monthSelected Not Firing??:?
