### ISSUE TITLE
my options are not taking effect

### ISSUE THREAD

**Issue by derridHeidegger** [DanielYKPan/date-time-picker#63]
hi 
i installed and pass some options but it doesn't change accordingly
i have this in my template
`        <div class="form-group">
           <input class="picker-input"
            id="time-input-1"
            [ngModel]="input1Moment | date: 'short'"
            [(dateTimePicker)]="input1Moment"
            [mode]="'inline'"
            [theme]="'#006633'"
            [value]="input1Moment | date: 'short'"
            [locale]=" 'he' "
            readonly>
        </div>`
and in my component
`public input1Moment: any;`
and even through i ask for inline, it uses popup, no he for locale and no change in theme color.

what am i missing?
i am on angular 4 and
"ng-pick-datetime": "^4.1.2"

**Comment by derridHeidegger** [comment]
by the way, sometimes it display as i ask but most display as the default popup and colors

**Comment by DanielYKPan** [comment]
I guess that would be problem with your app, not with the package.
