### ISSUE TITLE
Compatibility with Angular 8

### ISSUE THREAD

**Issue by sovushka-utrom** [DanielYKPan/date-time-picker#632]
Hi!
Is there any chance this module will be compatible with Angular 8? 
As we migrated our project to Angular 8, now we have this warning in console:
warning " > ng-pick-datetime@7.0.0" has incorrect peer dependency "@angular/cdk@^7.0.0".

**Comment by Anzil-Aufait** [comment]
@sovushka-utrom  , did you fix this issue ??

**Comment by danielmoncada** [comment]
It  still works for me in an NG 8 application, we just have these errors..

**Comment by sovushka-utrom** [comment]
Since it was updated to compatibility with Angular 8, it works fine & we don't have any warnings. Thank you for reacting so fast to this request.
@danielmoncada, try updating the module (yarn add ng-pick-datetime), the warning should disappear. 
For me, this issue can be closed.

**Comment by danielmoncada** [comment]
I'm running the latest version 7.0.0 and am still receiving the warning.

```html
warning " > ng-pick-datetime@7.0.0" has incorrect peer dependency "@angular/cdk@^7.0.0".
```

**Comment by sovushka-utrom** [comment]
From my yarn.lock:  
"@angular/cdk@^8.0.0":  
  version "8.1.4"  
ng-pick-datetime@^7.0.0:  
  version "7.0.0"  
And I don't get any notification on start nor on build.
I'm afraid I can't help you further.

**Comment by thonythony** [comment]
Is ng-pick-datetime with Angular 8 support has been released ?

**Comment by constantinoschristoforou** [comment]
Any updates on the angular 8 version? it  seems that the latest npm release is for angular 7

**Comment by danielmoncada** [comment]
@thonythony @constantinoschristoforou I have since forked this, and released an updated version. https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker
