### ISSUE TITLE
Positionning issue with Microsoft Edge

### ISSUE THREAD

**Issue by jm-plagnard** [DanielYKPan/date-time-picker#64]
My code
`<input
            class="form-control picker-input"
            name="inputDate"
            [ngModel]="moment| date: 'MM/dd/yy'"
            [mode]="'dropdown'"
            [position]=" 'bottom' "
            [(dateTimePicker)]="moment" 
          >`

On the attached screenshot you can see that the words "close" and "today" are outside of the box.
Please note that this is happening only when the page width is small.
It's happening only in dropdown mode

![bug](https://user-images.githubusercontent.com/2590874/27250036-422d60a2-52f2-11e7-9474-a1701204eda6.png)

**Comment by DanielYKPan** [comment]
what is size of the page?

**Comment by jm-plagnard** [comment]
It seems to occur only when the size of the input text in under 250px.
It may be related to the min-width css of the picker-dropdown class

**Comment by DanielYKPan** [comment]
@jm-plagnard 
But based on the image you shown, it was not about the width, more likely about the height.

Have you tried the picker in a clean style project? I mean a project without any external css framework or css styles?

**Comment by DanielYKPan** [comment]
@jm-plagnard 
Update to latest picker version. It should be fixed.
