### ISSUE TITLE
Date selected in popup does not gets set in input field

### ISSUE THREAD

**Issue by kdkaur89** [DanielYKPan/date-time-picker#65]
I am currently using Angular 4. Integrated the module from the steps mentioned but when I select the date it is not getting set in the input field.

My input field is part of form.
Code Snippet:
  <input "class = "form-control" formControlName ="test" [dateTimePicker]="test" (dateTimePickerChange)="setMoment($event)" readonly />

The date is present when printed from "setMoment" but the input box remains empty

**Comment by DanielYKPan** [comment]
you have to bind your variable to your input value
