### ISSUE TITLE
[ng-pick-datetime-moment] Angular 8 aot compilation fails 

### ISSUE THREAD

**Issue by michaelsivo** [DanielYKPan/date-time-picker#667]
Hi,
I'm using ng-pick-datetime with the moment adapter you are providing.
When trying to compile in aot, I have the following error:

`
ERROR in ../ng-pick-datetime-moment/moment-adapter/moment-date-time.module.ts(22,2): Error during template compile of 'OwlMomentDateTimeModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
`

I'm in angular 8.2.10, moment 2.24 and lastest ng-pick-datetime and ng-pick-datetime-moment.

**Comment by marcinkunert** [comment]
@michaelsivo try this: https://github.com/DanielYKPan/date-time-picker/issues/597#issuecomment-500061595 
Seems to work for me

**Comment by michaelsivo** [comment]
Ok, it works thanks
