### ISSUE TITLE
Reset the date-time-picker when locale change

### ISSUE THREAD

**Issue by normandjulian** [DanielYKPan/date-time-picker#68]
When I use the locale, It change the language for the calendar 👍  :
`<input formControlName="creationStartDate" readonly placeholder="Date"
                        [pickerType]="'date'" [ngModel]="creationStartDate | date: 'shortDate'"
                        [(dateTimePicker)]="creationStartDate" [mode]="'dropdown'"
                        [locale]="language"/>`

### Change the language dynamically
The user can change its language in another component, and I catch it the set the **language** variable with Obersable :
`this.auth.getLanguage().subscribe((language: string) => this.language = language);`

- But the language of the date-time-picker isn't reset when the this.language change.

### Set the LOCALE_ID with the locale variable
The Angular pipe I use ('shortDate'), display the result in english way ('mm/dd'/yyyy') even I set 'fr' because the LOCAL_ID of Angular is 'en-US' by default.

- Can the date-time-picker set the LOCAL_ID of Angular with its own property ?

**Comment by DanielYKPan** [comment]
@normandjulian 
There is definitely a way to change the language dynamically. But I think it is better not to implement it.
If you want to change the language of picker, you may also want to change the language of the whole page or other parts of the page. So it is not a good practice to just try to solve language of the picker

**Comment by normandjulian** [comment]
Thank you, I found a way to do it proprelly.
