### ISSUE TITLE
After updating [dateTimePicker] databinding, jump to currently set date?

### ISSUE THREAD

**Issue by sebastianvog** [DanielYKPan/date-time-picker#71]
Hello,
not sure if this is a bug or feature request:

in my html i have 
<div class="picker-input" [dateTimePicker]="fromDate" (dateTimePickerChange)="pickerFromUpdate($event)" [mode]="'inline'" [style.width]="'250px'" </div>
</div>

In my .ts code I update fromDate to a different month while the picker is being displayed

For example,
i bring up the picker. At the beginning it shows the current date (June)
 I programmtically set date time to May 1st
 
Right now the top bar of the inline picker says May 1st, however the bottom calendar view is still at June.

I am looking for a way to jump to the currently selected date month.

**Comment by DanielYKPan** [comment]
@sebastianvog 
R u using the inline mode?

**Comment by sebastianvog** [comment]
Yes I do use inline mode.. Sorry my pasted html was stripped out in mhy initial post.  My bad. 
here the  template
` <div class="picker-input" [dateTimePicker]="fromDate" (dateTimePickerChange)="pickerFromUpdate($event)" [mode]="'inline'"
              [style.width]="'250px'" [theme]=" '#505050' "></div>
          </div>
`

**Comment by DanielYKPan** [comment]
@sebastianvog 
The issue has been fixed. Please update ng-pick-datetime to latest version.

**Comment by sebastianvog** [comment]
Thanks Daniel, very much appreciated!
