### ISSUE TITLE
cannot set property 'picker' of undefined

### ISSUE THREAD

**Issue by ArtzGroup** [DanielYKPan/date-time-picker#723]
I am using Angular 9. I used owl-date-picker, it works completely fine with input, but when I try INLINE it doesn't work. I went through the documentation and followed exactly. Everything is working, but the <owl-date-time-inline> doesn't work. It gives me "cannot set property 'picker' of undefined" error. Can you please help me on this. Thanks.

`SYSTEM ERROR : "Cannot set property 'picker' of undefined" >>> "TypeError: Cannot set property 'picker' of undefined\n    at OwlDateTimeInlineComponent.push../node_modules/ng-pick-datetime/__ivy_ngcc__/date-time/date-time-inline.component.js.OwlDateTimeInlineComponent.ngOnInit`

`"Cannot read property 'startAt' of undefined" >>> "TypeError: Cannot read property 'startAt' of undefined\n    at OwlDateTimeContainerComponent.push../node_modules/ng-pick-datetime/__ivy_ngcc__/date-time/date-time-picker-container.component.js.OwlDateTimeContainerComponent.initPicker (http://localhost:9233/vendor.js:140606:41)\n    at OwlDateTimeContainerComponent.push../node_modules/ng-pick-datetime/__ivy_ngcc__/date-time/date-time-picker-container.component.js.OwlDateTimeContainerComponent.ngAfterContentInit`

`app.module.ts:94 SYSTEM ERROR : "Cannot read property 'id' of undefined" >>> "TypeError: Cannot read property 'id' of undefined\n    at OwlDateTimeContainerComponent.get [as owlDTContainerId] (http://localhost:9233/vendor.js:140483:32)\n    at OwlDateTimeContainerComponent_HostBindings (http://localhost:9233/vendor.js:140736:77)\n    at setHostBindingsByExecutingExpandoInstructions (http://localhost:9233/vendor.js:62132:25)\n    at refreshView (http://localhost:9233/vendor.js:62418:9)\n    at refreshComponent (http://localhost:9233/vendor.js:63532:9)\n    at refreshChildComponents (http://localhost:9233/vendor.js:62169:9)\n    at refreshView (http://localhost:9233/vendor.js:62422:13)\n    at refreshComponent (http://localhost:9233/vendor.js:63532:9)\n    at refreshChildComponents (http://localhost:9233/vendor.js:62169:9)\n    at refreshView (http://localhost:9233/vendor.js:62422:13)"`

**Comment by RoWEN-FCUB** [comment]
Hello. I was facing a similar error. It seems this library is no longer supported. I move to  danielmoncada /
date-time-picker and now it works fine, even using Angular 10.

**Comment by ArtzGroup** [comment]
> Hello. I was facing a similar error. It seems this library is no longer supported. I move to danielmoncada /
> date-time-picker and now it works fine, even using Angular 10.

Can I get a link for the Repo. Thank you.

**Comment by RoWEN-FCUB** [comment]
https://github.com/danielmoncada/date-time-picker

**Comment by ArtzGroup** [comment]
> https://github.com/danielmoncada/date-time-picker

I tried the installation steps. But, it doesn't compile at all. I just installed it with `npm install @danielmoncada/angular-datetime-picker --save`. I didn't even add it in AppModule yet. Not sure why this happens. Without installing this package, my app is running fine. I am getting this error. 

`AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. **The error output was: Compiling @danielmoncada/angular-datetime-picker : module as esm5**`

I tried npm audit fix, npm fund. But, nothing works.

**Comment by RoWEN-FCUB** [comment]
Sorry if I can't help you more, can you move this issue to https://github.com/danielmoncada/date-time-picker/issues ?? I see there that issues are being anwsered faster.

**Comment by ArtzGroup** [comment]
> Sorry if I can't help you more, can you move this issue to https://github.com/danielmoncada/date-time-picker/issues ?? I see there that issues are being anwsered faster.

Thanks for your help. I created a new issue in the above link. Closing it here.
