### ISSUE TITLE
ERROR in The target entry-point "@danielmoncada/angular-datetime-picker" has missing dependencies:

### ISSUE THREAD

**Issue by ikubij** [DanielYKPan/date-time-picker#725]
ERROR in The target entry-point "@danielmoncada/angular-datetime-picker" has missing dependencies:
 - @angular/cdk/a11y
 - @angular/cdk/overlay
 - @angular/cdk/portal
 - @angular/cdk/keycodes
 - @angular/cdk/coercion
 - @angular/cdk/platform
 - moment

I added the date-time-picker package to a new Angular 10 project and I am getting this issues, Kindly advice.

Also, I am using NGX-Bootstrap, and CDK seems to be for material.

**Comment by ikubij** [comment]
I think you should update the docs, Cause I had to install cdk and moment manually.

**Comment by krunvaghela** [comment]
Worked 
Install 
`npm i @angular/cdk --save`  & 
`npm i @angular/animations --save`
