### ISSUE TITLE
Date Time picker - minutes value not able to slide. minutes value autoslide 

### ISSUE THREAD

**Issue by hraverkar** [DanielYKPan/date-time-picker#74]
I am using "ng-pick-datetime": "^4.2.0" version . i am not able to slide the minutes value . ones i slide, it start auto slide and minutes value changed vary fast.

**Comment by DanielYKPan** [comment]
@hraverkar 
Could you provide a link to git repo that can replicate the issue?

**Comment by sacasher** [comment]
I have the same Issue, [in this Video shows the error](https://www.youtube.com/watch?v=ZtDtKozvaNI)

**Comment by DanielYKPan** [comment]
@sacasher 
What browser version r u testing in the video?

**Comment by sacasher** [comment]
I'm using the 4.2.5 version with node 7.10.0
but in the video, I did the test in the [demo page](https://danielykpan.github.io/date-time-picker/)

**Comment by DanielYKPan** [comment]
@sacasher 
Thanks

I would try to regenerate the issue so that I would be able to fix that.

What system r u using?

**Comment by sacasher** [comment]
My OS is Fedora 25 (Linux 4.11.4-200.fc25.x86_64)

**Comment by DanielYKPan** [comment]
@sacasher 
From what I saw in your video, 
If you mouse up inside the picker, the slider works fine. But if you mouse up outside the picker and move your mouse back to the picker, the picker would always be sliding.
Is that correct?

**Comment by sacasher** [comment]
That's correct, the same happens in the mobile version smartphones and tablets (Android and iOS)

**Comment by FlorianNeiss** [comment]
I have the same bug. Just slide to the left.

**Comment by DanielYKPan** [comment]
@sacasher 
@hraverkar 
Update to latest picker version. It should be fixed.

**Comment by sacasher** [comment]
Thank you @DanielYKPan :)
