### ISSUE TITLE
ng-pick-datetime not compatible with angular 9

### ISSUE THREAD

**Issue by eapatel** [DanielYKPan/date-time-picker#744]
I upgraded angular version from 8 to 9. During ng serve, it throws below error.

```
Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ng-pick-datetime/date-time/adapter/moment-adapter/moment-date-time.module) which declares OwlMomentDateTimeModule has not been processed 
correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

3 export declare class OwlMomentDateTimeModule {

```

package.json
"ng-pick-datetime": "^7.0.0",
"ng-pick-datetime-moment": "^1.0.7", 

How can I support it for angular 9?

**Comment by danielmoncada** [comment]
@eapatel  please use my fork, which supports ng 9+ https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker

@danielmoncada/angular-datetime-picker

**Comment by eapatel** [comment]
Thanks @danielmoncada for the reply. I installed it and it solved all the problems. Thank you so much :)
