### ISSUE TITLE
Time picker doesn't updates in 'inline' view

### ISSUE THREAD

**Issue by ebem** [DanielYKPan/date-time-picker#75]
When date-time picker is in inline mode, the selected  time is not updated in Return Object: at the first, only when i choose another date, then time gets updated. 

To select date and time

The desired result: select date -> select time -> done.
At the moment: Select date -> select time -> select date -> done. 

Version : 4.2.0

P.S Great date-time-picker, besides this small bug.

**Comment by DanielYKPan** [comment]
@ebem 
it would be fixed in next release.

**Comment by DanielYKPan** [comment]
@ebem 
Update to latest picker version. It should be fixed.

**Comment by ebem** [comment]
Thank you! For now I already have different mode for this date-time-picker and I am working on different project, so I can't comment on how it works with inline mode, but if you say it's fixed, then it is.
