### ISSUE TITLE
Fix german translation for 'cancel' please

### ISSUE THREAD

**Issue by tobigit** [DanielYKPan/date-time-picker#76]
This ist the current germen (de) translation:

exports.LANG_DE_TRANS = {
    'time picker': 'Zeit wählen',
    'today': 'Heute',
    'set time': 'Zeit festlegen',
    'close': 'Schließen',
    'cancel': 'Streichen',
    'confirm': 'Bestätigen',
    'hour': 'Stunde',
    'minute': 'Minute',
    'second': 'Sekunde',
};

Please replace 'cancel': 'Streichen' with 'cancel': 'Entfernen'. This means removing the date.

**Comment by DanielYKPan** [comment]
@tobigit 
Thanks man.
