### ISSUE TITLE
Disabled past dates from the picker  

### ISSUE THREAD

**Issue by meghavipatadia** [DanielYKPan/date-time-picker#77]
I want to select only dates after the current date.
when the user tries to select past dates it should be disabled.

**Comment by DanielYKPan** [comment]
This feature would be in next release

**Comment by meghavipatadia** [comment]
Thanks for replying. When do we have next release of date-time-picker?

**Comment by DanielYKPan** [comment]
@meghavipatadia 
In the next couple days. I have to run some tests.

**Comment by meghavipatadia** [comment]
Ok thank you.

**Comment by DanielYKPan** [comment]
@meghavipatadia 
Update to the latest package. Now the picker added **[minMoment]** and **[maxMoment]** to define what valid moment could be selected.
