### ISSUE TITLE
Parameter [position] is not behaving as described in README.md

### ISSUE THREAD

**Issue by HerrSlavchev** [DanielYKPan/date-time-picker#79]
Compare the logic from the following lines:
[dialog-position.directive.ts](https://github.com/DanielYKPan/date-time-picker/blob/master/src/dialog-position.directive.ts#L91-L103)
with this quote from the description:
> [positionOffset]=" '0%' " --- Set the picker position offset in dropdown mode. When you set your position to 'top' or 'bottom', the positionOffset is the percentage of your input box height. When you set your position to 'right' or 'left', the positionOffset is the percentage of your input box width. The value could be minus like '-10%'. (The default value is '0%').

From what I see, when the `[postion]` is set to 'left' or 'right', the `top` field gets modified by a percentage of the component height and vice-versa. 
I think the `top` field should get modified when `[position]` is 'top' or 'bottom'.

**Comment by DanielYKPan** [comment]
@HerrSlavchev 
You r right. when the **[postion]** is set to 'left' or 'right', the top field gets modified by a percentage of the component height **(NOT width)** and vice-versa. I would modify the README.md.

So basically, 
when the **[postion]** is set to 'left' or 'right'. [poistionOffset] would modify the distance between the picker and the input box vertically. That is why the **top** field gets modified.
