### ISSUE TITLE
Cancel set datetime to null

### ISSUE THREAD

**Issue by zizinic** [DanielYKPan/date-time-picker#81]
Hi Daniel,

The plugin is great.  During the using I found a small issue annoys me.  If I tried to use the picker and changed my mind by clicking cancel, the datetime sets to null instead of the original value.  Can you keep the value if click cancel in the panel?

Thanks!

**Comment by zizinic** [comment]
Or if the "cancel" is intended to remove the datetime, can you provide a option to hide and disable the button, which may cause confusion? Thanks again.

**Comment by llozano** [comment]
Agree on this request. This new behavior on setting the value to null when user clicks Cancel button is totally unexpected and probably should be configurable.

**Comment by sebastianvog** [comment]
+1 on this. Cancel should keep the original value in my opinion. Thanks for this great time picker!

**Comment by DanielYKPan** [comment]
I has been fixed.
Update to the latest version. And see all those changes in README.md
