### ISSUE TITLE
minMoment & maxMoment are not updated

### ISSUE THREAD

**Issue by MickaelRomaniello** [DanielYKPan/date-time-picker#82]
Hi,

I have two inputs beginDate and endDate.

I'm using minMoment & maxMoment with date type by example: 

`private minDate: Date;
  private maxDate: Date;`

In my constructor, I set the actual date for the minimum and for the maximum the actual date plus 3 years.

I also need to change the minimum and maximum according to the second input.

I notice that the minMoment and maxMoment are never updated when you change it locally.
Once you have selected a date, if you want to go back to this picker, you select the picker, you will see that the min and max is the same as before, but he is supposed to change.

My minDate and maxDate can change but in the picker no.

Is there a way to fix it? 

Have a great day.

Mickael

**Comment by DanielYKPan** [comment]
I has been fixed.
Update to the latest version. And see all those changes in README.md

**Comment by kesemdavid** [comment]
@DanielYKPan @MickaelRomaniello How exactly did it get fixed? I encounter the exact same situation, my `endDate` should be 2 minutes after my `beginDate`, the min of the `endDate` does not update on `beginDate` changes.. Can you please provide an example showing what it is fixed and how to use it? Thanks!

**Comment by kesemdavid** [comment]
@DanielYKPan I don't actually have one but ill provide the relevant code:

__html__:
```         
<span class="field-name">Starting Time:</span>
<input name="startingTime"
            class="date-input"
            [value]="startingTime"
            [mode]="'inline'"
            [minMoment]="minStartingTime.format('YYYY-MM-DD')"
            [returnObject]="'moment'"
            [(ngModel)]="startingTime"
            (ngModelChange)="calculateMinEndingTime()"
            dateTimePicker
            required/>
</div>

<span class="field-name">Ending Time:</span>
<input name="endingTime"
            class="date-input"
            [value]="endingTime"
            [mode]="'inline'"
            [minMoment]="formattedNinEndingTime"
            [returnObject]="'moment'"
            [(ngModel)]="endingTime"
            dateTimePicker
            required/>

```

__component__
```
  public calculateMinEndingTime() {
    this.minEndingTime = moment(this.startingTime);
    this.minEndingTime.add(2, 'm');
    this.formattedNinEndingTime = this.minEndingTime.format('YYYY-MM-DD')
  }

```

As you can see, as the `startingTime` changes the `calculateMinEndingTime` triggers to add 2 minutes to that `startingTime` and set it as the `minEndingTime`, unfortunately, it never changes in the view

Thanks in advance for the help :)

**Comment by DanielYKPan** [comment]
@kesemdavid 
Update the package to ^4.3.4, and it should be all right

PS: If you add 2 minutes, you may consider to format the minEndingTime to 'YYYY-MM-DD HH:mm'.
Cheers

**Comment by kesemdavid** [comment]
@DanielYKPan 
I've updated the package but unfortunately the `endingTime` picker does not update on `startingTime` changes.
Is it implemented in a way it should be updated by the local reference?
If so, could you please provide the simplest example using this feature?

Thanks again, I'm lost here .. :|

**Comment by kesemdavid** [comment]
@DanielYKPan P.S the 'YYYY-MM-DD HH:mm' does not seem to work, the `minMoment` seems to totally ignore the given string with that format
