### ISSUE TITLE
Highlight certain days

### ISSUE THREAD

**Issue by budlink** [DanielYKPan/date-time-picker#83]
How do I add a class to certain dates?

**Comment by DanielYKPan** [comment]
@budlink 
Sorry, currently no

**Comment by LasithaPrabodha** [comment]
@DanielYKPan Can you add this please?

**Comment by dtomasbar** [comment]
Weekend highlight is a thing i miss in this component. Any chance to introduce it in the next release?

**Comment by kishor-bhatt** [comment]
How to highlight certain dates where some events are scheduled, any support for this or workaround please ?
Thanks.

**Comment by DanielYKPan** [comment]
You could highlight certain day, weekday, month or year via your own css file.

Year: each year cell has a class `owl-dt-year-` + Year Number. Eg for 2020 cell, it has a class `owl-dt-year-2020`

Month: each month cell has a class `owl-dt-month-` + Month Number. Month Number is from 0 (January) to 11 (December). Eg for May, it has a class `owl-dt-month-4`

Weekday: each day cell has a class `owl-dt-day-` + WeekDay Number. WeekDay Number is from 0 (Sunday) to 6 (Saturday). Eg for Monday, it has a class `owl-dt-day-1`.

Day: each day has aria-label value. Eg for day **May 12, 2018**, it has a aria-label value `aria-label="May 12, 2018"`. You could set this day's css via selector `.owl-dt-calendar-cell[aria-label="May 12, 2018"]`

**Comment by kishor-bhatt** [comment]
Hi Daniel,

Thanks a lot for your solution. I will do that.
In case if you have a similar GIT repository for Calendar showing some
highlighted dates in dashboard, please share the link.

Thanks again,
Kishor
