### ISSUE TITLE
Starting day of week

### ISSUE THREAD

**Issue by pavel-buchacek** [DanielYKPan/date-time-picker#84]
Hi Daniel,
I have problem with starting day of the week. My locale seems to be configured well (names of days, months, etc. are translated correctly by Moment). I am using CS locale, so starting day of month should be monday. But week in datepicker starts with sunday actually.

I am using current version of picker (4.2.2). It was working well in older versions. I think it stopped working in version 4.2.0.

I think, the same problem is in your online demo as well. You are using FR locale there and IMO first day should be monday, but it is sunday.

**Comment by DanielYKPan** [comment]
@pavel-buchacek 
Thanks, man.
I already fixed it. I will release a new version in the next couple day.

**Comment by DanielYKPan** [comment]
I has been fixed.
Update to the latest version. And see all those changes in README.md
