### ISSUE TITLE
v4.2.3 completely breaks our app!

### ISSUE THREAD

**Issue by Sky4CE** [DanielYKPan/date-time-picker#87]
Changes like [this](https://github.com/DanielYKPan/date-time-picker/commit/bcf2ff40fd88c1da39feaf3dd00bc2728c5c4c41#diff-04c6e90faac2675aa89e2176d2eec7d8R87) usually interpreted as **breaking change**. Are you sure about 4.2.**3** ? It is rather v5 with these changes to api.
By the way, seems like there is no (easy) way to bring our app to work with these changes, because we use `[(dateTimePicker)]=` and `[(ngModel)]=` together. Could you please show how to do it now ?

**Comment by DanielYKPan** [comment]
@Sky4CE 
we don't use `[(dateTimePicker)]=` and `[(ngModel)]=` together
we use `dateTimePicker` and `[(ngModel)]`
You could read more from README.md or from the Demo page

**Comment by Sky4CE** [comment]
@DanielYKPan , yes I see, but prior 4.2.3 I could use it together, so our logic depend on this.

**Comment by tonghia** [comment]
New version break out project too,
![screenshot_1](https://user-images.githubusercontent.com/11595722/28298761-551e6268-6b9f-11e7-953a-025dc6cfc44e.png)

I think I would revert back to old version, hope that you can have a look at these new version issues.
Thank you.

**Comment by DanielYKPan** [comment]
In your case, you may try this
```html
<div>
    <input class="picker-input"
           [value]="data | amDataFormat: dateTimeFormat"
           dateTimePicker
           [ngModel]="data"
           [mode]="'dropdown'"
           [returnObject]="'moment'"
           [pickerType]="pickerType"
           [hourTime]="hourTime"
           [(disabled)]="disabled"
           (onChange)="onChange($event)"
           readonly>
</div>
```

**Comment by Sky4CE** [comment]
@DanielYKPan , it works this way, thank you very much.
