### ISSUE TITLE
Wrong display of min & max date

### ISSUE THREAD

**Issue by MickaelRomaniello** [DanielYKPan/date-time-picker#88]
Hi,

I saw a few issues regarding the min and max date.

The max date is actual year - 18 years. The thing is that actually, we can see the years in black, not like in gray like it supposed to be. Is it possible to have the year in gray and also to disable the click?

Years:
![image](https://user-images.githubusercontent.com/4235811/28304641-d3c76878-6b98-11e7-9a19-6ba277a92db1.png)

The min date for hours is at + 2 hours. Actually we can see the same colour as usual and we can also slide. 
Is it possible to have a gray colour for the hours under the minimum and also disabled the slide under the specified time in the min date or max date?

Hours:
![image](https://user-images.githubusercontent.com/4235811/28306313-1a4900bc-6b9f-11e7-8df4-2b03ac688e9b.png)

Days (good behaviour) : 
![image](https://user-images.githubusercontent.com/4235811/28304767-6842a33c-6b99-11e7-8dcb-2d1891e0c8e1.png)

I saw another issue.

When you set a minimum date, it takes this date but the hours are not updated:

Actual date + 2 hours, should be 12.

![image](https://user-images.githubusercontent.com/4235811/28306589-21c8f08a-6ba0-11e7-8959-3f5b6aeeb6bd.png)

Another example date + 48 hours.

![image](https://user-images.githubusercontent.com/4235811/28307335-db0febc8-6ba2-11e7-856e-98c734032542.png)

Is it possible to fix this?

I hope that my explanation are understandable.

Have a great day.

Mickael

**Comment by DanielYKPan** [comment]
It was difficult to follow what you just described. You could build a simple app to demonstrate the issues, and share a git repo to me.

**Comment by MickaelRomaniello** [comment]
Simply: 

When you set a min date or max date. It works well. The only problem that there is that you don't show the information that it is blocked. That you can't access to these dates. 

Example : **Min Date 20 of June 2015** 

**Each years** : 2011 2012 2013 are in black but they should be in gray. You can also click on these years but normally you shouldn't. 

You can't select 2011 because the minimum is 2015.

![image](https://user-images.githubusercontent.com/4235811/28317257-72cae7c4-6bc6-11e7-9162-81a4d3900a07.png)

Example 2 : **Min Date 20 of June 2015 08:55** 

**The text of time** : 06:53 are in blue but they should be in gray. You can also slide on these hours but normally you shouldn't. 

You can't select 06:53 because the minimum is 08:55.

![image](https://user-images.githubusercontent.com/4235811/28317309-b25348f0-6bc6-11e7-8f93-6cd90d5f1c63.png)

Is it clearer now?

**Comment by DanielYKPan** [comment]
The slider could still be moved, but I am sure you could not confirm the time which is not between min and max.
