### ISSUE TITLE
Error: Can't resolve all parameters for SlideControlComponent

### ISSUE THREAD

**Issue by yaseerhaja** [DanielYKPan/date-time-picker#91]
Hi Team,

I tried to implement this date-time picker. 
As i followed all as per instruction. 
When i tried to run i got above error.
Any help is much appreciated.

I m using angular 2 with webpack.

**Comment by xifengxx** [comment]
I met the same error.
`Can't resolve all parameters for SlideControlComponent`.
when not import 'DateTimePickerModule' in app.module.ts, it's ok, and the angular progress works well, when import it, it occur errors.
My angular2 progress version is:

> @angular/cli: 1.2.6
node: 8.1.4
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.2.6
@angular/compiler-cli: 2.4.10

when I upgrade my program from angular 2 to angular 4, it works well and don't have this error.

**Comment by DanielYKPan** [comment]
This package use Angular animation. And angular 2 and angular 4 have different animation configuration. So this package only support Angular 4.
