### ISSUE TITLE
Header Date display format

### ISSUE THREAD

**Issue by jigarpt** [DanielYKPan/date-time-picker#92]
Hi, 

Thanks a lot for this amazing component. 

I am wondering is there a way to change the date format of "selected date being displayed in header section"?

![image](https://user-images.githubusercontent.com/28896871/28371436-9f3fcbc2-6cba-11e7-98c6-1b2409f3d847.png)

Thanks,
Jigar.

**Comment by DanielYKPan** [comment]
@jigarpt 
What kind of format do you like to use?

**Comment by jigarpt** [comment]
@DanielYKPan 

Thanks for your response. Ideally there should be a configuration option where we should be able to specify header display format For Ex. DD-MMM-YYYY HH:MM. I would like to see below kind of format. 

![image](https://user-images.githubusercontent.com/28896871/29258937-c0f1f788-80db-11e7-9594-03a9e61512d5.png)

Thanks, 
Jigar
