### ISSUE TITLE
ngModel does not work with Angular 4 reactive forms

### ISSUE THREAD

**Issue by tomschreck** [DanielYKPan/date-time-picker#93]
Your latest update (4.3.0) uses ngModel to bind data,  How do you bind data to your date-time-picker when implementing data entry forms using Angular 4's reactive forms?  Reactive forms do not use ngModel.

I tried using `[ngModel]="momentValue" (onChange)="setMoment($event)"` as referenced in your help, however, the Date/Time value in popup was never getting bound to the value in the form.  The popup would just default to today's value.

Is it possible to use date-time-picker with reactive forms approach for Angular 4?

**Comment by Vorlif** [comment]
Hey Tomschreck,

the last version implements the ControlValueAccessor interface.
That means you can use the date-time-picker like any other formular component (input, select, etc.). You can now easy use `[formControl]="momentValue"`.

I hope this helps.

**Comment by itsmekhanh** [comment]
Not sure if this is a bug, but when I tried using `[formControl]`, it doesn't render the initial value when the datetime picker pops up. Instead of rendering the initialized date and time, it just shows the current time and date.
```
      <input
          dateTimePicker
          id="dispatch-settings_start-time"
          type="text"
          [formControl]="dispatchForm.controls.startTimeForm"
          [mode]="'dropdown'"
          [pickerType]="'time'"
          [hourTime]="'12'"
          readonly>
```

`dispatchForm.controls.startTimeForm` has an initial value.

**Comment by Vorlif** [comment]
Yes, same problem here. 

@DanielYKPan are you planning to fix this?

**Comment by DanielYKPan** [comment]
@Vorlif 
Yes, I am trying to fix this

**Comment by DanielYKPan** [comment]
@Vorlif @itsmekhanh 
Try the package version @4.3.2

See if this fixed the issues

**Comment by Vorlif** [comment]
@DanielYKPan 
Works for me. Thank you for your work and the quick fix.
