### ISSUE TITLE
missing step attribute for time sliders

### ISSUE THREAD

**Issue by tomschreck** [DanielYKPan/date-time-picker#95]
I just upgraded to version 4.3.0 from version 4.0.5.  In version 4.0.5, time-panel.component.js had capability to set a [step] attribute for time sliders.  It defaulted to 1 so the minute slider would be for every value between 0 and 59.  I manually modified the [step] attribute value to 5 so the slider for minutes would be every 5 minutes (0 - 59 but every 5 minute increment).  I do not need minute precision.  Is it possible to add [step] attribute back and surface it to optional attribute values please?  Thanks.

**Comment by jhhoff02** [comment]
I would like the same feature. Could you please post the code for manually setting step attribute for minutes? Thank you

**Comment by antb-developer** [comment]
go to node_modules -> locale -> slider.component.js 

line no. 11 ->
this.step = 1;
to
this.step = 15;
