### ISSUE TITLE
Confirm and cancel button styling

### ISSUE THREAD

**Issue by chrisexv6** [DanielYKPan/date-time-picker#96]
Updated from the last version that had the Confirm button as a nice clean circle.  Would like to be able to get that styling back, if possible, but i cant see an easy way to override it.

I've been able to re-style the rest of the control but not the confirmation (and cancel) buttons.  Also miss the Today link in the calendar but that already seems to be an open issue.

Love everything about the picker (especially the new min and max Moment additions).  Keep up the good work!

**Comment by DanielYKPan** [comment]
@chrisexv6 
The confirm and cancel button are under '.owl-foot-control .control-btn' class.
You could override the shape or the color of the button by using this class.
PS: the tick and cross icons inside the button are SVG. If you want to change to color of those icons, please use property 'fill'
