### ISSUE TITLE
IOS: Time Picker no slider

### ISSUE THREAD

**Issue by MickaelRomaniello** [DanielYKPan/date-time-picker#97]
Hi,

I saw an issue of your time picker with IOS.

The slider of the time picker is not present in my project and also in your demo page.

![img_0047](https://user-images.githubusercontent.com/4235811/28514635-0b072f6e-705b-11e7-864d-d8936946012f.PNG)

![img_0046](https://user-images.githubusercontent.com/4235811/28514641-0e7d72f2-705b-11e7-91e3-920fda7ff0ae.PNG)

Have a great day!

Mickael Romaniello

**Comment by DanielYKPan** [comment]
@MickaelRomaniello 
Do you know the reason why? Because I am not familiar with the ios

**Comment by MickaelRomaniello** [comment]
For now, I don't know really but I will  try to find why.

**Comment by DanielYKPan** [comment]
@MickaelRomaniello 
I got it. It would be fixed in next release.

**Comment by MickaelRomaniello** [comment]
Perfect! I will test it when it will be available.

**Comment by ryanstelmat** [comment]
I'd love to see this fix get pushed through as well. It's a bummer not having it work for Safari :)

**Comment by socx** [comment]
It'll be great to have it working on Safari. I believe it has something to do with the flex used in the css class `.owl-date-panel-calendar-row` . The calendar currently appears thus:-
![calendar-on-safari](https://user-images.githubusercontent.com/5908636/28990811-cd05a7d2-7978-11e7-8758-f54523c931a5.png)

**Comment by DanielYKPan** [comment]
What environment are you using?

**Comment by MickaelRomaniello** [comment]
HI @DanielYKPan,

When do you think to release the fix?

**Comment by DanielYKPan** [comment]
@MickaelRomaniello 
Try the 4.3.1

**Comment by MickaelRomaniello** [comment]
Thank you I will, It's just that I didn't see it in the "Updates"

**Comment by socx** [comment]
@DanielYKPan   I just updated to 4.3.1 I can see the time sliders have been fixed in Safari (I am using Safari 5.1.7 on Windows 7). This is what it looks it 
![calendar-on-safari-4 3 1](https://user-images.githubusercontent.com/5908636/29001631-8cc6463a-7a87-11e7-9aab-b45b3ec72999.png)

**Comment by DanielYKPan** [comment]
@socx 
I guess this is because safari 5.1.7 dose not support css flex

**Comment by kesemdavid** [comment]
@DanielYKPan @MickaelRomaniello  How can i disable the sliders and use inputs like in the first picture?
