### ISSUE TITLE
Can't bind to 'minMoment' 

### ISSUE THREAD

**Issue by antb-developer** [DanielYKPan/date-time-picker#98]
Can't bind to 'minMoment' since it isn't a known property of 'input'.
My input is 
                      <input class="form-control"  type="text"  [mode]="'dropdown'"  [minMoment]="'2017-09-07 19:30:40'"  [(dateTimePicker)]="date" [ngModel]="date | date: 'M/d/y HH:mm:ss'">

Other attributes like mode , are working properly

**Comment by DanielYKPan** [comment]
@antb-developer 
This picker has been changed. Please use it like this:
`<input [value]="momentValue | date: 'short'" [(ngModel)]="momentValue" dateTimePicker />`
