### ISSUE TITLE
ngOnInit problem

### ISSUE THREAD

**Issue by BadiuAlexandru** [DanielYKPan/date-time-picker#99]
I want to setValue for my form control on ngOnInit event, but it doesn't update the control, instead if I make a different button with this functionality with a different function, then it works great, but on ngOnInit it doesn't want to work at all.

**Comment by DanielYKPan** [comment]
try not use ngOnInit, use AfterViewInit or AfterContentInit

**Comment by BadiuAlexandru** [comment]
ok, thank you for your answer, I will try this and come back with a feedback

**Comment by BadiuAlexandru** [comment]
I tried and it doesn't work, I used both AfterViewInit and AfterContentInit and no success

**Comment by BadiuAlexandru** [comment]
can somebody help me with a workaround for this? or with a solution?

**Comment by DanielYKPan** [comment]
Could you create a git project to demonstrate the issue?

**Comment by BadiuAlexandru** [comment]
The issue is that you cannot set datepicker value when you enter on the page, on all events: OnInit, AfterViewInit, AfterContentInit ... you can set his value only after body loads... I will try to create a git

**Comment by DanielYKPan** [comment]
Try the package version @4.3.2

See if this fixed the issues
